### ISSUE TITLE
How to create a non-built-in pcap packet source plugin?

### ISSUE THREAD

**Issue by simonhf** [zeek/zeek#1009]
I successfully created a live packet source plugin -- which works on a particular NIC / interface -- and everything seems to work fine. The plugin has special functionality which isn't relevant to the issue topic. However, the next step in development was to add the ability for the plugin to start in non-live mode and replay one or more pcap files, but the packets are still subject to the special plugin functionality.

I had problems getting the packet source plugin to work in non-live mode for pcap packets without modifying the Zeek source outside the plugin.

For adding the pcap functionality to my originally live-only packet source plugin, I looked carefully at the built-in pcap packet source which itself uses a special mode and can be either 'live' or 'non-live' depending upon whether it is recording pcap traffic or replaying pcap traffic [2], so the plugin registers itself using `::iosource::PktSrcComponent::BOTH` instead of the more common `::iosource::PktSrcComponent::LIVE`. And similarly at run-time it sets the `.is_live` flag to true [3] or false [4].

I did the same in my packet source plugin -- using `::iosource::PktSrcComponent::BOTH` and conditionally setting `.is_live` -- but came to the conclusion that setting `.is_live` to false for my packet source plugin pcap mode made no difference and would not enable Zeek to work correctly with the packet timestamps extracted from the pcap.

To me it looks like the `.is_live` flag is ignored here [5] and also the `if/else` which controls non-live mode for Zeek packet sources is hard-coded by the non-plugin `pcap_input_file` variable?.

I came up with a workaround PR [6] which seems backwards compatible with how the existing packet source plugins work, and even seems to 'fix' `.is_live` from being ignored. My intention was to have the lightest touch, but maybe my PR does make a confusing API even more confusing? Or maybe it does fix the `.is_live` plugin flag and make the API slightly less confusing?

For me it seems like the packet source plugin mode `::iosource::PktSrcComponent::BOTH` was never made abstract enough in the first place in the sense that a non-live / pcap packet source plugin appears to have to rely on the non-plugin `pcap_input_file`. So for example, if you want to create a pcap packet source plugin which processes a never ending queue of pcaps, the API doesn't seem to allow that, or?

Would it be possible to accept my PR [6] as a stepping stone? And then have this github issue to capture the todo item / place-marker to refactor the packet source plugin API to make it more flexible and/or intention revealing... which seems like a much longer discussion on what it should look like and how it should operate? Not to mention all the extensive testing that would be necessary for a refactor.

Or could / should the PR [6] be modified to kill two birds with one stone? If so, what could be ways and suggestions to make it better?

[1] https://github.com/zeek/zeek/blob/v3.1.4/src/Net.cc#L148
[2] https://github.com/zeek/zeek/blob/v3.1.4/src/iosource/pcap/Plugin.cc
[3] https://github.com/zeek/zeek/blob/v3.1.4/src/iosource/pcap/Source.cc#L170
[4] https://github.com/zeek/zeek/blob/v3.1.4/src/iosource/pcap/Source.cc#L193
[5] https://github.com/zeek/zeek/blob/v3.1.4/src/Net.cc#L148
[6] https://github.com/zeek/zeek/pull/1005

**Comment by jsiwek** [comment]
> I had problems getting the packet source plugin to work in non-live mode for pcap packets without modifying the Zeek source outside the plugin.

The quick (and possibly pedantic) response is that you may not technically need to modify Zeek source in terms of just implementing something equivalent to #1005 entirely inside a plugin: `OpenPktSrc()` will end up calling the virtual `PktSrc::Open()` method which is implemented by your plugin and so changing the `reading_live` and `reading_traces` global variables is something you can do in code you control and at equivalent point in Zeek's initialization process.

> Would it be possible to accept my PR [6] as a stepping stone? And then have this github issue to capture the todo item / place-marker to refactor the packet source plugin API to make it more flexible and/or intention revealing... which seems like a much longer discussion on what it should look like and how it should operate? Not to mention all the extensive testing that would be necessary for a refactor.

Won't deny that you've possibly run into a usage scenario where original API/architecture didn't anticipate, doesn't work well with, or lacks intuitive/obvious means to support, but not strongly convinced whether  #1005 is worthwhile as generalized solution especially since the plugin can technically do that itself inside its `Open()` method (and I also haven't stepped through your plugin to really understand the reason it's needed).  Conservative next step would be waiting to see if the other shoe drops and you find another problem that really does require changing logic/architecture on the Zeek side.

**Comment by simonhf** [comment]
Thanks so much for this suggestion @jsiwek because it worked!

Adding the following lines to my pcap packet source plugin makes everything work by only modifying the plugin and not changing Zeek:
```
...
extern bool reading_live  ; // Zeek global variable
extern bool reading_traces; // Zeek global variable
...
void ...::Open() {
    ...
    props.is_live = false;
    reading_live = false;
    reading_traces = true;
    ...
}
```

Oddly enough I had tried setting `reading_traces` previously but I didn't actually `extern` it, and I probably didn't set `reading_live` too. Anyway, it's all good now. Thanks again! :-)

**Comment by jsiwek** [comment]
> Oddly enough I had tried setting `reading_traces` previously but I didn't actually `extern` it

Could also `#include "Net.h"` if that feels like a less flaky way to get those declarations.  In a general sense, this all still sounds awkward that you have to do this and possibly easily broken in future if things get restructured.

Will close this for now, but maybe you'll eventually get an idea of how to make this behavior more explicit.  One idea could be building in a bit more logic to the `-r` or `-i` (or add a third flag) that explicitly toggles the use of this kind of "hybrid time semantics".  So like there's currently `zeek -i <iface>` (reading_live) and `zeek -r <pcap file>` (reading_traces), but seems like you're looking for `zeek -r <iface>`: if `iface` isn't a file, but there exists an interface with that name, read packets it from it, but treat the advancement of time similarly to that of an offline pcap file instead of live/current network traffic.

**Comment by simonhf** [comment]
> One idea could be building in a bit more logic to the `-r` or `-i`

Yeah, in my case I'm using `-i` to not supply a real interface but to supply a hint to my packet source plugin regarding how to get / find the packets via shared memory from another process which itself can supply the packets from different sources including live NICs or pcap files!
