### ISSUE TITLE
Broker: LIST cannot be converted to broker type

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#1033]
The Zeek List type currently cannot be converted into a broker datatype. The type just is missing from ``val_converter`` in ``broker/Data.cc``.

I assuming implementing this may also require a new data type on the broker side. This is required to support zeek<->broker syncing of tables with list-types as the key.

**Comment by jsiwek** [comment]
You may not need support for a distinct "list" type on the Broker side: it shouldn't be meaningfully different from a Broker "vector" in terms of what you'd use it for if I'm guessing right that you just need to store an arbitrary sequence of values?  So:

* Zeek stores/sends a `ListVal` as a `broker::vector`.  Sub-elements in the list are recursively mapped to the right Broker data type.

* Zeek loads/receives a `broker::vector` and knows based on context what `zeek::Type` to map it back to.  E.g. you know the target `ListType`, so create an associated `ListVal` for it and recursively map sub-elements of the `broker::vector` to associated index of the `ListVal`.

Though, I don't know without looking more at your code if that logic should just get put in the existing `val_converter` or would work better as separate layer.

**Comment by rsmmr** [comment]
@johanna can you comment whether this needs Broker change?

**Comment by Neverlord** [comment]
Looking at the Zeek API, it seems like just adding an extra `if`-block in `result_type operator()(broker::vector& a)` (Data.cc) is tricky. In general, the recursive approach outlined by @jsiwek is what we'd want. However, there's no bijective mapping from Broker types to Zeek types. We use `broker::vector` for `TYPE_VECTOR`, `TYPE_FUNC`, `TYPE_RECORD` and `TYPE_PATTERN`. The `VectorType` gets around this problem, because it's homogenous and we can access the expected element types via `type->AsVectorType()->YieldType()`.

Do we have additional type information / restrictions for the synchronization? Not allowing to nest vector/func/record/pattern in lists that interface with Broker could get around this issue, because this would allow us to assume `LIST_TYPE` for `broker::vector` when recursively reading elements of the list. If we do need the "full range", then we'd need some alternative to `broker::vector` with additional type information (`broker::tagged_vector` maybe?).

**Comment by Neverlord** [comment]
... or we mirror the types of Zeek with `broker::data`, i.e., make the mapping bijective. 🙂

**Comment by jsiwek** [comment]
> We use `broker::vector` for `TYPE_VECTOR`, `TYPE_FUNC`, `TYPE_RECORD` and `TYPE_PATTERN`. The `VectorType` gets around this problem, because it's homogenous and we can access the expected element types via `type->AsVectorType()->YieldType()`.

A Zeek List does explicitly allow heterogeneous element types, but don't think that alters the situation: in either case we should still know what Zeek type in being targeted.  i.e. mapping `broker::vector` -> `zeek::Vector` can inspect `VectorType::YieldType()` while `broker::vector` -> `zeek::List` can inspect the targeted `TypeList::GetTypes()` at any given index (and logic unfolds recursively from there).

> Do we have additional type information / restrictions for the synchronization?

There's a wildcard, `any`, type that could potentially cause complications, but it may be the existing logic to handle that already takes care of it and needs no further changes in any new List-handling logic.  That existing logic being that all `any` types are just wrapped inside Zeek as opaque `DataVal`, which stores the original `broker::data`, and users must explicitly pick a `zeek::Type` to cast it to.

**Comment by rsmmr** [comment]
So it doesn't sound like this is pressing, I'm move to 4.0.

**Comment by 0xxon** [comment]
Sorry - I forgot to answer this. I will try to just implement this using vectors - like discussed here.
