### ISSUE TITLE
zeek workers crash

### ISSUE THREAD

**Issue by venki522** [zeek/zeek#1047]
deployed seek on 2 servers.workers on one node and mgr,proxy,logger on another node.Workers are frequently getting crashed.Need some help to figure out why workers are getting crashed.please find the below config on the box.any help is much appreciated.

[worker]
type=worker
host=x.x.x.x
interface=af_packet::eno1
lb_method=custom
lb_procs=50
pin_cpus=4,5,6,7,8,9,10,11,12,13,20,21,22,23,24,25,26,27,17,18,19,42,43,44,45,46,47,48,49,50,51,52,53,54,55,31,32,33,34,35,36,37,38,39,40,41,14,15,16,30
af_packet_buffer_size=1*1024*1024*1024

**Comment by jsiwek** [comment]
That's not enough information to really help much.  Running `zeekctl diag` may be a starting point for you to understand more about what happened, but I'd generally suggest seeking further help on either the mailing list or slack first (https://zeek.org/connect) since there's better community feedback there for general support questions whereas GitHub issues are used for tracking actionable bugs/projects.
