### ISSUE TITLE
btest language/function-closures.zeek crashes if run w/o -b

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#1055]
This btest specifies -b.  If you happen to leave that off when running Zeek on the script, it exits with ```internal error: Attempted to clone an id ('cat_dog') with no associated value.
Abort``` which seems like it can't be good.  There's no mention in the script to expect such behavior.

**Comment by jsiwek** [comment]
Yeah, not Good, but maybe encountered before in #886 where I mention another test case of the weird/unexpected `-b` vs no-`b` behavior.  Rather than close this as duplicate, think to leave it open as a separate test to help verify any potential patches.

(Also noting that #734 may also be wrapped up with the underlying issue, too, but can't tell at a glance)
