### ISSUE TITLE
A field error in detect-sqli.zeek

### ISSUE THREAD

**Issue by xiong-liu** [zeek/zeek#1092]
![](https://liuxiong-1302419765.cos.ap-guangzhou.myqcloud.com/markdown/20200729094341.png)

>Maybe this place should be dst field,because this key$host is destination IP

![](https://liuxiong-1302419765.cos.ap-guangzhou.myqcloud.com/markdown/20200729094806.png)

**Comment by jsiwek** [comment]
It generally seems fine to me for a "responder" part of a Connection to act as a "source" for the purpose of a Notice since those are different contexts with potentially different perspectives.  I.e. originator/responder have meaning in broader context of a Connection, while source/destination have different meaning for narrower context, such as individual Packet or Notice.

**Comment by 0xxon** [comment]
Yup, I agree. Closing this since it seems semantically correct.
