### ISSUE TITLE
Remove the counter type

### ISSUE THREAD

**Issue by grigorescu** [zeek/zeek#1095]
Per the [discussion in Slack](https://zeekorg.slack.com/archives/CTGDG83B8/p1596128357182800), consider removing the `counter` type. The following code will segfault:

```
event zeek_init()
	{
	local a: counter = 1;
	a += 1;
	print a;
    }
```

It seems like under the hood, it's identical to a `count`, but was never really used.

**Comment by 0xxon** [comment]
This one is kind of interesting from a deprecation perspective.

We don't really have a method for deprecating a type, right?

Also - since it doesn't exactly work at the moment, I am kind of tempted to just rip it out. However, removing the TYPE_COUNTER enum might break external code - I assume some people copy/pasted from us and have that as a case in input readers/writers.

In any case - I made topic/johanna/1095-just-get-rid-of-it - which just completely rips out all traces of counter. I am not quite sure if we should just merge this - or do some kind of deprecation.

**Comment by grigorescu** [comment]
Would it be enough to just change this message to say that it's deprecated, will be removed, and use a count instead?

https://github.com/zeek/zeek/blob/54c9f4a0e1a3ca8a75576b477b8d94d06053b6f4/src/Type.h#L940

**Comment by 0xxon** [comment]
Yup, that would change the notice for old code. I doubt that people will notice though - they will probably just change it over to the Zeek namespace together with everything else. Unless we already remove the type in 3.2 - and it is too late for that.

**Comment by jsiwek** [comment]
Thoughts:

* Since using `counter` in scripts has been broken even before 3.0, that part of the scripting-language seems fine to remove right away.

* For the internal `::TYPE_COUNTER` that's already deprecated, change it to say "Use zeek::TYPE_COUNT" since that's the right direction for people migrating from 3.0 to 4.0 LTS.

* For the internal `zeek::TYPE_COUNTER` that's new in 3.2, we could either remove it on grounds that minor/Feature releases don't have as strict API-stability goals as between major/LTS versions, or add the deprecation: "Remove in v4.1. Use zeek::TYPE_COUNT".  Don't think it's "hard" to do the deprecation if it helps save some time/confusion for people migrating from 3.2 to 4.0 that had originally copy/pasted -- and by deprecation, I only mean keeping the identifier around until 4.1, not trying to keep all our own usages around since they appear to not be entirely functional anyway.

**Comment by 0xxon** [comment]
Sounds good to me - I will change my branch tomorrow-ish.
