### ISSUE TITLE
Kerberos 'till' value is always 2136422885

### ISSUE THREAD

**Issue by l0x-c0d3z** [zeek/zeek#1112]
I'm trying to figure out what's going on. For almost all my kerberos tickets, the `till` field has the same value (2136422885).

```
 zcat  */kerberos* |jq .till  |sort | uniq -c
      1 1591770236
      1 1596112779
      1 1596112856
      1 1596120827
      1 1596122245
      1 1596122790
      1 1596204050
      1 1596293407
      1 1596382414
      1 1596616118
      1 1596616208
      1 1596659365
      1 1596732008
   4111 2136422885
   3880 null
```

Here is a sample log:
```
{"ts":1596735356.29559,"uid":"Cie8uf9Y6O8lfMyqk","id.orig_h":"10.0.32.17","id.orig_p":50294,"id.resp_h":"10.0.32.5","id.resp_p":88,"request_type":"TGS","client":"user2/LAB.COM","service":"LDAP/labdc.lab.com/lab.com","success":true,"till":2136422885.0,"cipher":"aes256-cts-hmac-sha1-96","forwardable":true,"renewable":true}
```

**Comment by grigorescu** [comment]
Interesting, thanks for the issue.

I'm still doing some digging, but I actually don't think this is a bug with the analyzer, I think that's what you're seeing on the wire.

That epoch timestamp (2136422885) is Sunday, September 13, 2037 2:48:05 AM GMT. I found this post, which frustratingly has no answer complaining about the same date: https://willson.tk/kerberos_weird_date.html

I found that person's GitHub repo, but was unable to find the PCAP they said was there. There was some content on there related to Bro, so perhaps it's just confirmation bias.

There is a test in the Zeek test suite that exhibits this behavior: testing/btest/scripts/base/protocols/krb/krb-service-name.test and the associated PCAP is testing/btest/Traces/krb/optional-service-name.pcap.

Opening the PCAP in Wireshark reveals the suspect till time, `2037-09-13 02:48:05 (UTC)`. I also tried [an ASN1 decoder](https://lapo.it/asn1js/#MGahAwIBBaIDAgEKpFowWKAHAwUAQAAAEKIaGxhrZXJiZXJvc19yZWFsbV90aW1lLm5hc2ylERgPMjAzNzA5MTMwMjQ4MDVaphEYDzIwMzcwOTEzMDI0ODA1WqcEAgJl1agFMAMCAQs) and got the same thing.

My suspicion is that this is a bug in Microsoft's Kerberos implementation. Given how close the date is to the [Y2K38 problem](https://en.wikipedia.org/wiki/Year_2038_problem), I think they try to not set the value at all, then something gets subtracted from it, and we end up with that date.

**Comment by grigorescu** [comment]
Ok, I think I've figured this out. There's a bug in Kerberos.dll in the `KerbGetAuthenticationTicketEx` function. Rough pseudocode is:

`  RtlTimeToTimeFields(&Time, &TimeFields);
  if ( TimeFields.Year <= 2037 )
      LOWORD(v477) = TimeFields.Year;
  else
      LOWORD(v477) = 2037;

  BYTE2(v477) = TimeFields.Month;
  HIBYTE(v477) = TimeFields.Day;
  v478 = TimeFields.Hour;
  v479 = TimeFields.Minute;
  v480 = TimeFields.Second;
`

As you can see, there's some data size confusion regarding month and day. These fields are stored in a struct, so once that gets messed up, the rest follows.

What it's trying to do is to set the date far in the future, so that the ticket will never expire (the name of the value it's using is `KerbGlobalWillNeverTimeOut`). The server will then give it a real expiration time.

The good news is, you can at least use this to detect who's using kerberos.dll?

**Comment by vpax** [comment]
Two fun facts I learned today related to this: (1) On the wire, Kerberos transmits timestamps like that **as ASCII strings!**, which I never expected.  So it's really easy to confirm that indeed that's what's being sent and it's not a Zeek bug. Building on that, (2) here's a related weirdo timestamp I saw analyzing some operational traffic today: `99990913024805Z`, i.e., the same except rather than starting with `2037` it starts with `9999`!
