### ISSUE TITLE
[Type] ftp_port is the only case in zeek -NN output, of a type not qualified in a namespace

### ISSUE THREAD

**Issue by duffy-ocraven** [zeek/zeek#1132]
```
Zeek::FTP - FTP analyzer (built-in)
    [Analyzer] FTP (ANALYZER_FTP, enabled)
    [Analyzer] FTP_ADAT (enabled)
    [Event] ftp_request
    [Event] ftp_reply
    [Type] ftp_port
    [Function] parse_ftp_port
    [Function] parse_eftp_port
    [Function] parse_ftp_pasv
    [Function] parse_ftp_epsv
    [Function] fmt_ftp_port
```
All others have a qualifying namespace, i.e.
```
    [Type] DCE_RPC::PType
    [Type] DHCP::Options
    [Type] KRB::Ticket_Vector
    [Type] MQTT::PublishMsg
    [Type] NTLM::Version
    [Type] NTP::StandardMessage
    [Type] RADIUS::AttributeList
```

**Comment by jsiwek** [comment]
Is there a reason `ftp_port` in particular is important to move out of the global namespace?  Is there a reason for type-names as opposed to other identifier names are more important to move out of the global namespace?  If not, there's actually quite a lot in the global namespace that likely fails whatever condition/expectation you have.

If the goal is to prevent naming collisions, I further don't see how us arbitrarily claiming ownership of top-level namespaces like `FTP`, `DHCP`, `KRB`, etc. solves that problem either.  Seems to warrant more extensive planning of naming conventions to use organization names for top-level namespaces (e.g. we claim `Zeek::`) or else extending the language with more useful module/namespacing mechanisms such as letting importers/consumers have final control of remapping names to whatever they choose.

**Comment by duffy-corelight** [comment]
jsiwek above, well laid out the two directions we could go. I am glad that it was something as specific as ftp_port that is our initial stalking horse, since that is much less baffling about "where is this coming from" than if it had been something like PType. That we have exactly one exception--right now--I think makes this a good moment to seize the warrant for more extensive planning of naming conventions. We should decide one-way or the other, and document which way we decided, and why.

**Comment by ckreibich** [comment]
I'm with Jon regarding the lack of impact if we fix this for `ftp_port`. It also strikes me as dangerous to change namespace memberships in the distribution since we don't know what else might currently be using those names.

I could see us do two things here: (1) put this on the pile for if/when we reorganize internals more broadly (given that there are currently so few rules re. what/how plugins access internals, I feel that time will likely come at some point); (2) ensure that our plugin templating nudges folks toward automatically using namespaces. The template (in zeek-aux) already does a great job in that regard. A minor improvement might be to populate the (currently empty) BiF template with a module statement for the given namespace. But, also to Jon's point, that just establishes namespaces. It does nothing to avoid clashes among the same namespaces.

If people are supportive of the template improvement, I'm happy to put that together Apart from that, I'd close this ticket.

**Comment by duffy-corelight** [comment]
I first raised this because it struck me as odd that there was nearly universal alignment in putting plugin declared Types in a namespace (`ftp_port` is the only exception so far),  no case where any plugin has declared a Constant outside of a namespace, and there is only one case where --the opposite-- a plugin declared a Function in a namespace: 
`[Function] FileExtract::__set_limit.`

That seemed to show a widespread consensus of what goes in and what does not go in a namespace, even if not mandatory. It seemed that authors of the few exceptions perhaps did so only because they hadn't noticed the convention that every other author had adopted. This report, if it leads to concurrence that there is a consensus around that style, and a little nudge via PR to those specific packages, would easily fix the exceptions. Then documentation and/or template guidance regarding an example of the expected style, should be enough to keep things aligned in the future.

**Comment by rsmmr** [comment]
I'll go ahead and close this as there's no specific action item, and we're working on better templating already.
