### ISSUE TITLE
Packet analysis: Find way to pass data from one analyzer to another

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#1185]
This came up during the original packet analysis PR and during the IP work, but we couldn't decide on a good way to do it. Right now there are some places where it's necessary to pass data from one analyzer to the next, but the current packet analysis architecture doesn't provide any way of doing that.

Some ideas we've discussed:
- A key-value store in the packet object, since the packet is passed through the entire chain. The store would be a `std::map<std::string, std::any>`, allowing you to store any type in the value part. This is probably the most flexible option. There are concerns of whether the lookups in each analyzer would be a performance problem.
- Passing a void pointer to a custom struct down through the analyzer chain. This would probably be the fastest option but requires a well-defined interface for each analyzer to know what needs to be passed.

**Comment by timwoj** [comment]
One issue here is extensibility with 3rd party plugins. Say I add a new plugin that gets called by the IP packet analyzer that needs to receive some data. How do I tell the IP analyzer that I need that data when it calls the new analyzer?

**Comment by rsmmr** [comment]
This sounds like something we cannot solve fully generically, too many unknowns. Maybe an analyzer could make some global options available that other plugins would set if they need something. E.g., "IP::provide_Foo", "IP::provide_Bar"), and then the analyzer would generially make that information available (to all successors I would think). That means the 1st analyzer needs to antipciate what kind of options might be needed, and the 2nd analyzer needs to know what the 1st has to offer.

**Comment by J-Gras** [comment]
Some thoughts:
* Things will likely become tricky when an analyzer is called multiple times (e.g., VLAN analyzer and the inner tag).
* If a storing the values (or pointers to the values) in a map is too expensive for every packet, one might "ask" an analyzer to provide the value if required (e.g., MACs, VLAN tags and the like are currently just used to build the initial conn val if I am not mistaken). One could provide something like `pkt->GetValue(analyzer_identifier, key)`. In that case `Packet` would need to keep track of which analyzers have been applied and each analyzer would also need to provide a generic `GetValue()`-like method to retrieve the value. Then, the method would only be called for the packet that triggers the creation of a new session in the session analyzer. I think this approach only makes sense if we are about to store two or more values per analyzer otherwise.
* What kind of values do we expect to be passed around? Depending on their length and whether obtaining them involves computation, it might be sufficient to pass around pointers.

**Comment by rsmmr** [comment]
Can we compile a list of cases that we know about where analyzers need this? Would be good to understand better how generic this need to be.

**Comment by timwoj** [comment]
The current list of use cases and what data needs passing:
- VXLAN to packet analysis: encapsulation
- IP to GRE: encapsulation, IP header, protocol
- GRE to IPTunnel: encapsulation, IP header, protocol, tunnel type, gre version, gre link type
- IPTunnel to IP: encapsulation

@rsmmr and I talked about this one for a bit this morning. The easiest way forward right now (for the IP analyzer work) is to just add the fields directly into the packet object. This avoids the slow downs of the map implementation and the annoying typecast and extra passing of data of the void* option. Once that work has landed, and if we find other places we may need something like this, we can revisit it.

I think including the IP header in the packet data once it's being parsed by the IP analyzer may simplify some other parts of the code (such as `Packet::ToRawPktHdrVal`). Also, once a packet is known to be encapsulated or contain an encapsulation, it makes some sense to store that information with the packet directly.

**Comment by rsmmr** [comment]
Not sure of this might be mood at this point due to other changes, but setting milestone to 4.0 so that we can review.

**Comment by timwoj** [comment]
I think we could close this one and reopen it if it comes up again.
