### ISSUE TITLE
Script optimization through compilation

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#1203]
Creating a ticket to track discussion of [Vern's branch](https://github.com/zeek/zeek/tree/topic/vern/script-opt) adding a script compiler to speed up execution. The goal is to merge this in as an experimental feature, ideally with 4.0 if timing works out.

Some initial thoughts & discussion on how to approach the merge (with a focus on the integration into the current code base) are in this [Google doc](https://docs.google.com/document/d/1EhgR80BkWgIeHpgxWiXegQfcOT6zfQagpvc8LDjFigU).

**Comment by jsiwek** [comment]
After reviewing only the READMEs, it sounds like it's shaping up great and had the following thoughts for what may warrant fleshing out even before an experimental phase.  Some are duplicate/similar to Robin's Google Doc.  Expect I can find answers to questions once I review/investigate further, but maybe @vpax can easily answer some and/or extend the READMEs to cover.

## Testing / CI

- Thinking a requirement before any merge is to have full test suite passing
  in optimized-mode along with CI configured to now run against both modes.

- Hope there can be tests to verify correctness of various optimizations.
  Thinking `btest` along with dumping out the reduced AST or ZAM
  representations/descriptions associated with an optimized-script may be a
  natural approach.  More coverage before even an experimental release would
  be nice.

## Known Deficiencies

- Race condition on writing same ZAM file from many Zeek files seems worth
  fixing before any merge (very likely people will encounter).

- Wonder what exactly goes wrong with the `when` expressions and
  concurrent/recursive `for` loop execution.  I can see those blocking even an
  experimental release if the user only will see surprising behavior without
  any warning when accidentally wandering into those situations.

## Known Incompatibilities

- Thinking these are all acceptable for experimental phase.

- Long-term, I wonder how burdensome it is to have inconsistencies between
  the two modes.  Any ideas/plans to reduce differences ?  Anything in
  interpreted-mode to deprecate and align to behave the same compiled-mode ?
  Or the other way: anything in compiled-mode that can be made to conform to
  interpreted-mode behavior with some effort ?

## ZAM Files

- Any concern for (hash) collisions ?

  - If so, maybe ZAM file format contains list of all script file dependencies
    with their modification-times and compare against that list.  Also
    dependence on `zeek` binary would be implied.

  - What about the (unlikely, but still valid) case where there's two
    functions / handlers on the same line ?  Do those currently map to the
    same ZAM file ?  Add a starting-column-number in file name to resolve ?

## "Usage Error" Analysis

- In what cases may `&is_set` be truly needed ?  Seems like a good way
  for human error/mistake to sneak in -- either on first setting the
  attribute or during future code maintenance/transformation.  This
  seems important/mandatory for users to get right and for the optimizer
  to be certain about as otherwise the generated code is incorrect ?

- Should the warnings be on by default and require user to opt-out ?
  An "uninitialized usage" always seems worth knowing as it's a bug.  The
  "unused assignment" also always seems helpful and could even help catch dumb
  mistakes (e.g. copy-paste error) that turn out to be a real bug in
  surrounding logic upon reviewing and not only related to optimization.

## Internals / Misc.

- What's the reason for not currently handling/combining `event` and `hook`
  bodies during inlining step ?

**Comment by vpax** [comment]
How do we migrate/link this to Discussions?

**Comment by vpax** [comment]
Oh, and: a great set of points, thanks!
