### ISSUE TITLE
ICMP Neighbor Discovery: length overflow

### ISSUE THREAD

**Issue by grigorescu** [zeek/zeek#1225]
Per RFC 8106:

>  Length      8-bit unsigned integer.  The length of the option
>                (including the Type and Length fields) is in units of
>                8 octets.

We define length to be an  8-bit unsigned integer. Then we calculate the total length (accounting for the 8-octet unit and type and length fields), and store that back into the 8-bit uint:

https://github.com/zeek/zeek/blob/a87281a1d9e92de8475d83a97fab4a0432963c98/src/analyzer/protocol/icmp/ICMP.cc#L780

This overflows and wraps for length > 32.

**Comment by grigorescu** [comment]
I made the obvious fix and  changed the length to a `uint16` in b5d11d1ace6f6234ebc3ae74b4e324bd701d00dd on topic/vlad/gh-1225.

However I'd like a second opinion on the length handling in general in that function. It seems like this in particular:

https://github.com/zeek/zeek/blob/b5d11d1ace6f6234ebc3ae74b4e324bd701d00dd/src/analyzer/protocol/icmp/ICMP.cc#L870

should ensure that `caplen >= length` first.

**Comment by jsiwek** [comment]
Thanks, Vlad.

> I made the obvious fix and changed the length to a `uint16` in [b5d11d1](https://github.com/zeek/zeek/commit/b5d11d1ace6f6234ebc3ae74b4e324bd701d00dd) on topic/vlad/[gh-1225](https://github.com/zeek/zeek/issues/1225).

Using `uint16_t` for storage to avoid the later overflow is what I'd do also, but it shouldn't be casting the packet data to `uint16_t*` in order to extract it.  That is, the length field is defined as 8-bits so still need to extract it as such, but we should choose to store into something that won't later overflow.

> However I'd like a second opinion on the length handling in general in that function. It seems like this in particular:
> 
> https://github.com/zeek/zeek/blob/b5d11d1ace6f6234ebc3ae74b4e324bd701d00dd/src/analyzer/protocol/icmp/ICMP.cc#L870
> 
> should ensure that `caplen >= length` first.

That seems fine to me as it stands -- if the option reports a length greater than what's available in the captured packet data, `caplen`, we still do need to reduce `caplen` by some amount to indicate "we've consumed the data associated with that option, or at least as much of it as we could".  So whether we reduce it to `0` or let it go negative means the same thing to any subsequent parsing logic: "there's no data left".  If later on something goes to parse out packet data without checking that `caplen` is greater than the amount of bytes they need for that parsing, the bug is located wherever that hypothetical code is.

**Comment by grigorescu** [comment]
Thanks. Fixed the extraction issue, I think this is ready.
