### ISSUE TITLE
CAF/zeek cmake files in divergent places in directory hierarchy

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#1326]
With merging https://github.com/zeek/zeek/pull/1319, there are now a few more cmake files after installing our distribution that are installed by CAF.

These are installed in lib/cmake/caf. However, the cmake files of zeek are installed in share/zeek/cmake. It seems like it would be nice to have one standardized path where cmake files end up.

**Comment by 0xxon** [comment]
I think this would be neat to have fixed before 4.0 - especially since we just introduced it/ I am going to add it to the milestone for now.

**Comment by Neverlord** [comment]
These files are CMake packaging files. Moving them to `share/zeek/cmake` means breaking `find_package`. So either we don't install CAF files at all on the system or we should leave them at this location.

**Comment by 0xxon** [comment]
Ok. Does that mean that, theoretically, lib/cmake/zeek would actually be a more standard location for our cmake files?

**Comment by Neverlord** [comment]
> Ok. Does that mean that, theoretically, lib/cmake/zeek would actually be a more standard location for our cmake files?

As with most things CMake: ... maybe? 🤷🏻‍♂️

The search procedure goes looking for `<name>` (here Zeek or CAF) under `share/cmake/<name>` as well as under `lib/cmake/<name>` (plus a bunch of other paths): https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure.

So either path works for CMake, but moving the CAF package files to a directory named `zeek` would break `find_package`. I did some googling before modernizing the CMake scaffold for CAF and `lib/cmake/<name>` seemed most common. But since CMake scans both paths, `lib` and `share` will both work.

**Comment by 0xxon** [comment]
yeah, I actually assumed that the natural path would be /share/caf/cmake. But it sounds like that's also not really the answer to this...

**Comment by Neverlord** [comment]
Ultimately, package maintainers may override where the files go via `CMAKE_INSTALL_PREFIX`. But if you can find a somewhat official best practice guide on what the best / most recommended default setting is: I 'm all ears. 😉

**Comment by 0xxon** [comment]
Ok :)

I am still a tad unhappy about the fact that we not have cmake files in two completely unrelated parts of the directory hierarchy. But - it seems like this is nothing that we should just fix in the last minute, so it might be best to just leave it like this for this release, and then, eventually perhaps migrate the zeek cmake files.

**Comment by jsiwek** [comment]
If there's not a rule against or problems caused by having CMake scripts at differing locations (or particularly within `lib/`), then this may be a non-issue.  The scripts in `share/zeek/cmake` have a different idea about what they want to be used for than the scripts in `lib/cmake/CAF` .

`share/zeek/cmake`: have a particular use (so Zeek plugins can re-use some of their logic) and not meant to be generally visible or used for the purposes of the new-ish `find_package(<name> CONFIG)`.  If there's little benefit to rewriting any of those to support the package `CONFIG` search process, and Zeek plugins are successful and explicit about how they find and use scripts at that location, and there's no FHS rule against us putting CMake scripts at that location, then that location is "correct" enough.

`lib/cmake/CAF`: if CAF wants to support use of the new-ish package config search process, like if someone wants to install Zeek+CAF into `/usr/local/` and then still have other projects pick up that CAF install via `find_package(CAF CONFIG)`, and if `lib/cmake/<name>` is a common convention for that, and if it's not violating FHS practices, then that's also a "correct" location for what it trying to accomplish.

**Comment by 0xxon** [comment]
Fair enough. I still think it feels slightly confusing to have cmake files at different spots in the hierarchy - but this doesn't really seem to be worth the effort to change.

Closing, thanks a lot.
