### ISSUE TITLE
Install Zeek btest canonizers

### ISSUE THREAD

**Issue by sethhall** [zeek/zeek#1431]
Right now it's annoying to need to include all of the little btest canonifier scripts with an external Zeek script package if you want to use those that are shipped with Zeek.

Seems like we could just install those scripts somewhere with a Zeek install and then have a convention for referencing them in a btest.cfg file.

**Comment by ckreibich** [comment]
Yeah, I like this one. I believe we touched this in the past when discussing the implications of moving more policy folder content to packages. We could add `random.seed` as well, since it gets copied around a lot.

I believe we had converged toward also installing the test pcaps, though I can't locate that discussion atm. It'd add 26MB to the install. Perhaps with a configure options to skip installing these?

**Comment by jsiwek** [comment]
General question: the installation of these items implies they become part of the "stable Zeek platform" in which there's a commitment to not do breaking changes/removals unless a deprecation notice has been served for duration of a full major-release ?

If not, why not ?  If we're encouraging external plugins to depend on them, then haphazard changes/breakages are just as annoying as current state of having to copy things into the plugin?

If so, these are kind of an awkward thing to remember during the maintenance process: "don't change/remove them, might break a plugin's test-suite".  It's maybe rare that those situations happen, but that may not make it better, it may make it worse in the sense of whether anyone is likely to remember to be careful about those types of changes.

I wonder about benefits/convenience tradeoffs and whether to actually try minimizing interdependencies rather than expand them:

* random.seed: just have `init-plugin` copy or create an arbitrary one ?  Or is there reason to depend on exact seed used by Zeek's tests ?
* canonifiers: just have `init-plugin` copy the whole lot of them ?
* pcaps: not sure how often they'll get re-used in the first place and I don't have specific, alternate ideas, but could possibly put them into a package of their own on which others can depend or a different method of distributing/sharing entirely ?

**Comment by ckreibich** [comment]
Good points — reminds me of concerns you also brought up when we added `zkg`.

I think the driver here has been to avoid pushing content into packages that's prone to becoming stale/unused. That's not an answer to your arguments, but I think it's the tradeoff. I could see these things become part of the distribution, and the stability concerns would imo be small: breaking changes to the files we're discussing are also painful for Zeek's testsuite, hence rare. Curious to hear what others think.

The pcap package idea is fun. We might need more infrastructure to make this fully workable (where do packages install data, do you need to have such packages installed in production as opposed to development), but I could see these end up being useful in many contexts in the future.

(Btw, this would affect both pure plugins and Zeek packages, with or without plugins.)

**Comment by 0xxon** [comment]
> I think the driver here has been to avoid pushing content into packages that's prone to becoming stale/unused. That's not an answer to your arguments, but I think it's the tradeoff. I could see these things become part of the distribution, and the stability concerns would imo be small: breaking changes to the files we're discussing are also painful for Zeek's testsuite, hence rare. Curious to hear what others think.

I agree with this. Changes to the pcap files that, assuming we distributed them, would have any impact on external packages are exceedingly rare. They are so rare already - without us having any policy about this - that I think we don't have to worry about this.

I just went through the git history till 2017. I was able to find a few changes - all of them were fixes to the pcap files to deal with zeek errors (broken files that worked in the past, or pcapng to pcap changes) which should not trigger any test suite changes no matter what you do. They are also rare.

There also were a few files that were renamed - but that is quite rare (last time in 2019) - and to a certain degree also avoidable. This was partially done because some traces switched from being compressed to uncompressed (in 2018).

**Comment by rsmmr** [comment]
Let me throw out an alternative idea: we could move these scripts & pcaps into a separate git submodule. We wouldn't install that, but plugins could pull it in as a submodule our their end as well. Then we could update the content without breaking those plugins, because as long as they don't update the version they are pointing to, they won't see any changes.

On the pcaps, I go back and fort on whether it's useful to distribute/install them. I can see it in some cases, but most plugins will not need most of the traces; and it also seems easy enough for a plugin to put in a couple of traces of their own.

**Comment by 0xxon** [comment]
> On the pcaps, I go back and fort on whether it's useful to distribute/install them. I can see it in some cases, but most plugins will not need most of the traces; and it also seems easy enough for a plugin to put in a couple of traces of their own.

I agree that is is not super hard - it is just something that I encountered in, I think, every plugin that I have written so far. The common ones I copied in the end are a single connection trace, and the wikipedia one. Other things that get more deeply into protocols might be less interesting.

> Let me throw out an alternative idea: we could move these scripts & pcaps into a separate git submodule. We wouldn't install that, but plugins could pull it in as a submodule our their end as well. Then we could update the content without breaking those plugins, because as long as they don't update the version they are pointing to, they won't see any changes.

That sounds fine to me.

**Comment by ckreibich** [comment]
Yeah that's tempting. My one concern is that I'd expect some canonifiers to be common — removing timestamps and connection IDs should be required for pretty much any log tests  — and I'm not sure it's great to have submodules enter the workflow of many packages. It will technically work fine, since zkg has supported submodules for a while now ... but I think submodule management confuses a lot of people.

I'm starting to come around to Jon's suggestion of moving this into templating: pcaps and canonifiers could become respective features of the new zkg templates, meaning they'd each be optional and could come with some flexibility to let you include what you need. (It's this flexibility that I hadn't previously considered — I just didn't like the idea of the canonifiers or even pcaps sitting in the resulting package unused.) This would be content for which modernization to newer template versions would work well (just put in place newer versions of those scripts/files when updating the content).
