### ISSUE TITLE
Scope qualifiers fail for types with the same base name

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#1443]
The following code snippet:
```
type r: record { a: count; };

module test;

type r: record { b: string; };

event zeek_init()
        {
        local x: GLOBAL::r;
        x$a = 5;
        }
```
produces `line 14: no such field in record (test2::x$a)`.  The same thing happens if instead of global scope, the first `r` has scope in another module.

The core problem appears to be that the logic for the parser's `global_or_event_id` production reuses an existing global lookup without considering its associated module scoping.

**Comment by timwoj** [comment]
> The core problem appears to be that the logic for the parser's global_or_event_id production reuses an existing global lookup without considering its associated module scoping.

Yep, pretty much. We call `lookup_ID` but pass it a `false` for `no_global` and a `false` for `same_module_only`, which lets it return a global-scoped version of the ID. I haven't completely sorted out the parsing flow yet, but `same_module_only` is set to false because `defining_global_ID` is `0` in the parser when we create the IDs (even when we make the global one, which doesn't make a whole lot of sense to me). Shouldn't `same_module_only` always just default to `true`, at least for types?

**Comment by timwoj** [comment]
Actually, super easy fix. Shouldn't this:

https://github.com/zeek/zeek/blob/cb3abccfb19aee5ea54cbd5228d23c71202fe22e/src/parse.y#L1326

be `TOK_TYPE def_global_id` like the `TOK_GLOBAL`, `TOK_OPTION`, and `TOK_CONST` blocks before it?
