### ISSUE TITLE
Embed plugins statically into Zeek

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#1480]
The goal is to extend the plugin infrastructure to pull plugins directly into the Zeek build, so that they become available built-in. This tracks the work in #1416.

**Comment by ckreibich** [comment]
I believe this is currently only covered via the NEWS bit mentioning `--include-plugins`, right? It appears in the docs [here](https://docs.zeek.org/en/master/scripts/builtin-plugins/__load__.zeek.html), but that's just a skeleton. I'm going to tag this as needing documentation, probably somewhere in the [plugins](https://docs.zeek.org/en/master/devel/plugins.html) section ... let me know if you think otherwise.
