### ISSUE TITLE
Explain orig/resp (versus src/dst) terms better in documentation

### ISSUE THREAD

**Issue by StaticAJ** [zeek/zeek#1485]
Versions of Zeek encountered issues on: 3.3.0-dev.194, 4.1.0-dev,314

When trying to create logs from a pcap, I have experienced the protocol analyzers (including core analyzers such as DNP3) using the connection object associated with each packet across that TCP stream, without the source and destination addresses and ports being flipped according to the packet's is_orig value. The result is that the logs will display the source and destination the wrong way around.

To validate this lack of flipping between source and destination, I have compared zeek's output to what Wireshark reports. Additionally, I have looked within zeek's documentation and other online resources, but as I'm also new to Zeek it is not clear as to the cause of this, even when placing print statements within core Zeek source files. Any explanation of the cause, or suggestions for solving this would be greatly appreciated.

**Comment by jsiwek** [comment]
It may help if you give a specific example/pcap that shows what you're observing, but a guess I have is just a confusion about the meaning of some terms: originator/responder (orig/resp) versus source/destination (src/dst).  While src/dst describe a packet-level concept (who sent a packet / who received a packet) and values frequently flip back and forth, orig/resp describe a connection-level concept (who originally initiated a conversation) and values are generally persistent for the lifetime of the connection.

So if you're looking at an event with an `is_orig` value, it's generally telling you whether that event has a causal relation to the `orig` or the `resp` host, whose values you can think of as fixed for the lifetime of a connection -- there's no automatic flipping of them based on `is_orig` because then those values would mean the opposite of what they intend.

Does that help clarify anything?

**Comment by StaticAJ** [comment]
Thank you, I think the terminology is what is confusing me. But is there anywhere in the Zeek documentation that explains more of these terms, as it seems that the code itself is a bit ambigous  - sometimes "originator" is referred to as "source".

**Comment by jsiwek** [comment]
I don't know of a place where terms are explicitly described anywhere in the docs, so I'll turn this issue into a reminder to add that (e.g. maybe here makes sense: https://docs.zeek.org/en/master/logs/conn.html).

For any specific docs that you find ambiguous, give links/quotes and someone can review and revise.

**Comment by ckreibich** [comment]
Yes, good call! This also came up during the docs push as something we should cover, but in the end didn't go in prior to roll-out. I gave this a go, let me know your thoughts.
