### ISSUE TITLE
some PCAPs don't  generate ssl.log due to "TCP Spurious Retransmission"

### ISSUE THREAD

**Issue by Nobush1** [zeek/zeek#1564]
I use below  command line to parse the pcap:
zeek local -C -r 192.168.236.22.pcap FilteredTraceDetection::enable=F tcp_attempt_delay=100sec tcp_close_delay=12min

Relevant pcap is as follows:
[192.168.236.22.zip](https://github.com/zeek/zeek/files/6536180/192.168.236.22.zip)

**Comment by 0xxon** [comment]
Hi,

From a first glance, the pcap that you captured has signifcant packet re-ordering issues. The pcap contains the packets in an order that is not the same order in which they crossed the network. This means, that from the perspective of the pcap, the traffic is quite broken - there are acks for segments that we have not seen, and the segments then later arrive after they have been ack-ed.

I am not sure how you captured this traffic - and how this happened. However, it looks like the capturing of one direction of the traffic is delayed in comparison to the other direction. 

This is not really something that is easily fixable by a system like Zeek. Zeek assumes that the traffic that it parses is in the same order as it happened. So, e.g., data has to arrive before the acks of the other side that acknowledge the data.

For Zeek, it looks like is it missing packets in the connection. At that point, the normal analysis stops for a lot of protocols - like SSL; our current parsers do not support parsing connections that are missing packets. The data then arrives later - which raises the suprious retransmission warning - since, for Zeek, it looks like the data that arrives already should have been seen (it already was ack-ed).

In any case - the short version is that this is ok behavior on our side - Zeek does not support traffic that is not correctly ordered. The best solution to this is to fix your capture setup - so that the traffic is captured in the same oder in which it crosses the wire.

If you have more questions about this, you probably should reach out on our other community channels like slack or our email lists, which are read by more people - which often have more experiences with capturing setups.

Johanna
