### ISSUE TITLE
Hook for packets not processed

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#1620]
### Discussed in https://github.com/zeek/zeek/discussions/1595

<div type='discussions-op-text'>

<sup>Originally posted by **rsmmr** June 11, 2021</sup>
In a number of different contexts, a desire has come up to get access to packets that Zeek doesn't process otherwise. I think we generally could pretty easily provide a plugin hook for purpose that receives the current `Packet` structure, filled in to the degree that the packet made it through the pipeline. 

The main questions is what exactly it means that Zeek "did not process" a packet. It probably should not be simply "no analyzer looked at it" because we might hit dead ends at different points in the stack (say, an usual protocol on top of IP that's not having a further analyzer to continue with).  Instead we need some user-centric notion of "this traffic is being taken care of".

I'm wondering if the following would work:

1. We track a boolean `processed` along with each `Packet`, initialized to false. 
2. As the packet makes it through through our pipeline, any packet analyzer can set it that flag to true to indicate "I'm taking care of this", meaning that at the very least there will be something in the logs about the activity. For example, TCP/IP analysis would set this as soon as we get to the point where the traffic will for sure make it into `conn.log`.
3. If at the end of a packet's life the flag is still false, we hand it over to a new plugin hook `unprocessed_packet`
4. We probably also want to record some basic stats on how many of these we see.

Does this make sense?</div>

**Comment by rsmmr** [comment]
Taking from Discussions as a feature for 4.2.

**Comment by J-Gras** [comment]
So the goal is to make packets that are not processed by Zeek available to a C++-level hook, right?
Let me quickly recap my understanding of the problem:
1. This is primarily about the packet analyzer level. Once we reassemble packets to streams, a failure to parse data is handled differently.
2. This should be able to cover packets of unknown protocols (which are already logged) as well as packets that existing packet analyzers fail to analyze.
3. Users should be able to tune/filter what is classified as not processed (e.g., users might want to ignore certain unprocessed protocols on top of IP).

Actually I find it a bit hard to tell when a packet is processed, i.e. when to set the suggested flag to true. That feels like a packet analyzer predicts the future: No matter what payload I have extracted, Zeek will now continue to process it.

What about turning this around: Just tell that we failed to analyze a packet. Either packet analysis fails to determine a next analyzer or some packet analyzer fails to process the contents of a packet (e.g., at some point the TCP analyzer discards some packet that couldn't be reassembled). AnalyzePacket() already uses a return value to indicate success. If I am not mistaken, this is currently not used. Finally, to allow a user to ignore certain protocols, it should be possible to add a "black hole" analyzer that does nothing but indicate that its input can be considered as processed. This way users can use the existing configuration mechanism to tune their setup as needed.

**Comment by timwoj** [comment]
@rsmmr and I talked about this one for a bit this morning. The current plan looks something like this:

- Add a flag in the Packet class that defaults to false, meaning a packet is always considered unprocessed until some analyzer says it is.
- Set the flag to true in various places, but primarily the first time the packet gets logged. This could mean when a connection is created, when ARP is logged, etc.
- Add some statistics around packets not being processed. This would preferably include a running average over some time span, so you could say "this percentage of packets over the last X minutes haven't been processed". A total count could also be added to the received/dropped statistics we already provide.

The only thing I think I'd change about the above is also considering any packet that the packet analysis framework returned `true` for should be considered processed, since that indicates it made it all the way through processing without running into a failure anywhere.

**Comment by timwoj** [comment]
What information is useful to be passed with the invocation of the hook?

**Comment by rsmmr** [comment]
> The only thing I think I'd change about the above is also considering any packet that the packet analysis framework returned `true` for should be considered processed

Yeah, maybe, let's take a look once the infrastructure is in place, we can fine-tune where exactly we set the flag then.

**Comment by rsmmr** [comment]
> What information is useful to be passed with the invocation of the hook?

Good question. Probably just the `Packet`, that has plenty meta data where available. Can't think of anything else right now.

Btw, just looking at `Packet`, I see `dump_packet`: We could add a mode where we record any packets that haven't been processed. Could be useful for debugging scripts/analyzers, and also Zeek itself.

**Comment by timwoj** [comment]
> Yeah, maybe, let's take a look once the infrastructure is in place, we can fine-tune where exactly we set the flag then.

The reason I mentioned that is for things like ARP. We process it and send events, but we never log ARP anywhere. Packet analysis returns a true since it got processed by something, but didn't logged. For most of the rest of the packets I see on my network, they're covered by setting the flag to true once we successfully create/lookup a `Conn` for them in `IPBasedAnalyzer`.
