### ISSUE TITLE
Prevent duplicate definition in record

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#1628]
I was surprised to just find out that it is possible to have two members with the same name in a record as long as they have differing types.

The following code:

```
type test: record {
	a: count;
	a: string &optional;
};

event zeek_init()
	{
	local a = test($a=5);
	print a;
	}
```

Yields the output:

```
[a=5, a=<uninitialized>]
```

We should probably prevent this :)

**Comment by JustinAzoff** [comment]
Looks like it's also related to how the attribute finding finds the right attribute iteratively.  Only the first one is really usable.  Change the order of the two attributes and you get

```
error in ././foo.zeek, line 8 and count: type clash for field "a" ((coerce [$a=5] to test) and count)
```

**Comment by sneh19337** [comment]
I would try to remove all the duplicates and send a PR for the same.

**Comment by sneh19337** [comment]
I would try to remove all the duplicates and send a PR for the same.

**Comment by sneh19337** [comment]
I will try to remove all the duplicates and send a PR for the same.

**Comment by 0xxon** [comment]
Sure - just go right ahead.

**Comment by abhishektiwari47** [comment]
hey i want to work on it.

**Comment by timwoj** [comment]
I found an interesting bug while investigating this one. The `scripts.base.frameworks.input.setspecialcases` btest actually has a case of this, where the `s` field of the `Val` record is duplicated, even though the header in the input file has fields named `s` and `ss`. That's not the bug though. If you fix that bug, the input parser has problems with line 6 in the file it's supposed to be reading:

```
warning: ../input.log/Input::READER_ASCII: ../input.log, line 8: Not enough fields in line '6		' of ../input.log. Found 1 fields, want positions 2 and -1
```

Line 6 is an identifier followed by two tab characters and nothing else. We're expecting the Ascii parser to break that up into three fields. The problem is that the call to `getline` exits early on the last field because there's no string to parse after the last tab character. This block https://github.com/zeek/zeek/blob/master/src/input/readers/ascii/Ascii.cc#L372-L380 is returning that there's only two fields, not three. Here's a minimized version of the same code that exhibits the same problem: https://godbolt.org/z/dMEKPnn3v.

The easy fix for the test is to insert a space character at the end of that line, but it results in different output since the space gets inserted into the `ss` field.

**Comment by timwoj** [comment]
> Here's a minimized version of the same code that exhibits the same problem: https://godbolt.org/z/dMEKPnn3v.

I pulled the `split` method out of zeek-agent-v2 to give it a shot, and it seems to work correctly: https://godbolt.org/z/Wv83dzosf
