### ISSUE TITLE
Replace nb_dns with c-ares

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#1635]
This was brought up as a part of #951 but that effort seems to have gone stale. We should investigate replacing our own internal implementation of DNS with something like https://github.com/c-ares/c-ares, which is written by the same guys that do `curl`. It would also remove a build dependency on `bind`.

**Comment by ckreibich** [comment]
A helpful side-effect of this wil be that the resolver then also honors `/etc/hosts`, i.e., not just rely on network I/O with the resolver.

**Comment by 0xxon** [comment]
And it will work on systems where there is no IPv4 resolver ;) (I think we just can't resolve stuff in these cases at the moment)

**Comment by timwoj** [comment]
I wonder if we could also import their fuzzer corpus for use against oss-fuzz: https://github.com/c-ares/c-ares/tree/main/test/fuzzinput

**Comment by timwoj** [comment]
> We lose the TTL information from address lookups because c-ares doesn’t report it in the hostent structure returned to the callback for ares_gethostbyaddr. 

Digging into this a bit more, it appears we use the TTL data for expiration from our local cache in `DNS_Mapping::Expired`. Setting it to zero in the case of PTR or TXT requests would basically mean the data is always expired as soon as it's put in the cache. The TTL data is definitely there in the responses from the DNS server for those requests, it's just that c-ares doesn't pass them along to us. I wonder if it would be wildly difficult to add and open a PR on their side for.

**Comment by timwoj** [comment]
> There's also an option called lookups in the channel configuration that we can set to `fb` that causes it to do both lookups for both `ares_getaddrinfo` and `ares_gethostbyaddr`.

Following up on this, adding this snippet when initializing the channel does indeed configure c-ares to do hosts lookups, and returns proper addresses for calls to `ares_getaddrinfo`, `ares_gethostbyaddr`, and `ares_gethostbyname`. It does not work for calls to `ares_create_query`/`ares_send`.

```
    options.lookups = "fb";
    optmask |= ARES_OPT_LOOKUPS;
```

**Comment by rsmmr** [comment]
Taking a stab at questions:

> * Is being able to use /etc/hosts something we want?

I'd say no. I think for our use cases, we want to know what DNS really says, independent of any local configuration; because 
the traffic we are looking at has no relationship to the monitoring system. Or, at least, we'd want a way to override `hosts` by saying `give me what DNS really thinks` (which however is probably not worth the effort of adding, compared to just ignoring `hosts` altogether).

> * We lose the TTL information from address lookups because c-ares doesn’t report it in the `hostent` structure returned to the callback for `ares_gethostbyaddr`.

This would be good to retain. For one, because of our caching, as you already say. Second, this could be genuinely useful information for scripts. We don't have bifs right now that expose TTLs, but we could add them; seems like something that could be useful for the malware detection space.

> * The Address and Text cache lookups used to return `<???>` if there was a mapping in the cache but there wasn’t any host or text data associated with the entries. What was this output used for? Do we need to actually return it?

Hmm, good question. I don't fully recall why we do it this way. I'm pretty sure this came about when we added the asynchronous lookup BiFs, along with `when`. But I don't recall why "<???>" instead of empty string. Maybe it was just for visibility, so that when something gets logged, it's clear that there's actually information missing.  Are there other cases where an empty string comes back, and this might be to distinguish from that?

Either way, one question is if want to break semantics there. Wouldn't be surprised at all if people have scripts testing for `<???>`.

(Btw, this reminds me of my favorite feature request for the scripting language: I'd really like to have `optional<T>` and/or `result<T>` types.)

> * The existing code doesn’t handle hostname aliases (retrieved via `ares_getaddrinfo` requests). Would that be a useful feature to add?

I say "yes" here.

> * Similarly to the hostname alias question, should be handle multi-part TXT replies?

I also say "yes" here, but less strongly. :) If it's easy, won't hurt and might be useful for some cases; if more work, fine to wait for a use case.

> * Should request failures output something via reporter? The current code outputs something but it's not terribly useful, at least from the unit testing context:

Agree with the not terribly useful, but problem is we don't have a way to pass/notice errors otherwise. Altough we could a new event for reporting DNS issues? (If we only had a `result<T>` ... :-)

**Comment by timwoj** [comment]
> I'd say no. I think for our use cases, we want to know what DNS really says, independent of any local configuration; because the traffic we are looking at has no relationship to the monitoring system.

Ok, I moved `PTR` requests over to use the same method as `TXT` requests, which let me get rid of a bit of code. I left `A`/`AAAA` requests separate for right now because the `getaddrinfo` will return me both IPv4 and IPv6 results in the same query callback, which I can then merge into a single mapping at one time. I might see if I can figure out a better way to do the merging so I can move those as well.

> This would be good to retain. For one, because of our caching, as you already say.

I dug through the c-ares code and put together a method that basically does what the handling in `getaddrinfo` does, so now I can get TTLs from any response. Right now I'm only using the TTL for the first RR I encounter, just out of simplicity of not having to skip over to find each one.

**Comment by timwoj** [comment]
> The existing code doesn’t handle hostname aliases (retrieved via ares_getaddrinfo requests). Would that be a useful feature to add?

I found a weird bug (or something I think is a bug?) in c-ares related to this one: https://github.com/c-ares/c-ares/issues/452. So that's on hold for now.

**Comment by timwoj** [comment]
> Agree with the not terribly useful, but problem is we don't have a way to pass/notice errors otherwise. Altough we could a new event for reporting DNS issues? (If we only had a result<T> ... :-)

I added the use of a doctest logging macro to Reporter::DoLog. It doesn't fix the semi-uselessness of the location information, but at least now it links the log messages to the unit test that caused them:

```
===============================================================================
../src/DNS_Mgr.cc:1552:
TEST CASE:  dns_mgr default mode

../src/Reporter.cc:682: MESSAGE: error in /mnt/data/tim/zeek/scripts/base/init-bare.zeek, line 1: Failed to parse PTR response: DNS server returned answer with no data

../src/Reporter.cc:682: MESSAGE: warning in /mnt/data/tim/zeek/scripts/base/init-bare.zeek, line 1: can't resolve IP address: 240.0.0.0
```

**Comment by timwoj** [comment]
I just noticed that c-ares also comes with portable versions of `inet_ntop` and `inet_pton`. This means we could potentially replace our `bro_inet_{ntop/pton}` code with those as well.

**Comment by timwoj** [comment]
> I just noticed that c-ares also comes with portable versions of inet_ntop and inet_pton. This means we could potentially replace our bro_inet_{ntop/pton} code with those as well.

After testing this, I'm going to skip making this change. Our versions handle embedded-ipv4 addresses differently their theirs, and changing to their version breaks some tests.

This work is mostly done and ready for PR, but I'm waiting to see if the upstream project will fix that issue with TCP taking a long time to shut down. It doesn't seem to affect anything in the runtime and the benchmark numbers look find, but there's the potential that it could cause btests to take a really long time to run and that's detrimental to the development cycles.
