### ISSUE TITLE
Some btest artifacts are built/installed even when --disable-btest and --disable-btest-pcaps is passed to configure

### ISSUE THREAD

**Issue by redbaron4** [zeek/zeek#1725]
Hi,

I was trying to build an RPM for Zeek-4.1.0 but it errored out after finding extra files.

In my spec file the configure line looks like

```
./configure --prefix=%{_prefix} --binary-package --enable-static-broker --disable-broker-tests --disable-btest --disable-btest-pcaps --with-python=/usr/bin/python3.6
```

However in 4.1.0 some btest related artifacts are still installed in the build tree. Here's the error output

```
error: Installed (but unpackaged) file(s) found:
   /opt/zeek/share/btest/data/random.seed
   /opt/zeek/share/btest/scripts/diff-canonifier
   /opt/zeek/share/btest/scripts/diff-canonifier-external
   /opt/zeek/share/btest/scripts/diff-remove-abspath
   /opt/zeek/share/btest/scripts/diff-remove-fields
   /opt/zeek/share/btest/scripts/diff-remove-file-ids
   /opt/zeek/share/btest/scripts/diff-remove-fractions
   /opt/zeek/share/btest/scripts/diff-remove-openclose-timestamps
   /opt/zeek/share/btest/scripts/diff-remove-timestamps
   /opt/zeek/share/btest/scripts/diff-remove-uids
   /opt/zeek/share/btest/scripts/diff-remove-x509-key-info
   /opt/zeek/share/btest/scripts/diff-remove-x509-names
   /opt/zeek/share/btest/scripts/diff-sort
   /opt/zeek/share/btest/scripts/diff-sort-conn-service
   /opt/zeek/share/btest/scripts/diff-sort-set-elements
```

Looking at the spec file in srpm on zeek site I can see these should be a part of `zeek-btest` and `zeek-btest-data` RPMs. Since I don't want any part of btest, should I add these to `zeek-core` for the moment or build semi complete `zeek-btest` and `zeek-btest-data` RPMs?

**Comment by ckreibich** [comment]
Thanks Dheeraj. This was actually intentional because `--disable-btest` so far has referred to the installation of the `btest` tool, not Zeek's `btest`-related tooling. The assumption was that if you don't install `btest` via Zeek, you omit it because you favor a different version from PyPI. The utility of the btest tooling is that it enables future tests (e.g. those shipped with Zeek packages, which are likely to use `btest`) to rely on it, just as you're relying e.g. on C++ headers to build plugins. The separate switch for pcaps was because some people might object to the pcaps due to their size.

So there are three things here: (1) install `btest`, (2) install Zeek's `btest`-related tooling, (3) install Zeek's test pcaps. Perhaps the best way forward here is to allow all three to be distinguished via `configure`, i.e. to add a `--disable-btest-tooling` to address the second part. (Ironically, that flag actually used to exist!)

Regarding the RPMs, I think right now the best way forward would be to include the best tooling as part of `zeek-core`, since the idea was that it's just always there.  `btest` should ideally be its own package, fully independent of Zeek. I'm not very familiar with packaging details, though.

**Comment by redbaron4** [comment]
@ckreibich Thanks a lot for taking the time to explain this in great detail. I now understand the motivation & reason for the flags.
I think this bug is no longer relevant so will close this & PR.
