### ISSUE TITLE
v6 -> v4 conversion causes `0.0.0.0/0` to be added to `Site::private_address_space`

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#1766]
The IPv4 mapped netblock in IPv6 (`[::ffff:0:0]/96`) [was added](https://github.com/zeek/zeek/blob/0746ef7ecc977a4fad2f0ffa1fe3a9944b94d7f0/scripts/base/utils/site.zeek#L91) to `Site::private_address_space`. Unfortunately, Zeek "helpfully" converts it to the IPv4 CIDR `0.0.0.0/0`, which causes all of IPv4 to be considered private address space. This also appears in the [documentation](https://docs.zeek.org/en/master/scripts/base/utils/site.zeek.html#id-Site::private_address_space) (5th from the bottom).

```
$ zeek --version
zeek version 4.2.0-dev.94
$ zeek -e 'print [::ffff:0:0]/96;'
0.0.0.0/0
```

https://try.zeek.org/#/tryzeek/saved/531078

**Comment by timwoj** [comment]
Added to the lists for the next 4.0 and 4.1 patch releases. The linked commit above is only in master, so it's not a huge rush, but it's something that definitely should be fixed.

**Comment by timwoj** [comment]
I think the problem here is that we consider `::ffff:0:0` to be a v4 mapped address. We store that address in an `IPAddr` and when `AsString()` is called on it to print it out, it checks to see what family it is, returns IPv4, and then returns an IPv4 address of `0.0.0.0`. The length value isn't even considered in any of this.
