### ISSUE TITLE
File analyzer API doesn't have a good way to pass arguments to instantiated analyzers

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#185]
When adding a file analyzer with `add_analyzer`, there's no good way to pass arguments to the new analyzer instance (say, if it were an analyzer to extract certain tags from a data stream, I would to want tell it which tags to extract). There's a record `AnalyzerArgs` but that's kind of an odd thing: right now it has two callbacks for the `DATA_EVENT` analyzer; but it's passed in for analyzers of any kind. One could extend that type with further arguments for other analyzers, but having one type for all analyzers doesn't seem like the right mechanisms.

**Comment by sethhall** [comment]
I've been wondering if Files::add_analyzer should return some sort of handle?  I sort of get the sense that it should.  It would make some stuff significantly easier.

**Comment by sethhall** [comment]
Here's some imaginary code....


```bro
local x: AnalyzerHandle = Files::add_analyzer(f, FILES_EXTRACT);
Files::add_argument(x, "cutoff", "1024");
```

And if `x` was defined as a global, at some point you could do this...

```bro
Files::remove_analyzer(x);
```

I don't know how great this proposal is, but it would make some file handling activities much more convenient.

**Comment by jsiwek** [comment]
Having a separate `Files::add_argument` could be weird in case where an analyzer needs the argument as part of the initialization done during `Files::add_analyzer` ?

But yes, an alternative would likely be using a variadic functions to supply arguments (currently script-layer functions cannot be variadic, but BIFs can).

However, then you are doing type-checking manually in the core for each analyzer instead of relying on the scripting language to type-check things for you.  It's also a bit more manual labor to document such an API and you are relying on the comments to be always reliable in telling you want analyzer tags take what arguments.

**Comment by sethhall** [comment]
Yeah, breaking out argument adding is a dumb suggestion on second thought.  The variadic suggestion is cool, but could be a bit weird from a scripting perspective.  At least with the redef-ed argument list thing we have now we can document the arguments that can be passed to an analyzer.

The other part of this is being able to remove an analyzer by it's handle.  Jon, remember how we couldn't figure out a good way to specify which analyzer to remove for the case where you might have multiple data analyzers attached to a file (as an example).  At the moment we're using the set of arguments given to an analyzer as the way to identify the particular analyzer instance.

**Comment by rsmmr** [comment]
Closing, doesn't seem like a pressing need.
