### ISSUE TITLE
Some input related errors do not include the file/line information

### ISSUE THREAD

**Issue by JustinAzoff** [zeek/zeek#1857]
We currently have a test that shows this issue: btest/scripts/base/frameworks/input/invalidset.zeek

The baseline is this (repeated twice, just showing the first 4)

```
EventErrorEvent, Could not convert line 'name\x09127.0.0.1' of ../input.log to Val. Ignoring line., Reporter::WARNING
EventErrorEvent, Error while reading set or vector, Reporter::WARNING
EventErrorEvent, Invalid value for subnet: 127.0.0.1, Reporter::WARNING
EventErrorEvent, Skipping input with missing non-optional value, Reporter::WARNING
```

The first error is good.. mentions the invalid line and the file it comes from.  However, the other errors don't do this.  "Skipping input with missing non-optional value" and "Error while reading set or vector" can be very difficult to track down the root cause.

it is easier to see this if the test is modified to only have the first line in the input file:

```
@TEST-START-FILE input.log
#separator \x09
#fields i       s
name    -
@TEST-END-FILE
```

in that case, the btest outputs only this:

```
warning: Skipping input with missing non-optional value
```

**Comment by timwoj** [comment]
What location would you like to see here? The location in the script file where it was reading the file? It doesn't appear that the `Reader` code in the input framework maintains a location in the file it's currently reading, unfortunately.

**Comment by JustinAzoff** [comment]
The errors like this one are pretty good:

    EventErrorEvent, Could not convert line 'name\x09127.0.0.1' of ../input.log to Val. Ignoring line., Reporter::WARNING

It contains the line that failed to load and which file it was seen in.  If it could have the line number of the input file that could also be nice, but not critical.

Knowing the name of the input file that failed to load is usually enough context.. from the filename being loaded you can infer which script is responsible and what you need to fix.

**Comment by timwoj** [comment]
Like I suspected, we don't keep any sort of location information at all during the parsing. Even in the Ascii `ReaderBackend`, we keep a filename but not the line number we're parsing. On top of that, all of the logging goes through `MsgThread` because `ReaderBackend` inherits from that, and that's what the `Formatter` classes store. I could probably extend `MsgThread` a bit to take a `Location*` and keep track of that information somewhere. It's going to take a bit of work because a lot of these classes aren't in a `detail` namespace so we have to be careful not to break the API.

This is a bit more than what I think would fall under a good first issue so I'm removing that tag. I'll come back to it later after a squash a few other higher priority bugs.

**Comment by JustinAzoff** [comment]
ah, filename and the line itself is really probably good enough.  the `Location` is just going to be the script that has the add_input with the filename in question.

**Comment by timwoj** [comment]
I meant that I could probably build/store a separate `Location` object while the file is being parsed by the reader, and pass that a long when it goes to log the warnings.

**Comment by timwoj** [comment]
```
warning: ..<...>/Input::READER_ASCII: ../input.log, line 4: Invalid value for subnet: 127.0.0.1
warning: ..<...>/Input::READER_ASCII: ../input.log, line 4: Error while reading set or vector
warning: ..<...>/Input::READER_ASCII: ../input.log, line 4: Could not convert line 'name	127.0.0.1' of ../input.log to Val. Ignoring line.
```

Does that work better?
