### ISSUE TITLE
Better error message for parsing pcap with non-Ethernet encapsulation

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#1995]
When Zeek is run on pcaps it does not understand due to encapsulation, it throws the following error:

```
$ capinfos ../udp.pcap| grep Encap
                     Encapsulation = IEEE 802.15.4 Wireless PAN (104 - wpan)
$ zeek -Cr ../udp.pcap
fatal error in /usr/local/share/zeek/base/frameworks/packet-filter/./main.zeek, line 285: Bad pcap filter 'ip or not ip'
```

For someone new to Zeek, this is a fairly cryptic message as evidenced by [this thread](https://zeekorg.slack.com/archives/CSZBXF6TH/p1646180487407939) on the Zeek Slack. We were able to address the issue by changing the encapsulation type, but if the error suggested this as a possible root cause I believe newer users could figure out how to fix the problem themselves without having to ask in Slack.

I was going to open a PR that provided a hint, but I realized I don't quite understand the implications here. I see the error is primarily structured to show [a BPF filter compilation error](https://github.com/zeek/zeek/blob/52b3e159a415fb3acd584f95aa64e2d2a9c0b282/scripts/base/frameworks/packet-filter/main.zeek#L285), but that doesn't seem to be the case here. Is there a way to differentiate these two? Is there a list of encapsulation types that Zeek supports somewhere? Is the right way™ to fix this to simply add new encapsulation types? Happy to try to address this issue, but I'd appreciate some feedback from the Zeek pros on the smart way to do this.

**Comment by ynadji** [comment]
Another example of this biting users:
* https://zeekorg.slack.com/archives/CSZBXF6TH/p1652827889017099
* https://zeekorg.slack.com/archives/CSZBXF6TH/p1652828033482849

**Comment by timwoj** [comment]
The error message set in `PktSrc::Error` is the same error though:

```
(const std::string &) msg = "cannot compile BPF filter \"ip or not ip\""
```

which continues to make it not terribly useful. Even if it got past the call to`FatalError` it would just result in the same error message later. The PktSrc opens just fine here because the pcap PktSrc doesn't really check for anything other than the file being a valid pcap. It doesn't care what's actually in it.

There's a couple issues here:

1. Yes, that message does get eaten and it shouldn't. At the very least, it should get propagated up to script land so it can be output instead of just dumping out something generic.
2. `BPF_Program` provides two `Compile` methods, one of which is supposed to be used with `pcap_t` pointers since `pcap_compile()` can give more useful output in those cases. Unfortunately, the pcap `PktSrc` doesn't implement it's own compilation code and so we use the non-pcap one all of the time. Fixing that gives the following error message:

```
(lldb) p msg
(std::string) $0 = "cannot compile BPF filter \"ip or not ip\": pcap_compile(ip or not ip): IEEE 802.15.4 link-layer type filtering not implemented"
```

3. This still isn't great since we don't really care that it doesn't implement that filtering, especially given that our default filter basically says "yes, give me all of the data". We'd should be able to pass the data along to the packet analyzers just in case someone has implemented an analyzer for it.

**Comment by timwoj** [comment]
I'm going to close this issue since it fixes the logging issue, and open another for (3) above since it gets sorta sticky pretty fast.
