### ISSUE TITLE
How to optimize RAM usage for Zeek ?

### ISSUE THREAD

**Issue by cxdinter** [zeek/zeek#2016]
Hi,
     I want to porting Zeek into embedded environment. So, the DDR RAM resource is limited.
     When Zeek running with default setting, it allocated around 230 MB RAM. I tried to remove all scripts in local.zeek, but this operation only reduced about 5MB RAM.
     Is it possible to reduce more RAM usage for Zeek by some other configuration ? Thank you in advance.

**Comment by 0xxon** [comment]
Hi,

As you noticed, Zeek is currently not optimized for ram-constrained environments. There are no special switches that you can use to lower the memory use; there also is no specific configuration that you can use to lower the memory use. 

This fact comes from the history of Zeek - traditionally it has been (and is) often used to monitor high-speed links. So our focus has been speed - sometimes to the detriment of memory use (e.g. by pre-allocating variables). While, in recent versions, I think some of our data structures have become more memory efficient, there probably still is quite a bit to go.

I don't think we currently have any plans to change this. If someone were to look at the sourcecode and find easy ways to lower the memory use, without having a speed impact, I am sure we would implement them though.

I am going to close this issue - note that these kinds of questions are more suited to our Slack/mailing lists, since this is not really a bug.

Johanna
