### ISSUE TITLE
Cannot `join_string_vec` with a separator of `"\x00"`

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#2054]
```zeek
event zeek_init()
	{
	local v = vector("1", "2", "3");
	local s = join_string_vec(v, "\x00");
	#local s = join_string_vec(v, "\x01");
	#s = gsub(s, /\x01/, "\x00");
	print(s);
	}
```

Throws the following errors:

```
error: string with embedded NUL: "\x00"
error: string with embedded NUL: "\x00"
fatal error: errors occurred while initializing
```

Just `+= "\x00"` works fine, but is less efficient for long vectors. I ended up settling on the commented out hack, which also works fine. I'm not sure why it only complains when in `join_string_vec`.

**Comment by timwoj** [comment]
The problem is that `join_string_vec` calls `StringVal::CheckString()` which includes a null check (the source of the error message). Changing this line:

https://github.com/zeek/zeek/blob/2f453cd0cdf83f70ba656d8c5bd531a08f14ac9b/src/strings.bif#L105

to 

```
			d.AddN(reinterpret_cast<const char*>(sep->Bytes()), sep->Len());
```

appears to fix it:

```
% zeek ~/Desktop/2054.zeek
1\x002\x003
```

I'll open a PR for it.
