### ISSUE TITLE
Bad subnet masks should not manifest as internal errors

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#208]
An statement like `print 1.2.3.4/33;` errors out with `internal error in <stdin>, line 1: Bad IPAddr(v4) IPPrefix length : 33`.  This is both excessive and makes it hard to pinpoint what lead to the problem.  It should instead generate a regular run-time error.

**Comment by 4254** [comment]
Sent on the go with Vodafone-------- Original Message --------Subject: [bro/bro] Bad subnet masks should not manifest as internal errors (#208)From: vpax To: bro/bro CC: Subscribed An statement like print 1.2.3.4/33; errors out with internal error in <stdin>, line 1: Bad IPAddr(v4) IPPrefix length : 33.  This is both excessive and makes it hard to pinpoint what lead to the problem.  It should instead generate a regular run-time error.

**Comment by 4254** [comment]
Sent on the go with Vodafone-------- Original Message --------Subject: [bro/bro] Bad subnet masks should not manifest as internal errors (#208)From: vpax To: bro/bro CC: Subscribed An statement like print 1.2.3.4/33; errors out with internal error in <stdin>, line 1: Bad IPAddr(v4) IPPrefix length : 33.  This is both excessive and makes it hard to pinpoint what lead to the problem.  It should instead generate a regular run-time error.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bro/bro","title":"bro/bro","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/bro/bro"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Bad subnet masks should not manifest as internal errors (#208)"}],"action":{"name":"View Issue","url":"https://github.com/bro/bro/issues/208"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bro/bro/issues/208",
"url": "https://github.com/bro/bro/issues/208",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Bad subnet masks should not manifest as internal errors (#208)",
"sections": [
{
"text": "",
"activityTitle": "**vpax**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@vpax",
"facts": [
{
"name": "Repository: ",
"value": "bro/bro"
},
{
"name": "Issue #: ",
"value": 208
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"bro/bro\",\n\"issueId\": 208,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"bro/bro\",\n\"issueId\": 208\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/bro/bro/issues/208"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 408868204\n}"
}
],
"themeColor": "26292E"
}
]
