### ISSUE TITLE
Zeek wont install on Raspberry pi

### ISSUE THREAD

**Issue by lukepenick** [zeek/zeek#2083]
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

When trying to install I get the following error:

The following packages have unmet dependencies:
 zeek-zkg:armhf : Depends: python3-semantic-version:armhf but it is not installable
Depends: python3-git:armhf but it is not installable
E: Unable to correct problems, you have held broken packages.

Both are installed: (apt list --installed)
python3-semantic-version/stable,stable,now 2.8.5-1 all [installed]
python3-git/stable,stable,now 3.1.14-1 all [installed]

When trying "apt-get install zeek" I get these errors.

**Comment by 0xxon** [comment]
Is the installation that you have by any chance a 64-bit version of raspbian? (visible in `uname -a` output)

Sadly, OBS (the service that we use to build binary packages) does not yet support building 64 bit binaries. This  dependency error happens because of the architecture mismatch and is currently sadly unsolvable for us.

If you don't need Zeekctl, but only are interested in Zeek, you should be able to just install zeek-core. Otherwise, you should also be able to install it while ignoring the broken dependency; as long as you install the 64-bit version of python3-semantic-verion everything should still work.
