### ISSUE TITLE
type of vector loop index is int, not count

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#213]
The following code snippet prints "int", not "count": `for ( i in vector("a") ) print type_name(i);`, even though the documentation sez 

> A vector is like a table, except it’s always indexed by a count

The problem is the use of `basetype(TYPE_INT)` in `ForStmt::ForStmt`.

**Comment by jsiwek** [comment]
I've changed vector loop index to `count` since it more closely matches expectation/meaning.  Hypothetically, that could alter script behavior, but I can't think of any practical case where it would -- likely only when someone is inspecting the type of the variable, but I don't see any reason to write code that depends on that.  Let me know if there's contrary opinion.
