### ISSUE TITLE
Packet::{l2,l3}_checksummed variables are poorly named

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2183]
While looking at finally merging https://github.com/J-Gras/zeek-af_packet-plugin/pull/30, @J-Gras noticed that the `l2_checksummed` and `l3_checksummed` variables in `Packet` are poorly named. `l2` should be the network layer (meaning IP/Layer 3) and `l3_checksummed` should be the transport layer (meaning TCP,etc/Layer 4). We should rename these variables for correctness.

We can't just outright rename them because they have to go through the deprecation cycle. We could either just extend the names and make them `layer{3,4}_checksummed` or we can name them something like `mac_checksummed` and `trans_checksummed`, but neither of those names feel really great.

**Comment by timwoj** [comment]
How about `net_layer_checksummed` and `trans_layer_checksummed`?

**Comment by timwoj** [comment]
We also have `l2_src`, `l2_dst`, and `l3_proto`. Those might be harder to renamed as they're likely used all over the place. Those seem to be used correctly across the code based thought, with `l2` meaning the ethernet layer and `l3` meaning the network layer.

**Comment by grigorescu** [comment]
So, AFAICT, Zeek today is doing no layer 2 checksumming at all. Perhaps this is because we assume that ethernet frames with invalid checksums don't even make it to Zeek, but there are some capture methods that can have this happen.

My proposal would be:

- Implement (optional) layer 2 checksumming, and use `l2_checksummed` to determine if that's already been done,
- For layer 3, use `l3_checksummed` instead of `l2_checksummed`,
- Introduce a new variable, and use `l4_checksummed` for layer 4.

This would bring the variables in use today in line with the functionality implied by their names, minimize changes to existing code, and avoid the need to deprecate anything, since I think it's reasonable to say that the variable was just being mis-applied.

**Comment by timwoj** [comment]
> This would bring the variables in use today in line with the functionality implied by their names, minimize changes to existing code, and avoid the need to deprecate anything, since I think it's reasonable to say that the variable was just being mis-applied.

This sounds reasonable to me.

> Furthermore, there should be a note on the semantics in the presence of tunnels.

I'll have to double check but I don't think it matters. We create an entirely new packet to process from what's inside a tunnel, and it wouldn't have the flags set.
