### ISSUE TITLE
Zeek renaming: script file suffixes

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#237]
I think we can at least rename scripts distributed with Zeek to use a different suffix other than `.bro`.  What to use instead?  `.zeek` or `.zk` ?  I prefer `.zk` as it's shorter.

I don't recall what all internal logic depends on the file extension, maybe some file searching logic, but that would need to change.

Do we treat `.bro` as something that's deprecated and to be removed/unsupported later?  External packages could possibly want to use `.bro` for a prolonged time simply for compatibility reasons.

**Comment by JonZeolla** [comment]
Maybe it's just me but I think zookeeper with `.zk`, I would prefer zeek.  Also with a rename project as big as this, uniformity will make it easier to pick up for new people.

**Comment by sethhall** [comment]
I prefer .zeek fwiw.

**Comment by 0xxon** [comment]
And I kind of like .zk more (and don't think the conflict with zookeper is a big problem).

**Comment by vpax** [comment]
I know pretty much everyone is going to hate this suggestion, but: we could just accept & use both by convention.  After all, we're already going to have `.bro` for quite a while.

**Comment by JonZeolla** [comment]
I agree with @jsiwek's thought to deprecate `.bro` and suggest keeping it around for at least two releases.  I don't think the zookeeper conflict is a _big_ problem (just a potential problem), and they don't necessarily use a `.zk` file extension in zookeeper that I'm aware of regardless, it's just a bit confusing.

**Comment by hosom** [comment]
I think `.zk` is unlikely to ever come up as an issue. I think `.zeek` is completely reasonable, but agree with @vpax in that I don't care for any file extension > 3 characters. 

Accepting and using both is a great idea and it made me think of something else... Why not use explicit file names for loads and set `.zk` and `.zeek` as a standard?

**Comment by rsmmr** [comment]
I like `.zeek` the most. Advantage of a short name is that it works as an extension!

I wouldn't standardize on *two* new extensions, though, that just seems confusing.

**Comment by mavam** [comment]
I also like `.zeek` the best. If we were pioneering in the lands of 4-letter extensions, I'd be hesitant. But there already exists the ubiquitous `.docx` extension and a few related others. So people would be used to seeing this.

**Comment by dnthayer** [comment]
Here is what I've found that needs changing (let me know if some of these items are beyond the scope of this github issue):

Change bro and bro-pkg to recognize both the old and new file extensions:
1) Change some logic in bro to recognize the new script file extension, and look for ".bro" as a fallback.
2) Change "bro-pkg" to recognize both file extensions when looking for "__load__.bro" files.

Create auto-generated files with the new file extension:
3) Change "bifcl" and "BifCl.cmake" (in "bifcl" and "cmake" git repos) to use the new file extension when creating files.
4) Rename scripts in the plugin skeleton directory (in the "zeek-aux" git repo) to use the new file extension.
5) Change bro-pkg to create "packages.bro" (and the "__load__.bro" symlink) with the new file extension.
6) Change BroControl to create its files ("cluster-layout.bro", etc.) with the new file extension.

Rename existing scripts:
7) Rename the standard scripts to use the new file extension.

Fixes needed due to filenames changing:
8) Fix various test scripts that will break because of the above changes.
9) Fix BroControl due to the renaming of "local.bro" in step #7 above.

**Comment by rsmmr** [comment]
Sounds good. Is there anything here where users need to watch out for something breaking on their side? The main stuff should be covered by continuing to search for `.bro` as well, anything else?

**Comment by dnthayer** [comment]
Here are some situations that I can imagine might confuse a small subset of users, and therefore we should mention about these in the NEWS before the next release:
1) Someone has their own custom script that loads a standard zeek script explicitly specifying the ".bro" file extension (example: `@load policy/protocols/conn/mac-logging.bro`).  A user can easily fix this by removing the ".bro" from the `"@load"`.
2) Someone installs zeek, then manually copies their old customized "local.bro" file but it doesn't get loaded (it will be ignored because the "local.zeek" file will be loaded instead).
3) Someone does an in-place upgrade from bro to zeek and then later they manually edit one of the old ".bro" files but zeek will just ignore that file (loading the copy with the new file extension instead).

**Comment by jsiwek** [comment]
> 1. Someone has their own custom script that loads a standard zeek script explicitly specifying the ".bro" file extension (example: `@load policy/protocols/conn/mac-logging.bro`).  A user can easily fix this by removing the ".bro" from the `"@load"`.

This is maybe something we can try to handle: if they use `@load foo.bro` and we don't find a foo.bro file, then just go ahead and see if there's a foo.zeek ?

**Comment by vpax** [comment]
@jsiwek that fallback seems okay to me.

Did we already tussle over `.zeek` vs. `.zk`?  I recall differing tastes so might not be straightforward to resolve.

**Comment by jsiwek** [comment]
@vpax seems up to you or @0xxon to take up the fight for `.zk` if you have strong preference.  Or if at least one of you doesn't care much, then we might go ahead with `.zeek`.  I also like `.zk`, but not enough to spend time making a case in what looks like an even split in preferences.

**Comment by dnthayer** [comment]
> > 1. Someone has their own custom script that loads a standard zeek script explicitly specifying the ".bro" file extension (example: `@load policy/protocols/conn/mac-logging.bro`).  A user can easily fix this by removing the ".bro" from the `"@load"`.
> 
> This is maybe something we can try to handle: if they use `@load foo.bro` and we don't find a foo.bro file, then just go ahead and see if there's a foo.zeek ?

We could implement special-case handling of loads that end in ".bro", but on the other hand I checked all 83 bro packages and only these two are affected by this problem:
1) dopheide/bro_notice_correlation
2) jswaro/tcprs

The fix for these two packages is so simple (a one-line change for each package) that it doesn't seem worth it to make the zeek script search logic more complicated.

**Comment by vpax** [comment]
@dnthayer If it's that rare, then I agree with keeping the added complexity out of the search logic.
@jsiwek Well, I do care ... would like to understand just how many of us it is.  `.zeek` looks pretty clunky to my eye ....

**Comment by jsiwek** [comment]
@dnthayer but we're already adding complexity to the search logic to make `@load foo` search for either `.bro` or `.zeek`, so is it much more difficult to also add a fallback for `@load foo.bro` -> `@load foo.zeek` ?  It may be rare in the package ecosystem, but we don't know how much that pattern exists in unpublished scripts.  We just announced we'd ask for community feedback if we do breaking changes without a backward-compatibility period, so preferable to avoid that if adding the fallback is not too difficult.

@vpax sure.  Robin, Seth, Matthias and a couple others indicated favor for `.zeek`.  Me, you, and Johanna liked `.zk`.  That's all I can glean from this thread; not sure where to go from here.  Do a round of arguments for either case?  Solicit more opinions from mailing list?

**Comment by rsmmr** [comment]
Take to mailing list for discussion sounds good to me. I still like ".zeek".

**Comment by vpax** [comment]
I started composing a note to the mailing list and then realized that .zk is pretty suggestive of some sort of compressed file, per gzip and the like.  So I'm willing to accept .zeek instead ...

**Comment by jsiwek** [comment]
The migration .zeek files is mostly done now via #336 (there may be some stragglers like in the documentation or test suite I'll try to pick off later today).  Thanks Daniel, nice job breaking out a plan of action and finding all the bits to change.

**Comment by JeffBarron** [comment]
This whole thing just makes me sad and frustrated.  I wasn't planning on writing a python script to rename everything from .bro to .zeek I have ACTUAL work to do.
