### ISSUE TITLE
Confusion between `if`/`@if` and `else`/`@else`

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#2430]
```ruby
$ cat foo.zeek
event zeek_init()
	{
	if ( T )
		@if ( T )
			print "foo";
		@else
			print "bar";
		@endif
	else
		print "baz";

	}
```

I would expect the prior code block to print `foo`, however, it doesn't even compile:

```
$ zeek --version
zeek version 5.1.0-dev.497

$ zeek foo.zeek
error in ./foo.zeek, line 5: incorrect use of directive
error in ./foo.zeek, line 9: syntax error, at or near "else"
```

The errors together make me think it's confusing the `else` and `@else`, but I'm not entirely sure. Adding braces around the `then` block of the `if` statement removes the error and executes as expected. Given that both branches of the `@if` are a single line, I would expect this code to not need braces to parse correctly. @timwoj mentioned there might be some similarities to #2289 . Here's a [try zeek snippet](https://try.zeek.org/#/tryzeek/saved/608127) to show this occurs in other versions of Zeek as well.

**Comment by awelzel** [comment]
Hmm. What you observe is in fact the currently the expected behavior.

> Adding braces around the then block of the if statement removes the error and executes as expected.

See the commit (and NEWS entry) from this commit: https://github.com/zeek/zeek/pull/2347/commits/171846a37a0561e14625c4e6746daf4b699b50c9

Merge of https://github.com/zeek/zeek/pull/2347 made some scenarios fail that previous Zeek versions accepted but interpreted very unexpectedly. For example,

```
# Print's "hello" once with Zeek 5.0
local v = vector( 1, 2, 3 );

for ( i in v )
    @if ( T )
    print "hello", i;
    @endif
}
```

> Given that both branches of the @if are a single line, I would expect this code to not need braces to parse correctly.

I tried with #2358, but due to how directives are statements it wasn't easy. Rejecting the situation and adding braces wasn't considered a deal-breaker for situations that shouldn't happen too often - does it for you?


I'd propose to close this unless someone feels this needs revisiting.

**Comment by ynadji** [comment]
Not a deal breaker for me. I think the error message could be better, for example, directly referencing the:
> Conditional directives (``@if``, ``@ifdef``, ``@ifndef``, ``@else`` and ``@endif``) can not be placed directly following ``if``, ``for`` or ``while`` statements.

And to use braces to get the desired behavior. It was unclear to me exactly _what_ was failing, but (correctly) assumed braces would get me out of the jam. It might be helpful to flag this more explicitly for beginners.
