### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by credmond219** [zeek/zeek#2458]
`CMake Error at CMakeLists.txt:3 (cmake_minimum_required):
  CMake 3.15.0 or higher is required.  You are running version 3.10.2`

**Comment by timwoj** [comment]
As of Zeek 5.0, we require CMake 3.15.0 in order to build. This was due to spicy being included in the build, and was noted in the NEWS entry for that release.

I'm going to close this issue as it falls under a support issue. We don't use GitHub issues for support questions. Questions like this are best answered using on either slack or our forum, which is both are frequented by Zeek developers and professional users. You can join here:

Forum: https://community.zeek.org/

Slack: https://zeek.org/community/
