### ISSUE TITLE
Cluster startup event

### ISSUE THREAD

**Issue by J-Gras** [zeek/zeek#2480]
In a clustered Zeek, there are various use cases for things to wait until the cluster has been successfully started (i.e. all nodes are available). For example, several btests like [notice/suppression-cluster.zeek](https://github.com/zeek/zeek/blob/16601eafa2a11b7a8741e6369050afdec175445f/testing/btest/scripts/base/frameworks/notice/suppression-cluster.zeek) just count nodes/workers before starting their work. It would be extremely handy to introduce a startup event as part of either the cluster framework or the management framework.

With respect to #2479 it might make sense to introduce events for different startup stages as well.

**Comment by bbannier** [comment]
Does [`Management::Controller::API::notify_agents_ready`](https://docs.zeek.org/en/master/scripts/policy/frameworks/management/controller/api.zeek.html#id-Management::Controller::API::notify_agents_ready) provide what you are looking for?

Note that in general one cannot assume any cluster state after receiving such an event; agent could e.g., become available right after the event was triggered -- they might e.g., have become unreachable or be shut down right after you processed the event.  You should allow for that in anything which relies on a certain state by hooking into additional events to update your picture of the cluster.

**Comment by J-Gras** [comment]
> Does [Management::Controller::API::notify_agents_ready](https://docs.zeek.org/en/master/scripts/policy/frameworks/management/controller/api.zeek.html#id-Management::Controller::API::notify_agents_ready) provide what you are looking for?

Thanks for the pointer! If I got it right, this event is used on the agent level of the management framework. I am looking for an event that refers to the cluster node level. These are two separate things, right?

**Comment by ckreibich** [comment]
Thanks for the ticket, Jan! :-) Yes that's right, it's a different level. Let me cover some of the recent discussion: for orderly cluster start/stop, the Management framework is the right level, because it drives those steps, just like `zeekctl` already does it in its world.

A `cluster_init`, on the other hand, looks at home in the cluster framework, at least as long as we keep the model of a fully predefined, "rigid" cluster. This model implies that every node has full understanding of the topology and can therefore declare when all of its peerings are established. With pure Broker that's tricky (because `Broker::peer_added` provides no notion of what the new peer does/is), but the Cluster framework already puts `Cluster::hello` on top of that, pairing node names with Broker IDs.

A proxy knows when all workers have said hello, the manager knows when all workers and proxies have said hello, and the loggers know when everything else has said hello to them. All it takes at those points is to aggregate those local readiness observations (in the manager, most likely), so it can trigger `cluster_init`.  

Benjamin's point about the fact that things remain unreliable after that point is true. We could think about other kinds of cluster liveness events to cover that.

**Comment by J-Gras** [comment]
We have `Cluster::Experimental::cluster_started()` now 🙂
