### ISSUE TITLE
dce_rpc_request lacks useful data

### ISSUE THREAD

**Issue by hosom** [zeek/zeek#257]
It looks like the operation and endpoint are not assigned to the rpc operation until the response. I'm not certain if I'm missing a subtlety here, but would it make more sense to add these fields to the record on the request?

**Comment by jsiwek** [comment]
It's been a while since I looked at the protocol and don't know it well to any significant depth, but going from memory and my skim just now, it seems like we don't have the info with just a `dce_rpc_request` event -- i.e. the endpoint binding is independent of the request, so you can see we get a uuid in either `dce_rpc_bind` or `dce_rpc_alter_context` events and map it to an endpoint at that time.  A subsequent `dce_rpc_request` will have that information (unless maybe we missed the packets containing the binding info or else the client never actually sent it).

Please feel free to dig a bit to see if an improvement is possible, else close the issue if that explanation is accurate.

**Comment by hosom** [comment]
I'll dig into this with some test captures using dump events and see what I can come up with.

**Comment by neu5ron** [comment]
may help to use microsoft message analyzer on some PCAPs that have RPC in it. Microsoft may have some more "parsers" or identifiers for certain bits/flags set.

**Comment by rsmmr** [comment]
Closing as there wasn't any further follow-up. Feel free to reopen if there's more/new information.
