### ISSUE TITLE
Consider changing `get_event_handler_stats` bif to use telemetry framework

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#2572]
We added a new bif called `get_event_handler_stats` as part of the Microsoft work for returning some rudimentary information about calls to event handlers. It's just using a variable stored in each event handler at the moment, but we should consider migrating it to the telemetry framework.

**Comment by awelzel** [comment]
The one thing that will happen if we "just" use the C++ telemetry API is that metrics for all event handlers become immediately visible through the Prometheus endpoint which likely is too much overwhelming detail (by default, anyway).

@Neverlord - any thoughts how to make exposition through the Prometheus API conditional? We'd still would unconditionally create the telemetry::IntCounters per EventHandler (and adapt the existing bif could enumerate/read them), but they maybe shouldn't show up in the API.

We could also keep things as they are. We don't need the thread-safety provided by the C++ telemetry API and Zeek scripts can be used to expose the raw data as metrics. Filtering/customization might even be easier on that level due to being in script-land. It's not as direct, of course.

This has been done here, fwiw:

https://github.com/zeek/zeek-demo/blob/b7ff45bdb8cc2f2d2ae9be633817c134d5ba55dd/containers/zeek/scripts/telemetry.zeek#L183-L198

**Comment by Neverlord** [comment]
> any thoughts how to make exposition through the Prometheus API conditional?

Why make it conditional? Do the new metrics range in the dozens or hundreds? I generally would just enable them and measure if there's an issue with too much data. Users can pick and choose what they display and the increase in HTTP traffic shouldn't matter either. Even if you configure a scrape interval in millisecond range, Broker has a configurable interval how frequently it will actually scrape data (and otherwise send you the last computed result).

If it tuns out that we have tons of new metrics that do increase the scrape overhead to a degree where we should care about: we have a filter logic in place to include only selected prefixes. So all we'd need to do is to put the "noisy metrics" into their own prefix and tell Zeek/Broker to filter them by default. Seems like we already expose the filter option to script land: https://github.com/zeek/zeek/blob/master/scripts/base/frameworks/broker/main.zeek#L172 (default is to include all metrics).

**Comment by awelzel** [comment]
Closing as #2786 was merged.
