### ISSUE TITLE
Multiple plugins in ZEEK_PLUGIN_PATH lead to "Duplicate Zeekygen script documentation" warning

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#2577]
If you build (but don't install) 2 plugins, say `t/P1` and `t/P2`, and set up ZEEK_PLUGIN_PATH to include their `build` directories, then when running Zeek you get the message:

> warning: Duplicate Zeekygen script documentation: build/scripts/__preload__.zeek
warning in /Users/vern/zeek/t/P2/build/scripts/__preload__.zeek, line 10: Duplicate Zeekygen script documentation: build/scripts/types.zeek
warning: Duplicate Zeekygen script documentation: build/lib/bif/__load__.zeek
warning: Duplicate Zeekygen script documentation: build/scripts/__load__.zeek

**Comment by awelzel** [comment]
Hmm, not sure what to fix here. The old `init-plugin` skeleton and the new package template select the top-level plugin directory (P1/P2 in your example) for ZEEK_PLUGIN_PATH instead of ./build (the loader works recursively so it'll find the plugins) - you could trim the ./build part from ZEEK_PLUGIN_PATH to prevent the warnings.

https://github.com/zeek/zeek-aux/blob/7eef21a984f1b83266de7fdec1e492f90bf41ee7/plugin-support/skeleton/tests/Scripts/get-zeek-env#L11-L12

https://github.com/zeek/package-template/blob/1d5a647f6e9238bad0f0d1c736e899860d04b17d/package/testing/Scripts/get-zeek-env#L11-L12

Alternatively can set `ZEEK_DISABLE_ZEEKYGEN=1` in the environment.

If that's good enough, mind closing?

**Comment by vpax** [comment]
I'm using the `init-plugin` from Master (as of last week).  Removing `build/` from ZEEK_PLUGIN_PATH doesn't change the problem, I still get the warnings.

> Alternatively can set `ZEEK_DISABLE_ZEEKYGEN=1` in the environment

That's pretty unsatisfying.  It's quite a baffling error message, and seems to me should at least be made more clear.  Why is Zeekygen running anyway?  I would've thought it should instead be contingent on a `ZEEK_ABLE_ZEEKYGEN` variable.

**Comment by awelzel** [comment]
> Removing build/ from ZEEK_PLUGIN_PATH doesn't change the problem, I still get the warnings.

Ok - hmpf - let me try it, I had assumed that'll avoid it.

**Comment by awelzel** [comment]
> > Removing build/ from ZEEK_PLUGIN_PATH doesn't change the problem, I still get the warnings.
>
> Ok - hmpf - let me try it, I had assumed that'll avoid it.

Clearly should've just tried first. Sorry. Zeekygen uses the basename of the plugin directory for normalization and that's build both plugins.

https://github.com/zeek/zeek/blob/e2d46ea6b79bf3585ef51440d51ccb172051a924/src/zeekygen/utils.cc#L143-L153

> That's pretty unsatisfying.  It's quite a baffling error message,

I don't think I have a satisfying answer. It's a warning, but obviously irritating.

Loading plugins that have the same base directory isn't something that happens when plugins are installed via zkg or make install (see the contents build/dist/...tar.gz for what's put in place). Pointing at two ./build directories via ZEEK_PLUGIN_PATH is likely also uncommon.

More unsatisfying ideas:
* Run make install and skip setting ZEEK_PLUGIN_PATH (requires root and modifies Zeek installation)
* Disable zeekygen by default? We have bifs that assume zeekygen info is available, so that would be fairly major.
* Special case the `build` string case in the function pointed out for plugins and add the parent directory. `build` as a plugin name can't really exist and it's isolated to zeekygen.

The last is ad-hoc, but maybe pragmatic enough.

**Comment by vpax** [comment]
Which BiFs assume zeekygen info is available?  I poked through the source and didn't identify any. The main use I found was for the ReST stuff, which seems driven by zeekygen itself, though I certainly could've been missing something.

Putting that aside, just what is the basis for the error, anyway?  That there are two identical filenames coming from different sources?  If so, then isn't the fix for zeekygen to incorporate the path to the filenames?

It just seems (quite) weird that what's essentially marginal functionality would impose requirements on other completely unrelated functionality ...

**Comment by awelzel** [comment]
> Which BiFs assume zeekygen info is available? I poked through the source and didn't identify any. The main use I found was for the ReST stuff, which seems driven by zeekygen itself, though I certainly could've been missing something.

`get_record_field_comments` or `get_identifier_comments` in zeekygen.bif.
```
$ ZEEK_PLUGIN_PATH=$(pwd)/plugin1:$(pwd)/plugin2 zeek -e 'print get_record_field_comments("PluginOne::Info$ts")'
[...the warnings you reported...]
The ts field.
```
These are the BiFs used for Zeek log schema generation at startup/runtime by Seth/Smoot, for example.

> Putting that aside, just what is the basis for the error, anyway? That there are two identical filenames coming from different sources? If so, then isn't the fix for zeekygen to incorporate the path to the filenames?

Yes - I presume. Zeekygen currently tracks scripts/packages using "nice relative short paths" as that's what it want is used in docs rather than absolute paths. The warning does have value as the generated docs might be misleading when there are collisions. I've prepped a change that uses absolute names, but not sure I'm super happy - the explicit `./build` case would be less invasive.

> It just seems (quite) weird that what's essentially marginal functionality would impose requirements on other completely unrelated functionality ...

Agreed. AFAICT it just doesn't/hasn't come up before. For normal installations, a plugin's base directory is unique. This is a dev environment artifact triggered only when developing on more than one plugin in a `./build` path.

**Comment by vpax** [comment]
@awelzel thanks!

**Comment by ckreibich** [comment]
Sorry for the delay folks, sigh. Let me add two ideas because I think this just happens to hit a few unfortunate constellations that don't have to be this way.

- The `build` directory name is just a convention. We can change `init-plugin` to use a build directory of, say, `build-<namespace>-<name>`, to avoid this. (Similarly in the `zkg` template.) I just tried this out and it's a one-line change to the generated `configure` and `Makefile`.
- Zeek's plugin manager finds plugins by recursive descent through folders in `ZEEK_PLUGIN_PATH`. It finds a plugin directory when it sees a `__bro_plugin__` file. So in Vern's case `ZEEK_PLUGIN_PATH` could be something like `path/to/t`, not `path/to/t/P1/build:path/to/P2/build`. This could be a guide to making paths unique: if the plugin basename isn't unique, try to make it unique by expanding it up to the relevant `ZEEK_PLUGIN_PATH` component: here that'd yield `P1/build` and `P2/build`. There could still be the current warning once that doesn't work out.

These are complementary — we could implement both. We can also make the current warning more helpful.

(This also had me wonder whether we have parallels to this in `ZEEKPATH`. I _think_ we're okay there because I see multiple folders in my machine's `ZEEKPATH` that end with the same directory name, and iirc Zeek detects loads of the "same" file by absolute path. But I haven't fully verified.)
