### ISSUE TITLE
Consider making assigning unset `&optional` to other `&optional` non-fatal

### ISSUE THREAD

**Issue by bbannier** [zeek/zeek#2630]
Currently Zeek requires that the RHS in an assignment from an `&optional` to another `&optional` field is set.

```zeek
type X: record {
	x: count &optional;
};

type Y: record {
	y: count &optional;
};

event zeek_init()
{
	local x: X;
	local y: Y;
	y$y = x$x;  # expression error in ./x.zeek, line 13: field value missing (x$x)
}
```

It seems that it should be possible to allow such assignments so that they behave like e.g., assignments between `std::optional` values in C++: if the RHS is unset, the LHS becomes unset; else the LHS is assigned the RHS's value.

The current behavior leads to bugs like #2629.

**Comment by awelzel** [comment]
Hmm - not sure. There's a bit more going on in #2629 and that would've been silently hidden away if this proposal was implemented.

> The current behavior leads to bugs like https://github.com/zeek/zeek/issues/2629.

The bug is accessing an optional field without checking if it is set, which IMO either "documents" an assumption that it is always set, or the optional case simply has not been considered. I'd rather stick with that being explicit (or have some syntax to make it more concise), but not hide it away.

**Comment by ckreibich** [comment]
> The bug is accessing an optional field without checking if it is set

Yeah, that's the crux in this one, and unlikely to change. I see the convenience but if we except this just for assignments, for example, then that's imo more confusing than bailing out on the unchecked field access. It would also be tough to implement this consistently as an assignment special-case — what if that RHS weren't a direct `FieldExpr` but the result of a function call, say.

I'll go ahead and close this one.
