### ISSUE TITLE
Improve main event loop

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#264]
The main event loop has always been a bit of a nuisance -- primary problems seem to be that devs find it hard to understand and also there's high-ish CPU utilization even in situations where it should be mostly idling.

Here's an old reference with other thoughts/ideas that I'm not sure are still relevant: https://bro-tracker.atlassian.net/browse/BIT-1388

A concrete project would be to test out porting the event loop to use something like `libev` or `libuv` (or other event library) and seeing what results from it.

**Comment by timwoj** [comment]
After digging into the code and doing a survey of the available libraries out there, we settled on libuv (https://github.com/libuv/libuv). It handles file descriptors directly, which means it can handle all of the current input sources. It also has built-in support for DNS lookups which means the code in `nb_dns.cc` can likely all be removed.

**Comment by timwoj** [comment]
I ran into what might be an issue with libuv: https://github.com/libuv/libuv/issues/2428

**Comment by rsmmr** [comment]
Updating to cmake3 seems reasonable, that's been our for 5 years. I'll create a separate ticket for that.

**Comment by timwoj** [comment]
Some observations from a week of working with libuv:

Poll timeout is set to zero if we use `uv_idle` handles, which causes the loop to just spin forever and use 100% of the CPU. If not using `uv_idle` handles and with the default `UV_RUN_DEFAULT` mode, the poll timeout is either infinite or the time that the next `uv_timer` handle will fire. The easy solution is to just use `uv_prepare` handles everywhere instead of `uv_idle` handles, but that causes the poll to just hang forever if there's nothing to be read on any of the actual file descriptors.

This is fine for things that have real file descriptors, since the poll will block for packet sources that are interfaces and for broker, or it will fire based on a timer being ready. The existing thread manager code doesn't return any file descriptors and so it currently doesn't have a say in when `select` would return, and the same would continue. The threading manager will be called with every loop, but only when something else wakes up the poll.

I haven't dug super-far into how the existing timers work yet. libuv timers fire based on a millisecond timeout from when `uv_timer_start` is called, and can optionally be scheduled to repeat some number of milliseconds as well. Right now I'm assuming I can work our existing timers into that sort of architecture, but I'll likely get to that this week.

The real problem with the looping is in the case of pcap files. With pcap files, we actually want the loop to spin as fast as it can, only it will ignore packet data when in psuedo-realtime mode and the timestamp hasn't been met yet. I'm considering just making this a `uv_idle` handle and letting it spin.

See http://docs.libuv.org/en/v1.x/design.html#the-i-o-loop for more info on how the poll loop works.

**Comment by timwoj** [comment]
The things I haven't really dug into yet:
- Timers
- DNS. Right now I think I can replace whole swaths of `DNS_Mgr` with calls to `uv_getaddrinfo` and `uv_getnameinfo`, but keep all of the name caching that exists.

**Comment by jsiwek** [comment]
This is done via #681
