### ISSUE TITLE
Add lambda functions with closures

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#270]
I believe this should be doable by adding a new `Val` type that records a function pointer along with a captured closure. 

(There *might* also be something to borrow from the `async` branch, but not sure)

**Comment by rsmmr** [comment]
Some thoughts on how we could implement this:

- We don't have a dedicated `Val` for functions, but we have `Func` to represent a function and we already derive a couple of different flavors from that. I'd try deriving a new `LambdaFunc` from `BroFunc` (which is representing a "normal" script function) and provide an additional `Frame` to its constructor, representing the scope to capture. The constructor would copy that frame through `Frame::Clone()`` and store the copy internally. Then override `Call()` to execute the lambda function using those captured values. `Call()` will need to build a new frame each time and copy in deep-copies of the values from that saved frame as well as the actual function arguments.

- Add a new expression, `LambdaExpr`, that instantiates a `Val` with a dynamically created `LambdaFunc` on evaluation. As it'll just look like a normal function value, most other stuff should be transparently working at that point.

- I believe the main challenge with all of this is having `LambdaFunc::Call() build the joined frame for executing the lambda function: The indices of the frame's slots must match the ID mapping inside the body of the lambda function. The problem here is that two different IDs could end up using the same frame slot because originally, they were referring to two different, independent scopes (the outer one we're capturing, and the inner one from the lambda function itself). An idea to solve this: When parsing into a lambda function, I believe we could determine at that point how large the current frame is, and then assign all new IDs at offsets counting from there. And then `Call()` would later build a matching frame by filling in first the captured values, then the arguments, and then leave space for any additional local variables inside the body. (`make_ID()` is the relevant function where frame offsets are assigned to IDs).

- Things to watch out for:
     - Make sure lambda functions can be nested (i.e., one can created lambda functions inside other lambda function)
     - Check uses of `Val::func_val` for anything else that needs to be adjusted. One specific thing: Cloning a `Val` storing a LambdaFunc` needs to clone the captured frame, too (whereas currently cloning a function is a no-op)

**Comment by rsmmr** [comment]
@jsiwek Does this make sense to you?

**Comment by ZekeMedley** [comment]
> I believe the main challenge with all of this is having LambdaFunc::Call() build the joined frame for executing the lambda function: The indices of the frame's slots must match the ID mapping inside the body of the lambda function...

I think that a nice way to get around this is to take advantage of the fact that all the variables are being copied by value. When you create the lambda, create a new scope and essentially make new declarations of the variables being moved in inside of that scope. Then, continue to parse the lambda function normally. This has the disadvantage that something like the python script below wouldn't work, but I think that would be fine in Zeek because the idea of passing by reference and pointer isn't so fleshed out.

```
>>> a = 2
>>> b = lambda: a + 2
>>> b()
4
>>> a = 3
>>> b() # Zeek version would print 4 still because it made a copy of a
5
```

The other thing worth considering I think is rather or not the lambda should capture the entire enclosing scope, or allow the programmer to specify what variables to capture like in C++. Python does the first one, but I'd worry that if we choose to copy everything over, you could potentially end up with a decent amount of extra stuff sitting in the lambdas scope that it doesn't really need. I tend to lean towards letting the programmer specify which values to capture in the lambdas closure using C++ style syntax and maybe offering [`[=]`](https://en.cppreference.com/w/cpp/language/lambda#Lambda_capture) closures like C++ as well to just capture the entire enclosing scope:
```
[closure] (arguments) {body}
```
@ckreibich do you have any input on which might be more useful or if this is what you were interested in?

**Comment by jsiwek** [comment]
Generally making sense to me:

* Adding closure support is basically a `Frame` management issue.  A nice-to-have is not unnecessarily binding/copying things we don't actually use within the inner-scope.

* The other main trick will be correctly mapping the `ID` and `Frame` offsets within closures.  Don't know exactly what that will look like, but we do/can know when we are parsing whether it would be a closure (see `OuterIDBindingFinder`, which currently prohibits the creation of closures just because we didn't want to add full support at the time) and then we can also have custom logic in `Call()` to ensure correct value offsets.  There is also the concern of making sure nesting of closures works right.

* Don't think we need a new `LambdaExpr` since we already have anonymous functions?  Guess we should take inventory of what we currently can do in the Zeek language and clarify nomenclature from there:

Are we using "lambda" to mean the same thing as "anonymous" ?  I've seen some try to take "lambda" as meaning only "when the function is used as a value, such as assigned to a variable or passed as function argument".   So in that case, you could have named or unnamed lambda functions.  But I don't find it helpful to distinguish those, it's kind of implied by "functions are first-class".

I do find it more descriptive to use "anonymous" rather than "lambda" in our case:

1. We have named functions:

```bro
function named_func()
    {
    print "here's a named function";
    }
```

2. We have anonymous functions:

```bro
# Assigned to global variable.
global anon_func = function() { print "anon func"; };

event zeek_init()
    {
    # Assigned to a local variable (e.g. "a lambda" by some definitions)
    local greeting = function(name: string): string { return "Hi, " + name; };
    print greeting("Dave");

    # Or may be used directly and not stored as a value anywhere.
    print (function(name: string): string { return "Hi, " + name; })("Bob");
    }
```

3. Named functions must be declared at global scope.  Anonymous functions can be declared at either global or local scopes.  i.e. this doesn't work (or at least I don't think there's a way to get it to work):

```bro
event zeek_init()
    {
    function named_func()
        { print "here's a named function"; }
    }
```

4. Whether or not a function is a closure depends on if it references a non-local variable, so only anonymous functions may be closures in our case.

So judging from all that, I'd nitpick that if we're subclassing `Func` further, seems we only need to do that for what's properly and consistently known as "closures".  i.e. so we add `ClosureFunc` instead of `LambdaFunc`.

**Comment by ZekeMedley** [comment]
This is all a great starting point. Thanks a bunch for the explanation. I didn't realize we already had anonymous functions.

It seems like a `ClosureFunc` is for most intents and purposes just an  anonymous function with a little bit of extra code around its `Frame`. I'll take a stab at implementing it as such.

**Comment by rsmmr** [comment]
Agree, building out the anon functions sounds good.

**Comment by ZekeMedley** [comment]
I think the only big thing left to resolve is when / how we decide a function should capture a closure. Based on what I have so far, I don't think the choice will impact the implementation too much, so I tend to think then that its just a matter of preference. The two most obvious ones are:

1. **Anonymous functions capture their closures by default.** This is currently explicitly unsupported in Zeek, and would be closer to a pythonic way of doing things. This shouldn't add much performance overhead because there is already some static analysis performed in Zeek to find references to the enclosing scope's variables. Worst case you'll copy only the values you need. The advantage of doing this is that there is no need to add additional special syntax for declaring a function that captures its closure and it makes anonymous functions behave in a way that's similar to existing languages.

2. **Introduce new function syntax for capturing closures.** This would be closer to the C++ way of doing things. I image adding an optional piece of syntax to anonymous functions where the programmer could specify what variables they could like to capture, and use C++'s `[=]` to indicate that they'd like to capture everything from the enclosing scope. For example:
```Zeek
event zeek_init()
    {
    local n = 10;
    local m = 11;

    # capture variables with [ ... ]
    local add_n = function(i : count) [n] : count { return (n + i); }; 
    local capture_everything = function(i : count) [=] : count { return (i + n + m); };

    print add_n(3); # prints: 13
    print capture_everything(3) # prints: 24
    }
```
@rsmmr @jsiwek do you guys have any thoughts or additional ideas?

**Comment by jsiwek** [comment]
> 1. Anonymous functions capture their closures by default.

I'm inclined to go this way.  Don't see benefit of requiring different/extra syntax since a closure is implied by the use of a non-local variable somewhere in the function body.

**Comment by rsmmr** [comment]
Same here, agree.

-- 
Robin Sommer * Corelight, Inc. * robin@corelight.com * www.corelight.com
