### ISSUE TITLE
100.64.0.0/10 is not tagged as local net

### ISSUE THREAD

**Issue by sp-romain** [zeek/zeek#2761]
In eve log, `local_orig` / `local_resp` are set to `false` with the subnet 100.64.0.0/10.

```
{
  "ts": 1675724365.526336,
  "uid": "CCS5ib1CTbiP9XDijf",
  "id.orig_h": "xxxx",
  "id.orig_p": 56937,
  "id.resp_h": "100.102.248.9",
  "id.resp_p": xxxx,
  "proto": "tcp",
  "duration": 9.5367431640625e-07,
  "orig_bytes": 0,
  "resp_bytes": 0,
  "conn_state": "S0",
  "local_orig": true,
  "local_resp": false,
  "missed_bytes": 0,
  "history": "S",
  "orig_pkts": 2,
  "orig_ip_bytes": 96,
  "resp_pkts": 0,
  "resp_ip_bytes": 0,
  "orig_l2_addr": "xxxx",
  "resp_l2_addr": "xxxx"
}
```

However this subnet is present in share/zeek/base/utils/site.zeek, so it should be identified as a local net

```
# Shared Address Space (also known as Carrier-grade NAT), see :rfc:`6598`
100.64.0.0/10,
```

**Comment by ckreibich** [comment]
Thank you — yes, this is due to known inconsistencies around our treatment of "local" IP addresses. The definition you're referring to is `Site::private_address_space`, which lists it exhaustively, but isn't active by default: `Site::local_nets`, which governs the behavior you're observing, remains empty by default. `zeekctl` users default to 10/8, 172.16/12, and 192.168/16 as local nets, so it's all a bit inconsistent.

I'm about to default `Site::local_nets` everywhere to `Site::private_address_space`, which met no objections when proposed on Slack recently.

**Comment by ckreibich** [comment]
ps: eve log is in the other big open-source network monitoring project. :stuck_out_tongue:

**Comment by sp-romain** [comment]
Thanks for quick reply!
