### ISSUE TITLE
Allow to suppress `&deprecated` warnings

### ISSUE THREAD

**Issue by J-Gras** [zeek/zeek#2825]
It would be nice to have the ability to suppress deprecation warnings for a code fragment or a complete file. For example, in #2823 it would make sense to deprecate `Cluster::worker_count`. However, as the script itself needs to maintain the count as long as it is present, it would generate warnings.

**Comment by awelzel** [comment]
I stared a bit because that might be helpful if we do #2877 (or the Node$ip deprecation). Think zeekctl populating cluster-layout and suppressing the warnings, but external users using `Node$ip` or `Node$interface` receiving them.

One idea would be new directives of the following form:
```
@start-ignore-deprecations
...
@end-ignore-deprecations


@start-ignore-deprecations
@load ./some-deprecated-script.zeek
@end-ignore-deprecations
```

Could also have `@ignore-deprecations` for the whole file, but tempted to say that's could be start/end over the whole file ;-)

It looks a bit verbose, but at the same time somewhat fits into the existing directives, and generally being verbose/noisy for things that should be used sparingly standing is probably a good thing.

Unfortunately there's not a single deprecation "channel" where messages go through, and there are a few ad-hoc messages here and there.

**Comment by vpax** [comment]
A minor thought would be to consider doing this via a new `@pragma` "conditional", which would let us add other stuff in the future using a common framework.  E.g. `@pragma no-ZAM` to work around a ZAM bug.

**Comment by timwoj** [comment]
> A minor thought would be to consider doing this via a new `@pragma` "conditional", which would let us add other stuff in the future using a common framework. E.g. `@pragma no-ZAM` to work around a ZAM bug.

I like this quite a bit. Are you envisioning this being like the existing @if directive where there's an opening/closing statement for a block of sorts, or something more like `#pragma` in C++ where how it's handled is dependent on the pragma itself? Pragmas in C++ are handled as individual statements. For examples, `#pragma once` only has to be placed once at the top of the file, but GCC has their diagnostic pragmas that allow pushing/popping different directives for various blocks.

Something similar to @if would definitely be easier to implement, but the C++ one is quite a bit more powerful.

**Comment by awelzel** [comment]
> I like this quite a bit. Are you envisioning this being like the existing @if directive where there's an opening/closing statement for a block of sorts, or something more like #pragma in C++ where how it's handled is dependent on the pragma itself? 

Had thought to start with `@pragma start-ignore-deprecations` and that would need to be followed by a `@pragma end-ignore-deprecations`. This could be aligned more to the diagnostics push/popping, but might be overdoing it if we mainly want to suppress deprecation.

> Something similar to @if would definitely be easier to implement, but the C++ one is more powerful.

Might not follow, isn't it essentially depending on the command/value handling that's following `@pragma` and setting/resetting flags for the parsed files or globally?

**Comment by stevesmoot** [comment]
I don’t know if this would be in scope, but I had a similar idea when
looking at Schema generation. When the schema’s type system of tighter than
zeek’s it would be nice to be able to express it, e.g. schema supports
int16 int32 but we’d need To do int64 programmatically as it’s the halting
problem to know.  But one could annotate the types with something to enable
scehema generation to be tighter.

An edge case I am sure, but for your consideration.  (We’d also need to
expose it to the zeekygen api so zeek script could use; my first idea was
in the comment as that’s plumbed already)

S

**Comment by bbannier** [comment]
> > Something similar to @if would definitely be easier to implement, but the C++ one is more powerful.
> 
> Might not follow, isn't it essentially depending on the command/value handling that's following `@pragma` and setting/resetting flags for the parsed files or globally?

I think a clean solution could be to use markup for some kind of source range (either closed with `START` & `END`, or half-open until the end of the current file with just `START`). The `Reporter` could then use the range to mute diagnostics from the marked up source range. The only thing this would not allow would be to mark depreciations in loaded files, e.g.,

```zeek
# MARKUP-SUPPRESS-START
@load foo/bar  # triggers deprecations with their own locations elsewhere
# MARKUP-SUPPRESS-END
```

IMO this does not look like a big issue since at least I personally would prefer a more fine-grained approach to diagnostic suppression since it seems easier to reason about. When Vern introduced `--no-unused-warnings` we had [a discussion around a more generic framework for suppressing diagnostics](https://github.com/zeek/zeek/pull/2090#pullrequestreview-980861744); maybe it would make sense to invest into a way to globally disable diagnostics via a command line flag with this issue or in a follow-up.

* * *

In any case, I believe C pragmas need to be way more powerful since it is very easy to trigger diagnostics from code elsewhere locally (e.g., C++ template instantiation failures, macro expansions, local modification of source location with `#line`, ...). Apart from `@load` I cannot think of ways to trigger such non-local issues in Zeek script.

Since nothing about this markup would change how the source code should be parsed, I wonder if we should introduce a new Zeek script macro at all. When consuming source code in e.g., an editor a macro provides no additional interesting information, but it typically makes it much harder to model the source code in a CST, see e.g., [this discussion over in zeek/tree-sitter-zeek](https://github.com/zeek/tree-sitter-zeek/issues/6). There was some [discussion to toggle formatting with zeekscript with magic comments](https://github.com/zeek/zeekscript/issues/4) (this would be similar to how clang-format uses magic comments); similarly one could argue that magic comments would be enough to guide suppression of diagnostics (like e.g., [clang-tidy implements it currently](https://clang.llvm.org/extra/clang-tidy/#clang-tidy-nolint)).

Another benefit of magic comments would be that it could be easier to implement support for suppression just the current line (similar to how `clang-tidy` understand `# NOLINT`; not we'd have a strong requirement for `NOLINTNEXTLINE`),

```zeek
deprecated_fun();  # MARKUP-SUPRESS-FROM-THIS-LINE
```
