### ISSUE TITLE
Is v5.2.0 the latest release?

### ISSUE THREAD

**Issue by ZhongRuoyu** [zeek/zeek#2834]
Hi, Homebrew maintainer here. We noticed that while `v5.2.0` is already released (with release notes available), zeek `v5.0.7` is still the one marked as latest on the [releases page](https://github.com/zeek/zeek/releases). So, we would like to confirm the status of the `v5.2.0` release. Thanks!

**Comment by awelzel** [comment]
v5.2.0 is the latest feature release, v5.0.7 is the latest LTS (long-term stable) release. @timwoj should confirm what we mark with "latest" in the GitHub releases page.

It seems homebrew has previously released 5.1.3 (previous feature release) and seems reasonable to bump to 5.2.0 rather than downgrading to a 5.0 release.

I'm going to close this issue. Feel free to reach out on Slack (zeekorg.slack.com) or Discourse (community.zeek.org).

**Comment by ZhongRuoyu** [comment]
Thank you very much for the information, @awelzel. Given this situation, we will bump it to v5.2.0, and from now on, make sure the one marked as latest is used.
