### ISSUE TITLE
Replace deprecated conan generators for Windows

### ISSUE THREAD

**Issue by d4rk-d4nph3** [zeek/zeek#2897]
I have mentioned this in https://github.com/zeek/zeek/issues/2896 also.

Zeek v5.2's _conanfile_windows.txt_ uses generators (cmake and cmake_find_package) that are deprecated from conan v2 onwards.

It is now time to replace them with their successors.

**Comment by timwoj** [comment]
Do you have a link to documentation for replacing these?

**Comment by d4rk-d4nph3** [comment]
I found this issue comment (https://github.com/conan-io/conan/issues/12040#issuecomment-1238753532) during my search.

**Comment by timwoj** [comment]
This looks like it's going to require some rework of how we find/add the library targets to the main Zeek target. I'm going to hold off doing these changes until the CMake rework is done, since it's going to conflict a bit. The current setup is working fine for now, but we should eventually move to the new generators.

**Comment by d4rk-d4nph3** [comment]
Sounds good!

**Comment by timwoj** [comment]
I'm going to reopen this so we don't forget about it. It's marked low-priority so someone can get to it eventually.

**Comment by timwoj** [comment]
We ended up completely replacing Conan with vcpkg in https://github.com/zeek/zeek/pull/3576. This issue is obsolete now.
