### ISSUE TITLE
I found many memory leak problems with Valgrind

### ISSUE THREAD

**Issue by wubonetcn** [zeek/zeek#2952]
The following is a report generated by Valgrind, which details the locations where memory leak occur. 
You can use the following command to reproduce this example. The zeek version I tested is 5.2.0.
```
valgrind --log-file=./valgrind_report.log --leak-check=full --show-leak-kinds=all --show-reachable=no --track-origins=yes  build/src/zeek -Cr ~/Downloads/spirent-tc-mix_flow-100k.pcap
```
If you have identified these issues, please fix them in a timely manner. Thank you.
[valgrind_report.log](https://github.com/zeek/zeek/files/11230912/valgrind_report.log)

**Comment by timwoj** [comment]
These are known memory blocks used by various structures during runtime and are simply not released before shutdown. This is intentional, as most of them are globals or static data.

We have memory leak tests that run as part of the CI builds. If you have a report of something being leaked during runtime (and not at shutdown), we'll gladly take a look.
