### ISSUE TITLE
Building external Plugins no longer works via zeek-config

### ISSUE THREAD

**Issue by Neverlord** [zeek/zeek#2953]
For #2799, I've tested external plugins with:

```
./configure --zeek-dist=/path/to/zeek/sources
```

However, turns out there is yet another way to build plugins (that is currently broken):

```
export PATH=/path/to/zeek/bin:$PATH
./configure
```

The latter is supposed to retrieve the zeek-dist path "automagically" from `zeek-config`, apparently. I wasn't aware of this option, so that's currently broken. Thanks @awelzel for reporting this and explaining to me how its supposed to work.

I'll provide a fix for supporting this option again ASAP.

**Comment by ckreibich** [comment]
To add a bit of context:

Building plugins via the source distribution is not normally done these days, since Zeek installations have included the required headers for a long time now. `zeek-config --include_dir` and similar calls currently cover this. A more full-fledged `find_package(Zeek)` could take of it in the future to reduce reliance on `configure`.

Testing changes to plugin infrastructure should ideally include the following step, which exercises zkg's standard package template with inclusion of a plugin:
```
$ zkg create --packagedir foo --feature plugin
$ cd foo
$ zkg install .
```

The relevant `configure` script implementations are:
- https://github.com/zeek/zeek-aux/blob/master/plugin-support/skeleton/configure (for plain plugins, less common these days given that zkg packages are the common vehicle)
- https://github.com/zeek/package-template/blob/master/features/plugin/configure (for Zeek packages including plugins)

**Comment by Neverlord** [comment]
The configure scripts set a couple of "magic variables" that they get from `zeek-config`. Most importantly:

- `BROKER_ROOT_DIR` (for finding Broker)
- `BRO_CONFIG_CMAKE_DIR` (for finding our CMake package file for Zeek)

**Comment by dopheide-esnet** [comment]
This showed up in our auto builds a few days back as well, happy to help test when a fix is available.
