### ISSUE TITLE
How to filter files according to their contents

### ISSUE THREAD

**Issue by wangchencheng93** [zeek/zeek#302]
Hello,  i am new in bro. I wonder if you could help me with this.
I  want to filter files through regex, extract the files of contents matching the regex.
I found a related field named bof_buffer of fa_file type, but its size  is small.
I can't get the whole contents of the file before send it to file analyzers.
How can i do?

**Comment by jsiwek** [comment]
Hi, you can increase the `default_file_bof_buffer_size`, but, by default, it can't automatically store full files of arbitrary size for you to access since that's likely not performant.

If you need access to full file contents, you may have to collect that yourself, via the `Files::ANALYZER_DATA_EVENT`.  An example of that is here:

https://github.com/zeek/zeek/blob/a36ac12e885a60ee77f9141d4c35882cb53bc1f2/testing/btest/scripts/base/files/data_event/basic.bro

E.g. that `stream_data` event would receive chunks of the file in order, as they are processed, and you could collect them.

Other file analysis docs may be useful, in case you haven't seen them:

https://docs.zeek.org/en/stable/frameworks/file-analysis.html

Also, we tend to only use GitHub for bug reports or feature requests, not general questions or user support, but the mailing list has a wider range of users reading it and you may get more feedback for this type of thing if you inquire there:

http://mailman.icsi.berkeley.edu/mailman/listinfo/zeek

**Comment by wangchencheng93** [comment]
Thank you very much for your reply.  It's very useful to me. I‘ll try to follow your advice.
