### ISSUE TITLE
No mime_type extracted following the file extraction exercises tutorial

### ISSUE THREAD

**Issue by JackLiar** [zeek/zeek#310]
```
global ext_map: table[string] of string = {
    ["application/x-dosexec"] = "exe",
    ["text/plain"] = "txt",
    ["image/jpeg"] = "jpg",
    ["image/png"] = "png",
    ["text/html"] = "html",
} &default ="";

event file_new(f: fa_file)
    {
    local ext = "";

    if ( f?$mime_type )
        ext = ext_map[f$mime_type];

    local fname = fmt("%s-%s.%s", f$source, f$id, ext);
    Files::add_analyzer(f, Files::ANALYZER_EXTRACT, [$extract_filename=fname]);
    }
```

Above is the event I used. By the way your [tutorial](https://www.zeek.org/current/solutions/faf/index.html) needs to be updated, since there is no 'mime_type' in f.

I've tried it in both Bro v2.5 and Bro v2.6.1, and with either way I got:

```
root@6e3351e619a8:~# ls extract_files/
FTP_DATA-Fc4plc4XswHlUlymcg.  HTTP-FDlrWv2lAOeikDJFC.	HTTP-FS5CA72hiosbQD9bFj.  HTTP-Fx3fxB3f4Et7yuiaJ6.  SSL-F0gWRGv5NNTRJaVob.   SSL-FBHOuX3wpA7DHOnzV9.  SSL-FmqSV91YN8RRUezovf.
HTTP-F3cPWV3K80Pv20uvB3.      HTTP-FK1UF01GGeM1KmOl9b.	HTTP-FTVHj61SceMn6ANu94.  SMTP-FCNK0F2MhRNdL6RCof.  SSL-F62COt4jXDRRGIvLvj.  SSL-FDXRqW2EonC1K2dw1b.  SSL-FnpK2m3N9eIkZ4CMPf.
HTTP-F4NQcfI9JvDD83Jk3.       HTTP-FLDSNL1qbhIhy7nPU1.	HTTP-FUx1H60E29hOFs0pi.   SMTP-FbUS8R2oihxulRlvke.  SSL-F7xIrP2tGDMtXMTXIa.  SSL-FK4DEzuAa442Tz219.   SSL-FqLkBE4NQUd1V7WBh1.
HTTP-FAoo1c1moUwZAJFrk5.      HTTP-FNwwfC1t6KDzJjs3I1.	HTTP-FmLtzEb0czyaCJCn6.   SMTP-Fgk3Xx2gwg7kWbUEv7.  SSL-FAAXbq2reX8vVL9Co5.  SSL-FLk1OJ2hoi1nXFwZe7.  SSL-FutTprVmY01fWuY0k.
HTTP-FCISWc3UMczgaaBalf.      HTTP-FQLfX04sHQ3AeYYYX4.	HTTP-FpUZ2j3qI0Le7kbKN9.  SSL-F0Dg393TiBWNGsxKOl.   SSL-FB48fp3x2Z7h5I0sRg.  SSL-FetgZr162uaF2KPsRb.  SSL-FvC1E64g6kexAIp202.
```

What is wrong and what should I do...?

Plz help me :(

**Comment by jsiwek** [comment]
> Above is the event I used. By the way your [tutorial](https://www.zeek.org/current/solutions/faf/index.html) needs to be updated, since there is no 'mime_type' in f.

Sorry, the tutorials/exercises on the website tend to come from old conferences and so don't get updated later on.

The materials at [docs.zeek.org](https://docs.zeek.org) are usually reliable, though.  The file analysis docs there may be useful to you:

https://docs.zeek.org/en/stable/frameworks/file-analysis.html

E.g. you'd probably want to handle the `file_sniff` event since that's where you can get the `mime_type` field:

```bro
event file_sniff(f: fa_file, meta: fa_metadata)
	{
	if ( ! meta?$mime_type ) return;

	local ext = ext_map[meta$mime_type];

	local fname = fmt("%s-%s.%s", f$source, f$id, ext);
	Files::add_analyzer(f, Files::ANALYZER_EXTRACT, [$extract_filename=fname]);
	}
```

> I've tried it in both Bro v2.5 and Bro v2.6.1, and with either way I got:
> 
> ```
> root@6e3351e619a8:~# ls extract_files/
> FTP_DATA-Fc4plc4XswHlUlymcg.  HTTP-FDlrWv2lAOeikDJFC.	HTTP-FS5CA72hiosbQD9bFj.  HTTP-Fx3fxB3f4Et7yuiaJ6.  SSL-F0gWRGv5NNTRJaVob.   SSL-FBHOuX3wpA7DHOnzV9.  SSL-FmqSV91YN8RRUezovf.
> HTTP-F3cPWV3K80Pv20uvB3.      HTTP-FK1UF01GGeM1KmOl9b.	HTTP-FTVHj61SceMn6ANu94.  SMTP-FCNK0F2MhRNdL6RCof.  SSL-F62COt4jXDRRGIvLvj.  SSL-FDXRqW2EonC1K2dw1b.  SSL-FnpK2m3N9eIkZ4CMPf.
> HTTP-F4NQcfI9JvDD83Jk3.       HTTP-FLDSNL1qbhIhy7nPU1.	HTTP-FUx1H60E29hOFs0pi.   SMTP-FbUS8R2oihxulRlvke.  SSL-F7xIrP2tGDMtXMTXIa.  SSL-FK4DEzuAa442Tz219.   SSL-FqLkBE4NQUd1V7WBh1.
> HTTP-FAoo1c1moUwZAJFrk5.      HTTP-FNwwfC1t6KDzJjs3I1.	HTTP-FmLtzEb0czyaCJCn6.   SMTP-Fgk3Xx2gwg7kWbUEv7.  SSL-FAAXbq2reX8vVL9Co5.  SSL-FLk1OJ2hoi1nXFwZe7.  SSL-FutTprVmY01fWuY0k.
> HTTP-FCISWc3UMczgaaBalf.      HTTP-FQLfX04sHQ3AeYYYX4.	HTTP-FpUZ2j3qI0Le7kbKN9.  SSL-F0Dg393TiBWNGsxKOl.   SSL-FB48fp3x2Z7h5I0sRg.  SSL-FetgZr162uaF2KPsRb.  SSL-FvC1E64g6kexAIp202.
> ```

If you mean that you don't understand why none of those files have a file extension, it's possibly because the `ext_map` table only defines a limited set of mime types for which to add an extension.  You might check if a mime type is actually available in any of those instances, and if so, add an extension to the table.  If no mime types are actually available, it's because nothing was detected.  The only recourse then would be digging in deeper to see if there's any well-defined file format associated with those files and then teaching Bro about it via a signature file.

Also, since we generally just use GitHub for bug-and-feature tracking and not user support, you may get a wider range of feedback or faster answers by asking this kind of question on the mailing list:

http://mailman.icsi.berkeley.edu/mailman/listinfo/zeek

**Comment by JackLiar** [comment]
Thx for ur reply.

I used the pcap file mentioned in the tutorial, so I believe it should contain 'Content-type' header in HTTP.

I did check the pcap file manually, and there are 'Content-type' headers in HTTP. So I think there should be extensions after http filenames.

I'll try to use the mailing list, thx for ur advise :)

**Comment by jsiwek** [comment]
> If now we'r using fa_metadata to store mime_type and the f$mime_type is already abandoned, why do we still keep the mime_type filed in fa_file$info? For front forward capability? Just for curiosity

I think mostly just for logging purposes (it's following the standard convention/pattern used by many of the various log files Bro generates).  I.e. you see here it has the `&log` attribute:

https://github.com/zeek/zeek/blob/eb9a05cd25e46cec6710e1122fc4ff758b4ae2e3/scripts/base/frameworks/files/main.bro#L73

And then it is simply populated in pre-defined `file_sniff` event analyzer here:

https://github.com/zeek/zeek/blob/eb9a05cd25e46cec6710e1122fc4ff758b4ae2e3/scripts/base/frameworks/files/main.bro#L517

And the final logging is here:

https://github.com/zeek/zeek/blob/eb9a05cd25e46cec6710e1122fc4ff758b4ae2e3/scripts/base/frameworks/files/main.bro#L544

You can access it for your own purposes, too, but need to make sure you use it at a point in time after it gets populated.

Generally giving that entire script a read may be helpful to you -- maybe will find some useful functions  defined in its public API.
