### ISSUE TITLE
Normalize JSON keys when matching against record types from `from_json` BIF.

### ISSUE THREAD

**Issue by alilleybrinker** [zeek/zeek#3142]
Right now, the implementation of JSON deserialization for the new `from_json` BIF matches record types to JSON key-value pairs by iterating through the record fields and finding matching JSON keys. Unfortunately, this fails to correctly handle JSON record types with characters which are disallowed in Zeekscript record fields. A concrete example is trying to parse Manufacturer Usage Description files into Zeek using this new BIF; MUD includes fields with `-` and `:` in them, which can't currently be matched to Zeekscript record fields.

The solution would be to normalize JSON keys in some documented way, perhaps by 1) ignoring disallowed characters or 2) replacing disallowed characters with an underscore.

The relevant code is in the `TYPE_RECORD` branch of the `switch` on type tag in `BuildVal(const rapidjson::Value&, const TypePtr&)` in `zeek/src/Val.cc`. __[View code](https://github.com/zeek/zeek/blob/master/src/Val.cc#L1297-L1329)__

**Comment by timwoj** [comment]
> 2) replacing disallowed characters with an underscore.

We have existing code that already does things like this (thinking plugin names to normalized strings, replacing `::` with `_`). Those are only used internally, not as record fields, but If I had to pick, I'd say go that direction just for consistency.

**Comment by awelzel** [comment]
Or thread keys through a script-land callback/normalization. That will have more overhead, but probably okay and would allow special-casing certain keys or otherwise extend the normalization. Think camelCase to snake_case.

Other idea would be to put attributes on record fields similar to Go's struct tags that explain which fields they belong to, but that doesn't seem worth it.

**Comment by awelzel** [comment]
Following commit  would be the script-layer approach with a default normalization of:
```
+# Implement now that gsub() is declared.
+function from_json_default_key_mapper(s: string): string
+       {
+       return gsub(s, /[- :,.]/, "_");
+       }
+
```

https://github.com/zeek/zeek/commit/b84e841917252eb3476b8cb1b0868f355f4d3efc

**Comment by alilleybrinker** [comment]
Yeah that seems reasonable to me. My experience with this sort of auto-deserialization is from `serde` in Rust (specifically `serde-json`), which uses the "annotate `struct` fields with the name of the associated field in JSON" approach. It's maximally-flexible, but probably overkill in this context.

**Comment by awelzel** [comment]
Default pattern should better be the inverse `/[^a-zA-Z_0-9]/`.

Robin also suggested a fixed replacement. I'm still thinking a callback would provide a bit more flexibility so there's a way to to deal with unusual things:
```
{
  "1": "possibly not unusal",
  "1a": ["not nice", "not nice"],
  "": "{"": really?"}
}
```
The other idea `table[string] of any` support, but that's difficult.. :-/

**Comment by ckreibich** [comment]
Nice to see that you've started using this, @alilleybrinker! An example of the type of file Andrew is referring to is [here](https://www.rfc-editor.org/rfc/rfc8520#section-9).

Using attributes in Zeek [like `serde`](https://serde.rs/field-attrs.html) for this strikes me as too heavyweight. The callback seems fine to me. I actually considered supporting both tables and callback via a record argumentbut looking at the MUD example above, the table would have to be quite large if it needs to spell out whole strings, and if it would provide substrings a handful of `gsub()` calls strikes me as more concise. So I come out in favor of the callback.

I wouldn't provide a default mapping since it's not always needed and easily implemented when needed. The `from_json()` implementation could check whether the provided callback is a placeholder function (the `&default`) and only invoke when it's not.

The topic reminded me of the logging framework btw, though it doesn't have an exact equivalent:
- It has fixed separator/field presence strings
- `Log::default_field_name_map`, a `table[string] of string`, to rename log fields in a filter — easier scenario since it needs whole-string replacement
- `Log::default_ext_func`, a hairier concept that would be closer to deriving additional record fields on the fly — not something of interest here

**Comment by awelzel** [comment]
> An example of the type of file Andrew is referring to is [here](https://www.rfc-editor.org/rfc/rfc8520#section-9).

Thanks, that actually provides more examples of things that  fixed normalization doesn't address and that was missed in the initial implementation:

Reserved keywords in Zeek being used as keys. "tcp" and "port" below and in the full example there's also "type".
```
     "ace": [
               {
                 "name": "cl0-frdev",
                 "matches": {
                   "ipv6": {
                     "ietf-acldns:dst-dnsname": "test.example.com",
                     "protocol": 6
                   },
                   "tcp": {
                     "ietf-mud:direction-initiated": "from-device",
                     "destination-port": {
                       "operator": "eq",
                       "port": 443
                     }
                   }
                 },
                 "actions": {
                   "forwarding": "accept"
                 }
               }
             ]
```

> I wouldn't provide a default mapping since it's not always needed and easily implemented when needed. The from_json() implementation could check whether the provided callback is a placeholder function (the &default) and only invoke when it's not.

That makes sense. Will rework.

**Comment by awelzel** [comment]
Hey @alilleybrinker - #3149 has been merged. `from_json()` no has an optional callback to normalize key names. By default, no normalization happens.

I used the mud example to build a test case and ran into the case of reserved "type" and "port" keywords, too. You may take a use the callback shown there as a starting point, but possibly need more adaption.

https://github.com/zeek/zeek/blob/98626543651fbd298c90f240342c42fee63b0e3e/testing/btest/bifs/from_json.zeek#L232
