### ISSUE TITLE
out_of_bound ASN1EncodingMeta: more_len 129 > 26 for GSSAPI analyzer

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#3144]
This has recently been reported on the public [Zeek Slack channel](https://zeekorg.slack.com/archives/CSZBXF6TH/p1687245878023269)
> Goodmorning. What is the reason that i have a lot of binpac exceptions: out_of_bound ASN1EncodingMeta: more_len 129 > 26 for GSSAPI analyzer... Is something i can do to stop it in dpd.log? Thanks

And then a day later privately reported as well. The private report comes with a pcap, but unfortunately can't be shared publicly.

Initial skimming in the parser around `more_len` hints at the fact that we do not support "high tag number" form and possibly that causes parsing to fail.

https://github.com/zeek/zeek/blob/46715dacfd2f955739d3bf4010c74fbf827ad946/src/analyzer/protocol/asn1/asn1.pac#L31-L33

http://luca.ntop.org/Teaching/Appunti/asn1.html

**Comment by Mohan-Dhawan** [comment]
I might be entirely off the mark here as I do not know the whole issue. In my interactions with the ASN1 binpac parser, I found that several analyzer violations happened because GSSAPI did not handle the WRAP and MIC tokens (https://www.rfc-editor.org/rfc/rfc4121.html#section-4.2.6.1. The built-in analyzer only analyzes the NEG token. In my experiments, whenever there was a payload for either WRAP/MIC tokens, the analyzer threw violations.

**Comment by 0xxon** [comment]
Yup, you are indeed correct - this is a case where there are wrap/mic tokens present, which are missing the framing that is expected. From a short glance, it seems like it should not be hard to add support for these.
