### ISSUE TITLE
Repeated data streams in conn.log under live traffic

### ISSUE THREAD

**Issue by Brotherwang1** [zeek/zeek#3151]
Hi,  I find there are repeated quintuple data streams in conn.log and ssl.log when I monitor interface by zeek cluster using 25 lb_procs, the numer of flows recorded in conn.log and ssl.log is **conn:8727898,ssl:93025** respectively.

The configuration of node.cfg in this mode is：
[manager]
type=manager
host=127.0.0.1
[proxy-1]
type=proxy
host=127.0.0.1
[worker-1]
type=worker
host=127.0.0.1
interface=eno3
lb_method=pf_ring
lb_procs=25
pin_cpus=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24

But when I only use one lb_procs, the numer of flows recorded  in conn.log and ssl.log is :**conn:349080,ssl:3721** respectively. There will be no repeated quintuple data streams.

In the above two scenarios, I use tcpreplay to replay the same pcap file.

 Of course, I also use zeek to produces .log of this pcap file  offline the numer of flows recorded   in conn.log and ssl.log is :
**conn:371737,ssl:3715** respectively. 

I'm wondering why there is such a significant difference in the number of generated streams among these three modes. Additionally, why there are repeated quintuple data streams when I monitor interface by zeek cluster with25 lb_procs ? How can i solve this problem? Thanks.

**Comment by awelzel** [comment]
Hello @Brotherwang1 -

These questions are better suited for Slack or the Forum rather than GitHub - from the docs:

Join the Zeek community [Slack channel](https://zeek.org/slack/) or [forum](https://community.zeek.org/) for interacting with fellow Zeekers and Zeek core developers.

When you post there, please include information about the Zeek version and PF ring version as well as details about the network card and possibly hardware you're using.

That said, have you explored the `PFRINGClusterType` setting for zeekctl? Using one of the newer `inner-5-tuple` or `inner-6-tuple` options may improve the result. What you describe sounds like an issue with flow balancing. If you can, also providean example of the repeated conn.log entries - the history field and/or packet counts can be insightful to diagnose the issue.

Thanks,
   Arne
