### ISSUE TITLE
Appending to vector of any with += crashes: Val::CONVERTER (record/vector)

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#3191]
This appears to have started with Zeek 5.0 and no one complained so far, so marking low priority. Zeek 4.2 doesn't abort on this.

```
# crash2.zeek
type R: record { r: string &default="r"; };
type S: record { s: string &default="s"; };

# any queue
global q: vector of any;

function keep_this(r: any) {
        q += r;  # this crashes since Zeek 5.0
        q[|q|] = r;  # this is fine.
}

event zeek_init()
        {
        keep_this(R());
        keep_this(S());
        print q;
        }

$ zeek crash2.zeek 
fatal error in <no location>: Val::CONVERTER (record/vector) ([r=r])
Aborted (core dumped)
```

**Comment by vpax** [comment]
I have a hunch what's causing this, and if right then it's from a change I introduced, so I'm game to take a look.  That said, if you or someone else would like to, fine by me!

**Comment by timwoj** [comment]
Changing it to `q += [r]` works as well. `BinaryExpr::Fold` is expecting the RHS of the expression to be a vector if the LHS is one, and the error you're seeing is thrown when it fails to convert the RHS object to a vector.

**Comment by vpax** [comment]
I looked into this and it turns out that the core problem is an ambiguity. If `x` is a vector of `T` elements, then `x += y` is add-a-single-element if `y` has type `T`, and add-every-element if `y` has type `vector of T`. In the example above, `r` is of type `any`, so at run-time it could be _either_ a single element of type `T`, _or_ a `vector of T` that should be added element by element. (Or it could be the wrong type, period, leading to a run-time error.) The bug arises because in one context it's interpreted as a single element, and in another it's (incorrectly) assumed to be vector.

It's easy enough to fix this with some dynamic checking ... but it gives me pause to have a single statement that has somewhat varying semantics depending on what argument is passed to the function, as there are (perhaps quite unlikely) logic errors that this could mask. So I think my druthers would be to treat `x += y` for `y` of type `any` as requiring that `y` has (at run-time) a concrete type of `T`, and it'd be an error if it has the type `vector of T`, since I think the latter is surprising when one reads the statement. (If the developer wants the latter then they should declare `y` to have type `vector of any` to guarantee that it's a vector.)

That said, this isn't near-and-dear to my heart, I just want to know the best way to fix it :-).

**Comment by awelzel** [comment]
> I looked into this and it turns out that the core problem is an ambiguity. 

It seems Zeek 4.2 didn't have this - it just err'd out rather than doing the `add-every-element`.
```
$ zeek x.zeek 
error in ./x.zeek, line 4: appending non-arithmetic to arithmetic vector (v += vector(1))
```
And that appears quite reasonable - the implicit `add-every-element` opens the door for non-intended behavior and feels a bit too magic.

> I think my druthers would be to treat x += y for y of type any as requiring that y has (at run-time) a concrete type of T, and it'd be an error if it has the type vector of T, since I think the latter is surprising when one reads the statement.

What if `T` is `any` - looking at it from the other side: If LHS is `vector of any` the `add-every-element` of RHS gets into the way -  4.2 seems to do what one would expect instead:
```
# Regression 3191
global v: vector of any;

v += 1;
v += vector(2, 3);

print "v", v;
print "v", |v|, type_name(v[0]), type_name(v[1]);
---
4.2:
v, [1, [2, 3]]
v, 2, count, vector of count  # expected: mixed types in vector of any, you get what you asked for

5.0:
v, [1, 2, 3]
v, 3, count, count
```

Could we go back to the 4.2 behavior, removing/forbidding the `add-every-element` feature? This would be a breaking change with 5.0 and 6.0 behaving like that, but not sure I'd feel so bad if someone runs into it.

**Comment by vpax** [comment]
I'm not a fan of reverting to the 4.2 behavior. It would be introducing a conceptual incompatibility in what sort of operations container types support, just to address what I see as a corner-case.

I'm thinking we could proceed as follows. The semantics of `+=` are determined once, at compile-time, based on the types of the operands. The `add-every-element` semantics are provided if-and-only-if the RHS is, at compile-time, explicitly some sort of `vector of T` for which the LHS accepts values of type `T` as elements. If the RHS is of type `any`, then that fails the test and it's appended as a single element (which at run-time needs to be compatible with the type of the LHS vector). If the script writer really needs that RHS value to be treated as `add-every-element` then they either need to ensure the typing supports that, or at run-time use a type-switch or employ a `for` loop to add the elements.

**Comment by awelzel** [comment]
> I'm not a fan of reverting to the 4.2 behavior. It would be introducing a conceptual incompatibility in what sort of operations container types support, just to address what I see as a corner-case.

Yep, understood. I got hung up on the fact how we document vector's `+=` as `v[|v|] = e` in the vector's type section and the `add-every-element` didn't occur to me as something that should be allowed. I agree it's a special case.
