### ISSUE TITLE
Support for configurable localversion part in Zeek's version

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek#3224]
For distributors, appending an additional version string to Zeek's version can be useful to track any custom patches applied or other build/tree specific information.

Currently, to include additional information into the output of `zeek --version` a custom patch or `sed` in the build process is required.

Idea would be:
```
$./configure --localversion="myversion+4"
...
$ zeek --version
zeek version 6.0.0-myversion+4
```

**Comment by ckreibich** [comment]
Originalism vs pragmatism? :-)

> you cannot modify Zeek in any way while still calling it Zeek

There's also the flip-side, which is that you have to call it something else if you do modify it. Seems to me that the proposal provides a good compromise: it makes it clear that a modification is present, but implies that it's one that remains essentially Zeek. I also see the practical utility — I'd likely use this at times during development.

A potential alternative might be to add content in the `zeek -V` output. Not sure that's better because it's less visible, but the field naming could imply the use case (perhaps via a section like `distributor-metadata`). 

How would this get along with existing modifications, like `zeek version 6.1.0-dev.8-debug`? Just append?

**Comment by ckreibich** [comment]
I'm putting this on the agenda for the LT call this coming Thursday, just to make sure. My take is to put it in the version string and simply dash-append to whatever else is already there.

**Comment by ckreibich** [comment]
> My take is to put it in the version string and simply dash-append to whatever else is already there.

We're good to go with this approach.

**Comment by ckreibich** [comment]
This originally came in via @pbcullen — Peter, if this is still pressing for you, is this something you could see contributing?

**Comment by pbcullen** [comment]
I'm finally starting to look at this. If a localversion is supplied, I'm thinking ZEEK_VERSION_FULL in CMakeLists.txt should reflect that, but wondering if that might break something? It would affect the VERSION_C_IDENT value.  Also, should ZEEK_VERSION_NUMBER in CMakeLists.txt differ from that calculated using the major, minor, patch values? Maybe something like add 1000000 to it?

**Comment by ckreibich** [comment]
This is pretty subtle ... thanks for checking first. I don't think we should change `ZEEK_VERSION_FULL`, because it only captures version information right now (directly based on the `VERSION` file in the source tree). Our handling of debug builds looks close to what we'd like: the `zeek_version()` function manually adds `-debug` to the returned string that gets shown to the user, and cmake adds it to `VERSION_C_IDENT`, which means it ends up in the internal string identifying the Zeek build a plugin gets compiled for.

It seems to me we could do the same for this local version handling, since you'll want the output via `zeek --version`, and you likely want to disallow such localversion Zeek builds to successfully load plugins built for the same upstream version, but not for that localversion.

That leaves the exact output given the main version, development version, debug build, plus this — how about `6.2.0-dev.543-localversion-debug`? That means the prefix would still remain the same regardless of whether you're making a debug build or not.

**Comment by pbcullen** [comment]
VERSION_C_IDENT in the toplevel CMakeLists.txt can be updated with the localversion value. But, I see that ZEEK_VERSION_FULL is used in a couple places to display the zeek version (src/version.c.in, cmake_template/zeek-version.h.in, cmake_templates/zeek-config.in). Are you thinking that those template files should be modified to use a different cmake variable that contains the localversion value? If not, how would the localversion value get into the zeek_version() function?

**Comment by ckreibich** [comment]
Yeah, tracking it via a separate variable into cmake strikes me as the right approach. You'd keep the freedom to include it where needed, without affecting existing code.  If you look at [`zeek_version()`](https://github.com/zeek/zeek/blob/master/src/zeek-setup.cc#L227-L241), you see it folds in the `-debug` manually, and I was thinking you could do the same with such a variable here too. Similarly for `VERSION_C_IDENT` [here](https://github.com/zeek/zeek/blob/master/CMakeLists.txt#L576-L577). On the other hand, it doesn't look like it would need to affect anything in `cmake_templates/zeek-version.h.in`.

You could give it a go that way and see if you hit any hiccups ... it hopefully won't be too much work?
