### ISSUE TITLE
Conn.log: Originator and Responder IPs/ports Not Flipping for Logged Responder Packets

### ISSUE THREAD

**Issue by HiepTon** [zeek/zeek#3235]
### Capture wrong direction of communication

**To reproduce**
Version of zeek LTS: 5.0.9

Just run the pcap file enip_255_trunc.pcapng in attachment. The output is conn.log (also attached).

**Expected behavior**
The broadcast messages should be from 192.168.1.105 not from 255.255.255.255
[conn.log](https://github.com/zeek/zeek/files/12357398/conn.log)

This issue is resolved for icsnpp-enip plugin (https://github.com/cisagov/icsnpp-enip#source-and-destination-fields). 
[conn_Issue.zip](https://github.com/zeek/zeek/files/12357406/conn_Issue.zip)

**Comment by awelzel** [comment]
Hello @HiepTon - thanks!


Both conn.log samples you provide (in the attached .zip and the directly linked conn.log) have the following content - that is `255.255.255.255 -> 192.168.1.105` appears wrong and you can also see a `^` in the connection history indicating the direction was flipped.
```
1691381600.441783       CdxjfH1uzNCQdnY496      255.255.255.255 54412   192.168.1.105   44818   udp     enip    0.000227        0       1562    SHR     -       -       0       ^d      0       0       22      2178    -       ff:ff:ff:ff:ff:ff      00:18:23:12:39:19
```

When running the [enip_255_trunc.pcapng.gz](https://github.com/zeek/zeek/files/12367124/enip_255_trunc.pcapng.gz) from the  zip through a vanilla Zeek 5.0.9 without icsnpp-enip, the following conn.log is produced is instead as expected.
```
1691381600.441783       ChPBboLr9ygzyxJa3       192.168.1.105   44818   255.255.255.255 54412   udp     -       0.000227        1562    0       S0      -       -       0       D       22      2178    0       0       -
```

> The broadcast messages should be from 192.168.1.105 not from 255.255.255.255

After installing icsnpp-enip the connection is flipped. The culprit is registration of `44818/udp` into `likely_server_ports` in that package combined with Zeek's connection flipping logic.


The minimal reproducer would be as follows, no need to have the ENIP analyzer:
```
$ zeek -r enip_255_trunc.pcapng  'likely_server_ports += { 44818/udp }'
```

Appears reasonable not to flip a connection if the destination IP is a broadcast address as in the given pcap. Doesn't appear far fetched that some server software sends out broadcasts packets with a source port it's also listening on. Anything I'm missing?

@timwoj - thoughts? This one is somewhat direct, but the existing `WantConnection()` have access to src/dst addresses anymore and not clear to me we'd ever need to special case.
```
--- a/src/packet_analysis/protocol/ip/IPBasedAnalyzer.cc
+++ b/src/packet_analysis/protocol/ip/IPBasedAnalyzer.cc
@@ -171,7 +171,7 @@ zeek::Connection* IPBasedAnalyzer::NewConn(const ConnTuple* id, const detail::Co
                                          pkt->ip_hdr->FlowLabel(), pkt);
        conn->SetTransport(transport);
 
-       if ( flip )
+       if ( flip && ! id->dst_addr.IsBroadcast() )
                conn->FlipRoles();

```

**Comment by 0xxon** [comment]
That change looks ok to me.
