### ISSUE TITLE
Regression: CMake doesn't pass along third-party package information for plugin builds

### ISSUE THREAD

**Issue by timwoj** [zeek/zeek#3247]
This is a regression for the 6.0 release. Previous Zeek releases created a set of cached variables for use by ZeekPluginDynamic.cmake to pass along information about third-party packages like OpenSSL when building external plugins. This was lost during the CMake overhaul apparently, and some packages no longer build. The easiest one to test with is https://github.com/zeek/zeek-more-hashes. It attempts to include OpaqueVal.h which requires access to the openssl headers, and those include paths are missing during the build.

https://github.com/zeek/cmake/blob/7b722ce58c9d0fa82bc84c654487c8020aea148f/ZeekPluginDynamic.cmake#L22-L73 is the block of CMake in the 5.0 release that's missing from 6.0.

**Comment by 0xxon** [comment]
This actually brings up an interesting point. We probably should have some kind of way to easily test if a couple of frequently used packages still build against the current master.

With this release especially we had a couple that we broke - and this seems like something that we can avoid.

**Comment by awelzel** [comment]
> We probably should have some kind of way to easily test if a couple of frequently used packages still build against the current master.

No disagreement :-)

The twist here is a bit that this is found by OSX users. `zeek-more-hashes` actually has a CI setup that runs nightly and it's all green and happy, but just cause default work out.

This is mostly to emphasize that the regression job would be useful across linux,osx,freebsd. The other twist I think is that this might work when building plugins against a source/build tree instead of an install tree.

**Comment by Neverlord** [comment]
> https://github.com/zeek/cmake/blob/7b722ce58c9d0fa82bc84c654487c8020aea148f/ZeekPluginDynamic.cmake#L22-L73 is the block of CMake in the 5.0 release that's missing from 6.0.

The forwarding for the paths moved to `ZeekPluginConfig.cmake`:
https://github.com/zeek/zeek/blob/master/src/ZeekPluginConfig.cmake.in#L34.

When building the plugin, I can see that CMake is finding OpenSSL:

```
$ ./configure --zeek-dist=$ZEEK_SRC
(...)
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/local/opt/openssl@3/lib/libcrypto.dylib (found version "3.1.2")  
(...)
```

Running `make` fails with the mentioned error:

```
fatal error: 'openssl/md5.h' file not found
#include <openssl/md5.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

After looking at the CMake targets, it seems like we simply don't forward OpenSSL as a dependency. It works for me when applying this patch to Zeek's CMakeLists.txt:

```diff
$ git diff CMakeLists.txt
diff --git a/CMakeLists.txt b/CMakeLists.txt
index aeaa15a17..402cd3d16 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -291,6 +291,7 @@ target_include_directories(
     zeek_dynamic_plugin_base
     INTERFACE $<INSTALL_INTERFACE:include> $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>
               $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/src>)
+target_link_libraries(zeek_dynamic_plugin_base INTERFACE OpenSSL::SSL OpenSSL::Crypto)
 add_library(Zeek::DynamicPluginBase ALIAS zeek_dynamic_plugin_base)
 set_target_properties(zeek_dynamic_plugin_base PROPERTIES EXPORT_NAME DynamicPluginBase)
 install(TARGETS zeek_dynamic_plugin_base EXPORT ZeekTargets)
```

Looking at the generated `ZeekConfig.cmake` on my system: the other dependencies are libpcap, zlib and c-ares. Do we have public Zeek headers that depend on them as well? Do we need to have target-level dependencies for them as well? The setup for these libs would probably not as straightforward because we bundle them in some configurations.

> We probably should have some kind of way to easily test if a couple of frequently used packages still build against the current master.

I couldn't agree more. I'd only add that automating these checks would be even better. 🙂

I don't think we need this on a per-commit check in our CI, but some form of regularly running pipeline would be awesome. Something like a nightly build on the main branch.

**Comment by awelzel** [comment]
> The forwarding for the paths moved to ZeekPluginConfig.cmake:

This file isn't available in an install tree, AFAICT, so suspect that's not working without a source/build tree:

```
$ cd /opt/zeek-6.0-release/
$ find . -name ZeekPluginConfig.cmake
```


> $ ./configure --zeek-dist=$ZEEK_SRC

This isn't a work-flow used normally: Does this still work you when you build the plugin against an install tree without a source/build tree available? My understanding was that for the installed tree there's this separate `ZeekPluginBootstrap.cmake` file.

Basically, this from my prior comment:

> The other twist I think is that this might work when building plugins against a source/build tree instead of an install tree.

---

> Looking at the generated ZeekConfig.cmake on my system: the other dependencies are libpcap, zlib and c-ares. Do we have public Zeek headers that depend on them as well?

Poor man grep in the install tree:
```
OpaqueVal.h:#include <openssl/md5.h>
File.h:#include <krb5.h>    #  I think this is left-over from when OpenSSL required krb5, will open a PR
iosource/pcap/Dumper.h:#include <pcap.h>
<...> more pcap.h
digest.h:#include <openssl/evp.h>
digest.h:#include <openssl/md5.h>
digest.h:#include <openssl/sha.h>
file_analysis/analyzer/x509/OCSP.h:#include <openssl/ocsp.h>
file_analysis/analyzer/x509/X509Common.h:#include <openssl/asn1.h>
file_analysis/analyzer/x509/X509Common.h:#include <openssl/x509.h>
threading/formatters/JSON.h:#include <rapidjson/document.h>  # Have extra logic, but will be gone from public headers with 7.1
threading/formatters/JSON.h:#include <rapidjson/writer.h>
zeek-config.h:    #include <sanitizer/lsan_interface.h>
util.h:#include <gperftools/heap-checker.h>  # conditional?
util.h:#include <gperftools/heap-profiler.h>
util.h:#include <pthread.h>
util.h:#include <pthread_np.h>
util.h:#include <pthread.h>
logging/writers/ascii/Ascii.h:#include <zlib.h>       # could possibly forward declare / hide
analyzer/protocol/krb/KRB.h:#include <krb5.h>
analyzer/protocol/zip/ZIP.h:#include <zlib.h>
analyzer/protocol/mime/MIME.h:#include <openssl/evp.h>
```

So pthread, zlib, krb, openssl, libpcap. None of which we bundle AFAIK, not sure pthread needs special handling. c-ares is hidden in the DNS_Mgr implementation.

openssl, libpcap are the likely candidates to hit. Maybe zlib, KRB somewhat unlikely.

**Comment by Neverlord** [comment]
> > $ ./configure --zeek-dist=$ZEEK_SRC
> 
> This isn't a workflow used normally: Does this still work you when you build the plugin against an install tree without a source/build tree available? My understanding was that for the installed tree there's this separate `ZeekPluginBootstrap.cmake` file.

Correct, sorry for leaving this out. The "default" method via `zeek-config` in the path worked for me as well.

It seems like we don't actually need the link-time dependency. I played a bit around with it and I'm working on a patch in the branch `topic/neverlord/gh-3247`.

**Comment by ckreibich** [comment]
> $ ./configure --zeek-dist=$ZEEK_SRC

This still comes up regularly enough that I wonder whether we should more strongly discourage people from using it, perhaps similar to how we pushed CAF/Broker configs out of `configure` and into `cmake` a while back. The only use case for it that I'm aware of is for people who don't install their built Zeek trees — right? No regular user or package installer should have a need for it.

>  We probably should have some kind of way to easily test if a couple of frequently used packages still build against the current master.

Arne proposed this a good while back and I like it too — iirc I was concerned back then that we're plumbing external dependencies too tightly into our CI, since it's common that packages don't get maintained long-term. But I like it as an early warning signal, and packages like `zeek-more-hashes` (that we maintain!)  would certainly good contenders.

I'm contrasting this against bulk-testing against the package source, which recently came up in a different context — I think that's too tricky for various technical reasons (discerning bitrot from problems on our side, external dependencies for plugins, etc).

**Comment by Neverlord** [comment]
> The only use case for it that I'm aware of is for people who don't install their built Zeek trees — right? No regular user or package installer should have a need for it.

Even then, you can always "install" Zeek into a userspace directory. So unless there's a strong incentive to keep this feature: removing it would make the CMake scaffolding a lot simpler since we no longer would have to maintain two separate modes for building plugins. The entire `ZeekPluginBootstrap.cmake`-thingy would just go away. 🙂

**Comment by ckreibich** [comment]
> Even then, you can always "install" Zeek into a userspace directory.

True, that's what I always do, too. I wouldn't actually remove it, though — I know that we have folks who rely on it for their local development routine. I just think that once you touch plugin development you really are better off with an installed tree, since that's how your plugin will be used by the rest of the world.

**Comment by timwoj** [comment]
I tested the linked PR above against the `zeek-more-hashes` plugin and it looks like it fixes the issue.

**Comment by timwoj** [comment]
> Yeah, but it somehow ended up pulling in an include path where our VERSION file is. This breaks on macOS since STD headers to #include <version> (which breaks because of case-insensitive FS). If the latest commit doesn't fix the build on macOS, I need to dig deeper into it. It doesn't happen locally on my Mac.

I was wondering why that was failing. It doesn't happen here locally either. Looks like it passed this time around on Cirrus though.

**Comment by Neverlord** [comment]
> I was wondering why that was failing. It doesn't happen here locally either. Looks like it passed this time around on Cirrus though.

Passing CI, but back to the include error when building the plugin. Back to the drawing board...

**Comment by Neverlord** [comment]
> > I was wondering why that was failing. It doesn't happen here locally either. Looks like it passed this time around on Cirrus though.
> 
> Passing CI, but back to the include error when building the plugin. Back to the drawing board...

Scratch that, messed up the build. Seems to work with f60a208b8d6dacbb8d1cba29d2de0e190c4f55de. Both methods: using `zeek-config` in `PATH` or when using `--zeek-dist=`.

@timwoj was this the commit you've been using as well?

**Comment by timwoj** [comment]
I was using 80846a797127e4c8be62ca7fe0c4707856927a30, which was the first PR version. I'll test again with the latest.

**Comment by timwoj** [comment]
This should be fixed now so I'm closing this
