### ISSUE TITLE
Zeek extract eml file from SMTP protocol network traffic problem when Zeek listen network interface

### ISSUE THREAD

**Issue by HackerYunen** [zeek/zeek#3272]
Hi, I am a noob about zeek, and I had found so long but nothing can help. 
I write a zeek script to extract eml file from SMTP protocol network traffic, here is my zeek script content:
```
@load base/protocols/smtp

event smtp_data(c: connection, is_orig: bool, data: string) {
    local f = open_for_append(fmt("%s.eml", c$uid));
    print f, data;
    close(f);
}
```
I use this zeek script extract eml file successfully from pcap which is dump by `tcpdump`, here is my command:
```
zeek -r example.pcap -C smtp.zeek
``` 

But when I try to listen network traffic interface directly, it was not working very well. An email which contains a attachment file encode by base64 was catch, but the eml file is not full content, lots of  content were lost. Here are my command:

```
zeek -i eth0 -C smtp.zeek
```

This problem is not repreat in pcap, they are the same attachment email, it work so pretty.

Can anyone help me please?  :(

**Comment by awelzel** [comment]
Hello @HackerYunen ,

These questions are better suited for Slack or the Forum rather than GitHub - from the docs:

Join the Zeek community [Slack channel](https://zeek.org/slack/) or [forum](https://community.zeek.org/) for interacting with fellow Zeekers and Zeek core developers.

When you post your question there, please attach information about your Zeek version, the pcap and the `conn.log` output for the given connection when reading live traffic. Thanks, Arne.
