### ISSUE TITLE
Get the input stream

### ISSUE THREAD

**Issue by lzkking** [zeek/zeek#3283]
After I set a backtrack point using input, I noticed that the data after that backtrack point is not being released, causing memory to infinitely expand. My input stream is obtained through an EVT file. I want to access the name of this stream in Spicy so that I can use trim to release memory before the backtrack point obtained using input. How can I obtain this input stream, and are there any functions available to retrieve this stream for using trim on it?

**Comment by bbannier** [comment]
Backtracking in Spicy is a tool allowing developers to parse the same input data again with a different route. For that it jumps to the field after the most recent `&try` field (i.e., a field for which parsing was already invoked). Since this approach still needs the data for another parse attempt, it cannot and should not be trimmed yet.

> My input stream is obtained through an EVT file.
It is unclear to me what you mean here.

If this still does not clear things up for you, feel free to open a new topic in our [Discourse](https://community.zeek.org/) where we provide support. If possible, please include small sample code and inputs showing what you have, what you see, and what you would have expected instead.
