### ISSUE TITLE
extract_ip_addresses can return IPv6 addresses that to_addr doesn't like

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#340]
The script fragment `print to_addr(extract_ip_addresses("IPv6:1:2::3:4:5:6:7")[0]);` generates a low-level run-time error, `error: Bad IP address: 6:1:2::3:4:5:6:7`.  A related problem is that `extract_ip_addresses` will return nine octets if given `"IPv6:1:2::3:4:5:6:7:8"` instead.

This causes problems in the SMTP analyzer, which inspects addresses extracted from headers.

**Comment by jsiwek** [comment]
To clarify: the bug to fix is that `extract_ip_addresses` does not do sufficient extraction/validation on its own such that its return values are in fact valid IP (v4/v6) addresses ?

The error message from `to_addr` seems legit, and it returns `::` if it fails to convert, so seems one can always do their own validity check.  Though can see an improvement in providing an `is_addr` function that wouldn't emit an error or else an argument/flag for `to_addr` to suppress error messages.  What do you think/need ?

**Comment by jsiwek** [comment]
> First, I haven't looked into whether a bare `::` (one that doesn't match any octets) is legal in an IPv6 address. If so, then in my first example, `to_addr` is at fault; if not, then `extract_ip_addresses` is at fault

It's legal: used to represent a sequence of all-zero-bits.  Called "Zero Compression":

>      'A special syntax is available to compress the zeros.  The use of  "::" indicates one or more groups of 16 bits of zeros.'

>       'The "::" can only appear once in an address.'

But the problem is that the extraction from `""IPv6:1:2::3:4:5:6:7`" associates the leading `6` with the address and so `6:1:2::3:4:5:6:7` has the full 8 hextets already, making the `::` in there is not valid since it can't expand any further.

**Comment by vpax** [comment]
Yeah I know that use of `::`, what I was wondering is whether the standard says it matches one-or-more Zero Hextets, or zero-or-more (which would make the first example legal, and thus `to_addr` at fault).

**Comment by jsiwek** [comment]
Oh sorry, I misread, then just to clarify: I meant that `to_addr` is not the thing at fault here since `::` does have to match one-or-more zero-hextets.

`to_addr` is internally going through `inet_pton` which is a fairly canonical way to check validity and do conversion, so `extract_ip_addresses` and `is_valid_ip` all being implemented purely in script-layer via regex matching is what needs improvement.

**Comment by vpax** [comment]
Cool, sounds like we're in sync.  I hadn't realized they were implemented at the script layer, though I did see some baroque regular expressions in the docs, which I guess are what they rely on.  So yeah, those are what need fixing.

**Comment by alsmith** [comment]
Sorry to be a pain but while this seems to solve the error, it's still prone to misparsing, especially in the context of Received: headers (xref SMTP parsing):

![image](https://user-images.githubusercontent.com/6310490/121216030-d0d63380-c880-11eb-8b90-7cce0ef21ec8.png)
