### ISSUE TITLE
http dpd sigs don't trigger for large requests

### ISSUE THREAD

**Issue by JustinAzoff** [zeek/zeek#343]
Attached is a pcap where the client sends a 1500byte or so http request to the server

[http_large_req_8001.zip](https://github.com/zeek/zeek/files/3108857/http_large_req_8001.zip)

even though the request starts with "GET" and the response starts with "HTTP " the dpd signature doesn't match because the client request exceeds the default dpd_buffer_size of 1024 bytes.  Only 5 bytes from each flow should have been needed to identify this as HTTP.

**Comment by jsiwek** [comment]
> Only 5 bytes from each flow should have been needed to identify this as HTTP.

If you're requiring a match from *both* directions to identify it as HTTP, then it's more like you need 5 bytes from resp, but an arbitrary number of bytes from orig because we need to buffer everything orig sends for replaying into the analyzer that gets instantiated whenever the match finally occurs.

Is the idea here to change to default `dpd.sig` for HTTP so that it has no `requires-reverse-signature` dependency and just enables HTTP analysis on matching either orig or resp signature, but not necessarily both ?

Otherwise, seems it's a question of tuning the `dpd_buffer_size` -- either leaving it up to each site to do that, or upping our default if there's good reason to think it's deficient for a lot of users.

(I did take a peek into DPD matching code/logic and didn't notice any obvious bugs there -- I generally could make sense of it, and still seems like it's the way things should be done generally, but possible I'm overlooking a better solution)

**Comment by JustinAzoff** [comment]
yeah, I wonder if http sigs should be relaxed in cases where the client is obviously HTTP.. like maybe not 100% confirmed as http, but attach the analyzer earlier to see what it does

**Comment by JustinAzoff** [comment]
I've since seen this on two more cases:

A powershell HTTP request on port 4615 with a 4k `Authorization: Kerberos ....` header

An apache struts exploit

**Comment by rsmmr** [comment]
We agreed that for now we'll create a package that makes the relevant changes more before merging into a release. That way we get more exposure first to see if it causes trouble anywhere. If it works well, we'll merge into 3.1

Things to try in that package:

-  Add a uni-directional signature for HTTP.
- Increase DPD buffer size.

**Comment by JustinAzoff** [comment]
Experience over the past year has shown that increasing the dpd buffer size helps in many cases.  However, it does not help in all of them:

* Sometimes the http request is just larger than 4k or even 8k.
* Sometimes the http request is small, but there is no response.. possibly the server crashes or only half of the connection is seen.
* Sometimes only the response is seen.

The better fix appears to be to just split the requires-reverse-signature http sigs into two independent signatures.  This can be easily done in a package, but since the default sigs are still loaded there's a bit of a performance hit to run both of them.

I know this may cause some conn log entries to have service=http when the connection might have not been 100% http, but the current situation leads to completely missing http log entries, which is definitely worse.

**Comment by rsmmr** [comment]
So either signature would then trigger the analyzer?

I think I can see making this change, even thought I don't like it. :) (Don't like it because it breaks the assumption of requiring both endpoints to be seen speaking the protocol before adding the analyzer).

**Comment by JustinAzoff** [comment]
I have a pcap from some malware where the client exfiltrates some data via a POST over http, and the server responds by closing the connection.  Currently that does not show up in the http log at all due to that very assumption..
