### ISSUE TITLE
Update `Tunnel::max_depth` default to reflect modern encapsulation environments

### ISSUE THREAD

**Issue by ckreibich** [zeek/zeek#3439]
Per [discussion on Slack](https://zeekorg.slack.com/archives/CSZBXF6TH/p1699037435105629) our current default value of 2 is too low for modern environments, where a combo of VXLAN & Geneve is quite common. The `max_depth` variable defines the cutoff at which Zeek will stop decapsulating further.

We're looking for input on the number of lower-layer encapsulation levels that folks see in production to guide a choice of a new default — please chime in here if you can.

@awelzel, fyi.

**Comment by awelzel** [comment]
I've surveyed the logs of five non-cloudy production deployments and none had "exceeded_tunnel_max_depth" in the weird_stats for the past year. Neither @initconf nor @dopheide-esnet have reported seeing it.

On Slack, where this [first came up recently](https://zeekorg.slack.com/archives/CSZBXF6TH/p1699454716025919?thread_ts=1699039132.123169&cid=CSZBXF6TH), the user reported a value of 3 being sufficient for their needs.

> Sure, it is a multi account AWS environment using the VPC mirroring feature with an AWS load balancer to direct the traffic from multiple accounts.
> Yes, the weird logs were generated when using default settings.

> A value of 3 was sufficient to get past the layers of encapsulation.

Based on that, I'd vote 4 for now, but would certainly be good to hear if others see "exceeded_tunnel_max_depth" and have done something about.

---

I do wonder if a weird is the right messaging in general. A `x` or `_` or `?` in a tunnel's history for packets not fully decapsulated would make it directly visible in a popular field. Maybe.

**Comment by ckreibich** [comment]
I'm comfortable with a highly scientific choice of 4 based on your investigation. :-)

> A x or _ or ? in a tunnel's history for packets not fully decapsulated

As per our chat I like this a lot. I'd lean toward non-alphabet characters so the notion of upper/lowercase for directionality doesn't apply to them — so `?`, or perhaps `+`.

**Comment by multicast-bytes** [comment]
Great conversation. 
In uncomfortable from a network forensics standpoint, where packets are on the network and analysis/recording is missed due to parameters such as these. 

Thus, I like the idea of using history to inform users that tunnel depth limit(s) where reached.

Indeed, I hit this issue myself whilst working in AWS where using their native AWS Traffic Mirroring via a AWS GWLB resulted in packets 3x encapsulated so to speak.

In pursuit of my own investigation, using scapy I built this pcap.. a dns lookup 3x encapsulated which should trigger weird when today's `max_depth` = 2 is used.

[vxlan-triple-v2.pcap.zip](https://github.com/zeek/zeek/files/13367086/vxlan-triple-v2.pcap.zip)
