### ISSUE TITLE
Log file gzip enhancement idea

### ISSUE THREAD

**Issue by schenksj** [zeek/zeek#360]
I'm curious of the communities opinion on the idea of providing the option to writing log files out already gzipped rather than scheduling gzip's when we rotate.  This would help keep utilization as flat as possible, especially on heavily loaded machines?  Happy to help with a contribution if there is appetite.

**Comment by sethhall** [comment]
This is already implemented in zeek, but not exposed through broctl (zeekctl!).  It's controlled through the LogAscii::gzip_level variable and you can enable compression with `redef LogAscii::gzip_level=7;`.

I'm going to leave the ticket open since the capability of dealing with compressed logs is not fully exposed in all tooling yet.

**Comment by timwoj** [comment]
This is now available in zeekctl as the `CompressLogsInFlight` option.
