### ISSUE TITLE
Referencing an index of a sorted vector

### ISSUE THREAD

**Issue by anthonykasza** [zeek/zeek#365]
For some reason scriptland raises an error when I try to index a sorted vector. See the following example script. 

```
event bro_init() {
  local v: vector of int = vector(-1, -10, 10, 1, 5, 0);
  local vo = sort(copy(v));

  print v;
  print vo;

  print |v|;
  print v[|v| - 1];

  print |vo|;
  # The following line raises an error
  print vo[|vo| -1];
}
```

I'm using version 2.6. I've tried calling sort as shown above as well as with my own comparison function.

**Comment by jsiwek** [comment]
>   local vo = sort(copy(v));

The return value of `sort` is an `any` type and the type of `vo` is also not explicitly declared, so it's just `any` from here out.

>   print vo[|vo| -1];

This emits the parse-time "not an index type" error because the type-checking has no idea what the type of `vo` is at that point.

To fix the error, I'd suggest just declaring the initial type like this:

>   local vo: vector of int = sort(copy(v));

Alternatively, you could keep the inferred type as `any` and use the `as` operator to type-cast at run-time:

>   print (vo as vector of int)[|vo| -1];

That's a bit tedious for this use-case, but it does show that we know the type at run-time and we *could* add more parse-time type-checking bypasses for the `any` type, but I don't think that's too desirable: could cascade and escalate into just changing into a dynamic language ...

But for purpose of closing this ticket, should we improve the error message?

Here's current error:

> error in ./test.bro, line 13: not an index type (vo[flattenvo - 1])

Would the following better help explain what's going on?

> error in ./test.bro, line 13: expression with type 'any' is not a valid index type (vo[flattenvo - 1])

Or any suggestions?

**Comment by anthonykasza** [comment]
Thank you, Jon! 

> error in ./test.bro, line 13: expression with type 'any' is not a valid index type (vo[flattenvo - 1])

This is a much more helpful error message. 

I assumed `sort()` would return whatever type was passed to it since it sorts in place. I should check my function return types more closely.
