### ISSUE TITLE
It is possible to have cryptographic algorithms inside Zeek?

### ISSUE THREAD

**Issue by Sun-Dordje** [zeek/zeek#367]
hello Zeek community,

I work on an analyzer for OPC UA.
I have a client and server to generate OPC UA trafic with the security policy basic128rsa15.
I have implement with python a script to decrypt what I catch.
When i run Zeek with my pcap files opcua_secure_channel.pcap

There is the first encrypted block that I catch from an OpenSecureChannelRequest and
the seconde block from the OpenSecureChannelResponse :

![blockencrypt](https://user-images.githubusercontent.com/48475339/57772413-a2271680-7715-11e9-8db2-7abbef09f2fb.png)

I put them into my script and i have the good decrypt message :

![blockdecrypt](https://user-images.githubusercontent.com/48475339/57772449-b66b1380-7715-11e9-9653-2c69112cdd11.png)

i underlined the type_id of the decrypted message and that corresponds with the correct type_id of an OpenSecureChannelRequest and OpenSecureChannelResponse.

So now i would like to decrypt the message just-in-time with Zeek, but i need a library like mbedtls (https://tls.mbed.org/) to have cryptographic algorithms.
It is possible to put a C library into Binpac Files/ script Zeek?

Or someone have an idea to how can i make it? Or How can i use cryptographic algorithms inside my zeek script or binpac analyzer?

Thank you
Sun-Dordje

**Comment by 0xxon** [comment]
Hi,

please note - since this is actually not a bug, but a question, one of our mailing lists is probably the better venue for this. Questions like this will also get seen by more people on the mailing list.

To answer your question - yes, it is possible to use libraries inside of Binpac code or in bif (built-in-function) files (which you use to create functions that are exposed in scriptland). You cannot directly call foreign c-code from scriptland without making the functionality available in a bif file first.

https://www.zeek.org/development/howtos/bif-doc/index.html gives an introduction of writing bifs - I assume that is what you would want to do. Zeek already uses OpenSSL internally to deal with certificates - you can look at that for some example code. Look at https://github.com/zeek/zeek/tree/master/src/file_analysis/analyzer/x509, specifically functions.bif

I hope this helps,
 Johanna
