### ISSUE TITLE
Notices::ignored_types causes manager to leak memory, rapidly

### ISSUE THREAD

**Issue by aeppert** [zeek/zeek#373]
Example: redef Notice::ignored_types += { Conn::Content_Gap };

The manager will continually consume memory until it crashes.

**Comment by jsiwek** [comment]
It seems unusual for just ignoring a notice type to cause that kind of behavior and I didn't immediately see any explanation.   Since your example included the `Conn::Content_Gap` notice: is it really the ignoring of that notice that causes a problem, or just the fact that that notice is being raised?

The ignoring of a notice happens on the manager node, not on the workers, so even with setting `redef Notice::ignored_types += { Conn::Content_Gap };`, you'll get increased load on the manager from having to process the remote events.  So wondering if underlying issue is from loading that `policy/protocols/conn/weirds` script which generates that notice.  As I'd expect and also as the script notes, it's not really mean for production deployments due to load issues.

**Comment by aeppert** [comment]
Fair. However, with the ignore in, the manager consumes 500GB of memory in minutes and dies. Without it does not. The weirds are generated either way.
