### ISSUE TITLE
`&default` on `table` in a `record` has strange behavior (errors and aborts)

### ISSUE THREAD

**Issue by ynadji** [zeek/zeek#3757]
This issue will refer to the following [https://try.zeek.org/#/tryzeek/saved/db54c31786484cc59bcc212a762515ad](try.zeek) snippet, as well as [https://zeekorg.slack.com/archives/CTGDG83B8/p1717065849548019](this thread on Slack).

I'd like to define a record with a table with a default function:

```ruby
type Foo: record {
freq: table[count] of count &default=function(m: count): count { return 0; };
};
```

This fails with `error in ./try.zeek, line 9: &default value has inconsistent type (&default=function(){ return (0)})`. Defining the function above doesn't help. @bbannier suspected it's an ambiguous parsing issue, so I tried `freq: table[count] of count &default=0;`, which causes an abort:

```
error in ./try.zeek, line 11: &default value has inconsistent type (&default=0)
internal error in ./try.zeek, line 13: type inconsistency in ZVal constructor
/usr/bin/timeout: the monitored command dumped core
Aborted
```

which seems bad! Let me know if I should split these into two issues.

**Comment by bbannier** [comment]
>  @bbannier suspected it's an ambiguous parsing issue, so I tried `freq: table[count] of count &default=0`

I am pretty sure that this is due to parsing where the `&default` on the field gets attached to the field value (which expects it to hold a default value), and not to the table (which expects a function key->value to compute default values).

Using a default value as suggested on Slack does indeed work around this,

```zeek
function foo(m: count): count
	{
	return m * 1000;
	}

global DEFAULT_FREQ: table[count] of count &default=foo;

type Foo: record {
	freq: table[count] of count &default=copy(DEFAULT_FREQ);
};

event zeek_init()
	{
	local f = Foo();
	f$freq[47] = 11;
    assert |DEFAULT_FREQ| == 0;
	}
```

* * *
> `error in ./try.zeek, line 11: &default value has inconsistent type (&default=0)`

This error message is correct as `0` is not a valid default value for a field of type `table[count] of count`; the real issue is that this aborts (but at least it emits an error message).

**Comment by vpax** [comment]
Regarding the abort, I can see where it's happening in the code, will add it to my monthly script optimization maintenance (even though it's just a scripting issue, not one in script optimization)

**Comment by vpax** [comment]
Closing per maintenance last month
