### ISSUE TITLE
Mismatch between `|...|` operator and what's returned for `enum`s and `port`s

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#3835]
The `|...|` operator [only allows for one of three possible yield types](https://github.com/zeek/zeek/blob/0ba80d13b49fc1d4603e67fc3b4807cc333376bc/src/Expr.cc#L1331-L1340), `any`, `double`, and `count`. However, [`port`](https://github.com/zeek/zeek/blob/0ba80d13b49fc1d4603e67fc3b4807cc333376bc/src/Val.cc#L597) and [`enum`](https://github.com/zeek/zeek/blob/0ba80d13b49fc1d4603e67fc3b4807cc333376bc/src/Val.cc#L3134) values return `int` types. That discrepancy causes the [attached program](https://github.com/user-attachments/files/16288493/size-count-val-discrepancy.zeek.txt) to crash with a low-level `ZVal` inconsistency error.

For `port` this is easy to fix because it really should be returning a `count` in all cases. However for `enum` it's not, because one of the `EnumType` constructors allows specifying a `zeek_int_t` value to associate with a new `enum` element. So probably the right fix here is to (1) make `port` return a `count`, and (2) extend `|...|` to recognize the `enum`s return `int`s.

---

```
type my_enum: enum {
	enum1
};

type Info: record {
	my_action: count &default = |enum1|;
} &redef;

event zeek_init()
        {
	local i: Info;
	print i$my_action;
        }
```

**Comment by awelzel** [comment]
Curious, I didn't realize `|...|` would work for ports or enums. There's `port_to_count()` and `enum_to_int()` and that's what we document in the type sections, too, and no mentioning of `|...|` - there are tests, though. For port it includes the port space mask, so not sure how useful that is without further masking.

https://docs.zeek.org/en/master/script-reference/types.html#enum
https://docs.zeek.org/en/master/script-reference/types.html#port

**Comment by evantypanski** [comment]
What instances make `EnumVal` have to be backed by an `int` and not an unsigned `int`? I'm having a lot of preliminary success just changing port/enum to return a count and making enum values backed by an `UnsignedValImplementation` [here](https://github.com/zeek/zeek/blob/2907d9feeec4c107f7b728ff16ba1107287bd285/src/Val.h#L1500), not `IntValImplementation`. Tests seem fine and I can only find instances of `EnumVal` getting created with a non-negative value, so I don't know whether that's just because there isn't much coverage for those cases or that they really never are created with a negative value. So are there any known instances of negative enum values?

I also know there are cases that an [`EnumType`'s counter can be negative](https://github.com/zeek/zeek/blob/2907d9feeec4c107f7b728ff16ba1107287bd285/src/Type.h#L870-L875) or [`enum_to_int` returns `-1`](https://github.com/zeek/zeek/blob/2907d9feeec4c107f7b728ff16ba1107287bd285/src/zeek.bif#L2536-L2540), but those seem unrelated to the actual enum's value being non-negative. Though if there's a size limitation to keep `enum_to_int` working then the underlying type can also just remain `int` but the returned type for the `|e|` operator return a count to remain consistent with other uses, since it (should?) [never be negative](https://github.com/zeek/zeek/blob/2907d9feeec4c107f7b728ff16ba1107287bd285/src/parse.y#L1144). At least not from any case I've been able to make. If you have `MAX_INT+1` cases maybe? :)

Though I very well may be missing some cases

**Comment by vpax** [comment]
In general, seems okay. Maybe a breaking change though because there's a code path from the public `EnumType::GetEnumVal()` method that allows constructing an instance with a negative value.
