### ISSUE TITLE
Missing parsed LDAP entry going from 7.0.0 to 7.0.1

### ISSUE THREAD

**Issue by martinvanhensbergen** [zeek/zeek#3919]
We have a pcap that produces ldap.log entries with diagnostic_messages filled about invalid credentials on Zeek 7.0.0:

![700](https://github.com/user-attachments/assets/256b5f07-d664-4b8e-bd03-2ee009ef2376)

However on Zeek 7.0.1 this pcap does not yield ldap.log entries:

![701](https://github.com/user-attachments/assets/a9025b50-5cbe-48db-8a5f-cf39fc568acf)

[ldap_invalid_credentials.pcap.txt](https://github.com/user-attachments/files/16905063/ldap_invalid_credentials.pcap.txt)

I wonder what could be the cause of this and which result is technically most correct :-)

**Comment by awelzel** [comment]
Okay, thanks @martinvanhensbergen . This is actually fixed in `master`, but we missed the following PR in 7.0.1:

https://github.com/zeek/zeek/pull/3854

@timwoj , I'm adding it to 7.0.2. That might actually be worth a quick follow-up :-(

@pbcullen - if 7.0.2 is far out, this is a cherry-pick candiate.

**Comment by timwoj** [comment]
We can turn around 7.0.2 next week if it's urgent.
