### ISSUE TITLE
The file size for uploading small files using the SMB protocol is sometimes recorded as 0

### ISSUE THREAD

**Issue by robinkou** [zeek/zeek#3977]
In the release version 7.0.3, it was found that the file size record in the smc_files log for uploading small files using the smb protocol was 0;
But the result was a successful upload;
And there are bytes in the seen_bytes in the files.

**Comment by 0xxon** [comment]
Issues like these are much easier for us to debug with a reproducer. Would it perhaps be possible to share a small example pcap of this issue?

**Comment by robinkou** [comment]
Here are the files used in the previous testing, hoping to help you
![files](https://github.com/user-attachments/assets/6ca2d3d6-a6a1-4463-bd74-c5f9751eb7a7)
![smb_files](https://github.com/user-attachments/assets/f80ed721-d871-4ee4-8b0b-7d44aa3ae656)
[smbtest.zip](https://github.com/user-attachments/files/17405524/smbtest.zip)

**Comment by awelzel** [comment]
Hey @robinkou - is this about the `smbrename.pcapng` upload in the provided traffic? At the time the `FILE_OPEN` entry is logged in `smb_files.log`, the file's size was `0` / non-existing, then the upload happened.

The CloseResponse of Frame 3841 in the provided PCAP contains the size as, so a `FILE_CLOSE` entry in `smb_files.log` could show the correct size. Would that be sufficient?

We don't currently handle `smb2_close_response()` though, only `smb2_close_request()`, so that would need extending.

![Screenshot from 2024-10-22 15-32-31](https://github.com/user-attachments/assets/64321730-9d45-470f-8fbc-66aa243c4ad4)

---

There's also frame 2560 which uses a SetInfo Request with SMB2_FILE_ENDOFFILE_INFO to allocate the file, so could leverage `smb2_file_endoffile` to determine that, too.

![Screenshot from 2024-10-22 15-40-28](https://github.com/user-attachments/assets/dffbc538-0d0f-47ad-afbd-d5b28e76d6f8)

**Comment by robinkou** [comment]
I understand now. Thank you very much for your answer
