### ISSUE TITLE
zeekCtl MemLimit field is set to run after a while to crash

### ISSUE THREAD

**Issue by shuaidonga** [zeek/zeek#411]
When the MemLimit value in zeekctl.cfg is set to 1500000, the system crashes after each work runs for a while.
![image](https://user-images.githubusercontent.com/16378509/59406863-1cfd5300-8de2-11e9-94f7-8f3e655dd7f4.png)
please help me.

**Comment by jsiwek** [comment]
`MemLimit` only changes the shell resource limits via `ulimit`, so that's expected if you decrease it from the default of "unlimited" and actually require more than what you set.

No option exists to dynamically and gracefully throttle the total memory use per worker -- that all depends on scaling your cluster and which scripts/analyzers are active (and it's also always possible to write your own custom script that accidentally have unbounded memory growth).
