### ISSUE TITLE
Any plan to update SQLite to latest 3.28.0?

### ISSUE THREAD

**Issue by rebeccasf** [zeek/zeek#448]
SQLite3 has identified CVEs up to version 3.27.2. Version 3.26.0 was impacted.
Reference: CVE-2019-8457 and CVE-2019-5018

Is there any plan to update the 3rd-party submodules for sqlite3?

**Comment by rebeccasf** [comment]
Thanks for the quick fix. Is there any plan to make a new release to include this change?

**Comment by 0xxon** [comment]
Hi,

this will be part of the next general release. At the moment I don't see a big reason to release anything before including this.

CVE-2019-5018 seems to only trigger if you are able to pass specially crafted queries to SQLite. Since the queries will be generated by (trusted) scripts this should not be remotely triggerable for Zeek.

CVE-2019-8457 needs an invalid value to be passed; this seems to again at least need control of the sql statement (or even direct c-level access to the SQLite API, I am not sure).

So both of these do not really seem especially critical for us - let me know if I am missing somethong.
