### ISSUE TITLE
MQTT analyzer

### ISSUE THREAD

**Issue by sethhall** [zeek/zeek#474]
This is being pulled in directly instead of done as a plugin.  I should have a pull request ready for it soon.

**Comment by jsiwek** [comment]
It's merged, but a couple questions to address ASAP:

* The payload of all publish messages is being logged?  How big these get?  It's also possibly just arbitrary application data and not readable?

* Don't think either subscribe or unsubscribe messages are handled right in the scripting layer: one event is raised per topic within a single `msg_id`, so if a message actually has more than one topic in it, it just overwrites the state table's `msg_id` index with a new `SubscribeInfo`.  So only the last topic within a message gets logged.

Lesser questions/feedback:

* Wondering if it should really be doing flowunit parsing, not datagram?

* The pub/sub logging being based on 5 second expiry seems janky, and so sensitive to high latency, but don't have other suggestion and guess it's not too mad to be missing that information if it's only QoS ACKs and stuff

**Comment by sethhall** [comment]
> * The payload of all publish messages is being logged?  How big these get?  It's also possibly just arbitrary application data and not readable?

Yeah, I think we might need to revise the payload messages to not log the full thing because potentially I think those can get up to 256MB (totally slipped my mind!).  This could also potentially cause an issue at the event layer just by creating strings that large, right?

Also, you're right that it's arbitrary application data, but all of the exploration I've done with MQTT has shown lots of messages like "ON", "OFF", or other short identifying strings.

> * Don't think either subscribe or unsubscribe messages are handled right in the scripting layer: one event is raised per topic within a single `msg_id`, so if a message actually has more than one topic in it, it just overwrites the state table's `msg_id` index with a new `SubscribeInfo`.  So only the last topic within a message gets logged.

Oh, if a user subscribes to multiple topics with a pattern do they get an ack for each topic that ended up getting subscribed to?  Apparently I need to look at some more traffic.

> * Wondering if it should really be doing flowunit parsing, not datagram?

I tried switching to flowunit but I got that incremental parsing error from BinPAC and didn't spend time digging further.

> * The pub/sub logging being based on 5 second expiry seems janky, and so sensitive to high latency, but don't have other suggestion and guess it's not too mad to be missing that information if it's only QoS ACKs and stuff

That was kind of my perspective too.  Unfortunately if we're going to be doing full roundtrip logging we don't have much of an option other than to pick an arbitrary point in the sand and draw the line.  I hope 5secs isn't too short, but we should be able to see logs later if it turns out that was too short.

**Comment by jsiwek** [comment]
> Yeah, I think we might need to revise the payload messages to not log the full thing because potentially I think those can get up to 256MB (totally slipped my mind!). This could also potentially cause an issue at the event layer just by creating strings that large, right?

Yeah, was thinking both are problems: allocating large payload strings, then also logging them.

> Oh, if a user subscribes to multiple topics with a pattern do they get an ack for each topic that ended up getting subscribed to? Apparently I need to look at some more traffic.

No, think I read it the same way you did: a Subscribe message has 1 or more Topics, and a SubscribeAck responds to that full Subscribe message, but what I was saying is it looks like the events we generate for Subscribe/Unsubscribe are 1 event per Topic within a given message:

https://github.com/zeek/zeek/blob/ac7daf84563b0654489d6baf96ca014ca47ff6a2/src/analyzer/protocol/mqtt/commands/subscribe.pac#L20-L33

https://github.com/zeek/zeek/blob/ac7daf84563b0654489d6baf96ca014ca47ff6a2/scripts/base/protocols/mqtt/main.zeek#L287-L299

So the script would just keep overwriting the table entry for each Topic in the message instead of keeping track of the aggregate.

Should just change `mqtt_subscribe`, `mqtt_subscribe`, and `MQTT::SubscribeInfo` to use a `vector of string` instead of a single `string` ?

**Comment by sethhall** [comment]
Ugh, you're right.  I kept glossing over the fact that that's an array of strings for the topics.  Yeah, it looks like the most straight forward method would be to do as you suggested with a vector.

**Comment by 0xxon** [comment]
I am going to merge the improvements in a few minutes - but to me it seems like there still are a few things that we should address in the near-term, even though I don't see them as release-blocking:

* it would be neat to support the configuration framework for options

* I think all events could use the new QueueEventFast - I think all of them already check event existence.

Given the fact that this has not seen any real-world testing, I also still am somewhat tempted to propose to treat this like the smb analyzer last time, and disable it by default...

**Comment by rsmmr** [comment]
> * it would be neat to support the configuration framework for options

Yeah, true, we should actually generally require this for new functionality ...

> Given the fact that this has not seen any real-world testing, I also still am somewhat tempted to propose to treat this like the smb analyzer last time, and disable it by default...

@sethhall  Would you be very opposed to that? Alternatively, we  have allowed ourselves some more days for testing before we cut RC1: Can we get this run in some large places this week?

**Comment by jsiwek** [comment]
> > * it would be neat to support the configuration framework for options
> 
> Yeah, true, we should actually generally require this for new functionality ...

There's cases where `option` may be less desirable:

* If it's a performance-sensitive path and you'd like to avoid having to lookup the ID / Val every time it needs to be used.

* If you don't *want* the user to change it at run-time.  i.e. maybe it's just a weird state change to make or other reasons that it may cause problems.

In this case, it's probably less about performance, though it's still inconvenient to do the lookup every time in the core, but more about weirdness: couldn't see someone wanting to globally change the max payload at run-time -- they'd probably rather want a per-connection tuning option.

In the end, if we want this particular one as an `option`, I won't argue much, but just saying in general: there's potentially reasons to not always choose `option` as the way to go.

> * I think all events could use the new QueueEventFast - I think all of them already check event existence.

The `BifEvent::generate_` functions all use `QueueEventFast` internally.  They also provide some extra argument conversion/type-checking, so seems fine to leave them instead of calling it directly.  Or do you mean somewhere else is using `QueueEvent` ?

> Given the fact that this has not seen any real-world testing, I also still am somewhat tempted to propose to treat this like the smb analyzer last time, and disable it by default...

I'm not opposed.

**Comment by 0xxon** [comment]
In at leas one other case, the way that we handled options on a performance-critical path was to introduce a new integer, local to the analyzer, and a set-bif, which is executed automatically by the script-level when the script-level variable is touched.

I admit that is more code, but it should not have a performance impact in comparison to the current state that way.

As for changing it at run-time - I think the final "goal" is to basically make all options run-time configureable, where there is no technical reason why that is not possible. You are right about the "weird state" - I can see this being the case - but this does not seem to apply here.

About QueueEventFast - I totally missed that BifEvent::generate_ uses that now :)

**Comment by jsiwek** [comment]
> I admit that is more code, but it should not have a performance impact in comparison to the current state that way.

Agree, I take back the perf. impact argument.

> As for changing it at run-time - I think the final "goal" is to basically make all options run-time configureable, where there is no technical reason why that is not possible. You are right about the "weird state" - I can see this being the case - but this does not seem to apply here.

Sure, I mostly just wanted to point out the general perspective that I'm expecting any `option` to be *safe* to modify at run-time and that can require a case-by-case thought process when deciding on `const &redef` versus `option`.  (And also thinking requires effort, hence conservative use of `const &redef`)

**Comment by 0xxon** [comment]
Disabling by default is done in https://github.com/zeek/zeek/pull/523

**Comment by jsiwek** [comment]
Closing this as MQTT disabling-by-default is done per #523 and it's the only thing critical to 3.0.

#524 changes to use a runtime `option` for the max payload size and can merge whenever.
