### ISSUE TITLE
Error Compiling on Debian 10 / Buster

### ISSUE THREAD

**Issue by TravisFSmith** [zeek/zeek#489]
Unable to complete compiling on Debian 10 / Buster versions of the platform.  

```
Sample Output from 'sudo make'
[  9%] Linking CXX executable bin/broker-pipe
/usr/bin/ld: lib/libbroker.so..: undefined reference to `__atomic_store_8'
/usr/bin/ld: lib/libbroker.so..: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[3]: *** [aux/broker/CMakeFiles/broker-pipe.dir/build.make:92: aux/broker/bin/broker-pipe] Error 1
make[3]: Leaving directory '/home/<username>/Downloads/bro-2.6.2/build'
make[2]: *** [CMakeFiles/Makefile2:398: aux/broker/CMakeFiles/broker-pipe.dir/all] Error 2
make[2]: Leaving directory '/home/<username>/Downloads/bro-2.6.2/build'
make[1]: *** [Makefile:152: all] Error 2
make[1]: Leaving directory '/home/<username>/Downloads/bro-2.6.2/build'
make: *** [Makefile:15: all] Error 2
```

**Comment by jsiwek** [comment]
For x86_64 and gcc 8.3.0, I don't see this.  What is your architecture/compiler info ? e.g. `uname -a` and `c++ --version`.

A crude workaround to try may be: `rm -rf ./build/ && LDFLAGS="-latomic" ./configure && make`

Otherwise, sounds like there's some platforms where the CMake logic needs to try to autodetect whether to link libatomic automatically.

**Comment by TravisFSmith** [comment]
Currently running:
uname -a:  Linux raspberrypi 4.19.58-v7l+ #1245 SMP Fri Jul 12 17:31:45 BST 2019 armv7l GNU/Linux

c++ --version: c++ (Raspbian 8.3.0-6+rpi1) 8.3.0

Just for reference, 2.6.2 compiles fine on Jessie & Stretch versions of raspbian. I believe I also ran into the same issue in an Ubuntu 19, I will double check that as well as the workaround mentioned.

**Comment by TravisFSmith** [comment]
Same error when doing the instructions above.

**Comment by jsiwek** [comment]
Was able to reproduce on that platform/specs.  Should be fixed in `master` now, or if you prefer to stick with 2.6.2, this patch to `aux/broker/CMakeLists.txt` should still work for that version, too:

https://github.com/zeek/broker/commit/3582d0c00b51f13d1cdf1b370f9f9301ab41eeb0#diff-af3b638bc2a3e6c650974192a53c7291
