### ISSUE TITLE
Any type not working with arithmetic types

### ISSUE THREAD

**Issue by ZekeMedley** [zeek/zeek#498]
Presently, something like this works fine in Zeek.

```zeek
local a: any = "fast";
local b: string = a;
print b + " dog";   # prints -> fast dog
```
But does not work for arithmetic types.

```zeek
local a: any = 1;
local b: count = a;
print b + 10;
```
Error `assignment of non-arithmetic value to arithmetic (count/any) (b = a)`

One result is that Zeek's `Queue` stops working for arithmetic types.
```zeek
local q = Queue::init();
Queue::put(q, 1.1);
Queue::put(q, "do");
local a: double = Queue::get(q);
local b: string = Queue::get(q);
```
My suspicion is that fixing this should just be a matter of changing a little logic here:
https://github.com/zeek/zeek/blob/95ce17768269652dfe2fdbd8fc5206e38548088d/src/Expr.cc#L2220-L2230

**Comment by jsiwek** [comment]
Don't immediately have an answer for how the language *should* handle `any` here.  That type is generally probably not consistently handled and probably most often used just in cases where we wanted to bypass type-checking... not something we intend people to do generally (guess would have just made a dynamically typed language then).

But you can be explicit about your type conversions as a workaround for you examples:

```zeek
local a: any = 1;
local b: count = a as count;
print b + 10;
```

```zeek
local q = Queue::init();
Queue::put(q, 1.1);
Queue::put(q, "do");
local a: double = Queue::get(q) as double;
local b: string = Queue::get(q) as string;
print a, b;
```

For queue, also don't generally think they were intended to be used to contain heterogenous value types, so that seems like it may be mostly up to the user to keep track of themselves if they're going to use it that way.

**Comment by rsmmr** [comment]
Agree that this isn't supposed to be supported in the first place.
