### ISSUE TITLE
windows deployment

### ISSUE THREAD

**Issue by Cry0k** [zeek/zeek#504]
Hi guys,

i have two main questions:
1) can i install zeek on windows platforms?
2)in case i cannt install zeek on windows platforms can i configure server client relationship between zeek and a windows host?

thanks in advance.

**Comment by jsiwek** [comment]
> 1. can i install zeek on windows platforms?

Not natively, but it can build/install under Windows Subsystem for Linux (WSL) last I checked, however there's two issues with that as well:

* Doesn't support live packet capture.

* The WSL implementation for `long double` isn't supported as what it should be (an 80-bit extended precision floating point): https://github.com/microsoft/WSL/issues/830.  I don't know if that's much problem for Zeek in practice, but there's at least one unit test that will fail, showing that results may be different on WSL than on Linux.

The second problem may be fixed in WSL2, but I don't know about the first.

>    2)in case i cannt install zeek on windows platforms can i configure server client relationship between zeek and a windows host?

You didn't explain enough what you want to do, but simply establishing a communication channel would be possible if the windows host (running WSL) uses https://github.com/zeek/broker to talk to a remote Zeek process.

**Comment by burhan26** [comment]
Is live packet capture supported while running Zeek on WSL2? I want Zeek to sniff packets on a network adapter of the Windows VM where I'm running Zeek using Debian on WSL2.

**Comment by timwoj** [comment]
@burhan26 This is a really old issue to be bumping, but the answer is that if it does, it's wholly untested. There is the Windows version of Zeek now, if that would be easier for you to build. That version does support packet capture if you link it against npcap.

For future usage questions, the #windows channel on Slack is probably a better place to ask. We try to keep GitHub usage just for issues with the code itself.

**Comment by burhan26** [comment]
Thanks so much! That's very helpful.
