### ISSUE TITLE
Please strip the installed binaries

### ISSUE THREAD

**Issue by yurivict** [zeek/zeek#511]
The FreeBSD the ports system complains:

```
Warning: 'bin/binpac' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
Warning: 'bin/bifcl' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
Warning: 'bin/paraglob-test' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
Warning: 'bin/zeek' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
Warning: 'lib/libbinpac.so.0.51-27' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
Warning: 'lib/libcaf_core.so.0.16.3' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
Warning: 'lib/libcaf_io.so.0.16.3' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
Warning: 'lib/libcaf_openssl.so.0.16.3' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
Warning: 'lib/libbroker.so.1.1' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
```

**Comment by jsiwek** [comment]
CMake does generate a target called `install/strip` which appears to install and strip binaries.  Seems the port could just change to use that?  If so, we'll close this issue (we're not directly involved w/ maintaining the port), else please explain what more needs to be provided for the port to do stripping.

**Comment by yurivict** [comment]
> CMake does generate a target called install/strip which appears to install and strip binaries. 

cmake doesn't seem to be able to disable python, etc.. No equivalents of ```--disable-auxtools --disable-python --disable-broker-tests --disable-zeekctl```.

**Comment by jsiwek** [comment]
> cmake doesn't seem to be able to disable python, etc.. No equivalents of `--disable-auxtools --disable-python --disable-broker-tests --disable-zeekctl`.

You mean the equivalents for when calling `cmake` directly instead of our `configure` wrapper script?

Those would be `cmake` arguments:
* `-D INSTALL_AUX_TOOLS:BOOL=false`
* `-D DISABLE_PYTHON_BINDINGS:BOOL=true`
* `-D BROKER_DISABLE_TESTS:BOOL=true`
* `-D INSTALL_ZEEKCTL:BOOL=false`

You can generally read the `configure` script for any others you need.

**Comment by yurivict** [comment]
> Those would be cmake arguments:

These work, thanks!

--------

The cmake target ```install/strip``` still installs some unstripped files:
```
Warning: 'lib/libcaf_core.so.0.16.3' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
Warning: 'lib/libcaf_io.so.0.16.3' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
Warning: 'lib/libcaf_openssl.so.0.16.3' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
```

**Comment by sethhall** [comment]
You could try the CMAKE option..
`-D BUILD_STATIC_BROKER:bool=true`

That should statically link in CAF and avoid this issue.

**Comment by yurivict** [comment]
> That should statically link in CAF and avoid this issue.

It now installs static libraries, ex. ```lib/libbroker.a```. This doesn't solve the problem, just hides it.

Static libraries are against the policy without a compelling reason, because they blow up the disk, unless there is a good reason.

**Comment by jsiwek** [comment]
> The cmake target `install/strip` still installs some unstripped files:
> 
> ```
> Warning: 'lib/libcaf_core.so.0.16.3' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
> Warning: 'lib/libcaf_io.so.0.16.3' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
> Warning: 'lib/libcaf_openssl.so.0.16.3' is not stripped consider trying INSTALL_TARGET=install-strip or using ${STRIP_CMD}
> ```

We actually embed and build/install an external library as a convenience to users, but for the purpose of packaging/ports, you probably want that external library as it's own package and tell Zeek to depend on that rather than use our embedded version.

Those libcaf* libraries are really from https://github.com/actor-framework/actor-framework

And you'd use the `--with-caf=` or equivalent `CAF_ROOT_DIR` option to configure Zeek to use it.  So it's probably going to be more a question for the CAF development team if the libraries are still not stripped when installing it independently.

**Comment by jsiwek** [comment]
So think there's no further action to take here, else let me know what's missing.
