### ISSUE TITLE
Provide bro-compat package

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#521]
@Justin suggested a `bro-compat` that would allow scripts written for Zeek to work with 2.x Bros. That's something we should provide ourselves, so that everybody uses the same package. Otherwise it'd conflict if people implemented it independently.

Quick 1st stab at code (extended form Justin's code, not tested)

```
@ifndef ( zeek_init )
# Running on Bro 2.x, which doesn't know anything about Zeek events & functions.
global zeek_init: event();
global zeek_done: event();
global zeek_script_loaded: event();
	
event bro_init() { event zeek_init(); }
event bro_done() { event zeek_done(); }
event bro_script_loaded() { event zeek_script_loaded(); }

TODO: Add similar for `zeek_version()` and `zbro_is_terminating`.
@endif
```

**Comment by jsiwek** [comment]
> event bro_init() { event zeek_init(); }
> event bro_done() { event zeek_done(); }
> event bro_script_loaded() { event zeek_script_loaded(); }

These won't work with exactly the same semantics as before due to event ordering (and that can be important) -- raising an event like this does not handle it immediately, it gets queued for later.

Also not clear what goal the idea is aiming at: provide wrappers for just the newly named "zeek" stuff such that they'll work with 2.x, or generally make "anything written to target 3.0 also work in 2.x".  The later is way less tenable, but if we didn't do the full compatibility treatment, then it doesn't seem useful to me anyway -- people will have to go audit all of the compatibility differences anyway.

Generally, the idea of allowing things that target 3.0 to also automatically work in 2.x is "nice", but also a mixed-message and bad precedent?  Once 3.0 is out, we shouldn't generally support or encourage use of older versions anymore?

IMO, this is in the realm of leaving it up to the individual script maintainer to write whatever is necessary for 2.x and 3.0 compatibility if they do want both.  e.g. it's on them to write the `@if` conditions that check for the necessary Bro/Zeek versions.  That's my suggested policy for any future major-version transition, too.

**Comment by rsmmr** [comment]
That was my initial take, too (leave it to the script maintainer). However if multiple people write that code above, the init event will be raised multiple times. Having it in a standardized package would avoid that. And I think this would actually do encourage going with 3.0: it makes it easier to write scripts for 3.0 even if one is concerned about others still on 2.x.

That said, yes, it wouldn't be exactly the same, and generally backwards compatibility is a more complex problem than just this. And worse, if we did this, it could actually create the impression that the package simply solves it completely--which it doesn't. So yeah, I think you convinced me to better leave this alone.

I'll leave the ticket open for a bit if there's further input, otherwise will close.

**Comment by timwoj** [comment]
I agree with Jon here. Adding a package that basically reverses the name change negates the reason we did the name change in the first place.
