### ISSUE TITLE
disable_analyzer doesn't work on TCP_ApplicationAnalyzer's

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#532]
`disable_analyzer` walks a connection's Analyzer tree looking for the analyzer to remove, but this doesn't include `TCP_ApplicationAnalyzer`'s because those are not really in the tree, but rather are separate children of the `TCP_Analyzer`.

More generally, I keep running into problems because `Analyzer` methods don't work consistently on all subclasses of `Analyzer` - really confusing.  Either this should be regularized, or terminology adjusted so that the coder isn't misled.

**Comment by jsiwek** [comment]
Do you have a specific example to reproduce what you are seeing?

Asking because `HTTP_Analyzer` is a type of `TCP_ApplicationAnalyzer`, but this appears to work:

```zeek
event http_reply(c: connection, version: string, code: count, reason: string)
	{ disable_analyzer(c$id, current_analyzer(), T); }
```

Though this does not work:

```zeek
event protocol_confirmation(c: connection, atype: Analyzer::Tag, aid: count) &priority=10
	{ disable_analyzer(c$id, aid, T); }
```

But that's because `Analyzer::RemoveChildAnalyzer` is only looking for the analyzer within the `children` list, while the protocol confirmation is happening at a time when the analyzer is only in the `new_children` list and waiting to be moved into `children`.  Simple to patch that method to check both lists, but not sure if that's the same bug being reported.

**Comment by vpax** [comment]
I don't have an easy example, as this was from debugging my own plugin.  However, maybe you can clarify for me about `new_children`.  What I saw was that my analyzer, which I was adding via `TCP_Analyzer::AddChildPacketAnalyzer`, gets put into the `TCP_Analyzer`'s `packet_children` list.  I don't see how the generic `Analyzer::RemoveChildAnalyzer` code is going to know about that list and be able to loop over it (though that's certainly the semantics I'd like, ideally).

**Comment by jsiwek** [comment]
> However, maybe you can clarify for me about `new_children`.

I was looking at the way analyzers generally get added to the tree from either a DPD signature or well-known port.  Those call `Analyzer::AddChildAnalyzer` which doesn't directly put the new analyzer in the `children` list, but rather `new_children` (seems that's to prevent iterator invalidation if called while looping over children).  In the DPD case, I was seeing the `disable_analyzer` call fail to find the analyzer within the `protocol_confirmation` event since it was still in the `new_children` list.

So sounds like I found a different bug than you.

> What I saw was that my analyzer, which I was adding via `TCP_Analyzer::AddChildPacketAnalyzer`, gets put into the `TCP_Analyzer`'s `packet_children` list. I don't see how the generic `Analyzer::RemoveChildAnalyzer` code is going to know about that list

Yeah, the `packet_children` were not considered in `RemoveChildAnalyzer`.  Would be great if you can confirm the patch in https://github.com/zeek/zeek/pull/534 fixes it for you.  I tested it using the conn-size analyzer which also uses `TCP_Analyzer::AddChildPacketAnalyzer` like you do.

**Comment by vpax** [comment]
@jsiwek Confirmed that the patch fixes my original problem - thanks!  Apologies this took a while for me to check.
