### ISSUE TITLE
"r is record" and "r as record" do not work

### ISSUE THREAD

**Issue by grigorescu** [zeek/zeek#547]
It looks like there's a parsing bug that's preventing the new dynamic type-checking and casting from working:

`if ( r is record )` results in:

> syntax error, at or near ")"

Similarly:

Same error for ` print (r as record)`.

**Comment by jsiwek** [comment]
Don't think that should work: "record" isn't a type itself, you should use the concrete record type for the type-checking/casting operations.  E.g. if `r` were a record of type `conn_id`, you'd use `r as conn_id`.  An analogy in terms of C/C++: it would sort of be like trying to cast to just a `struct` rather than the particular user-defined struct type.
