### ISSUE TITLE
Bro 2.6.4 Install Error

### ISSUE THREAD

**Issue by blacktop** [zeek/zeek#564]
Using Docker I get the following error:

[error output](https://gist.github.com/blacktop/b3f691a87d4186b207bfd4f1d7dc2aba)

Here is my dockerfile:

https://github.com/blacktop/docker-zeek/blob/master/2.6/Dockerfile

**Comment by jsiwek** [comment]
The patch for this is here:

https://github.com/zeek/binpac/commit/a28376b3712822ecca6f547ee532e42bc729795c

It hasn't made its way into any 2.6.x release and likely won't ever since we'll be moving support efforts to 3.0.x in likely just a couple weeks.

I suggest to either apply the patch directly, or else build/install the latest release of binpac, v0.54, separately and then instruct the configuration process for Bro 2.6.x to use it via `./configure --with-binpac=/path/to/binpac`.
