### ISSUE TITLE
SSH Analyzer Skipping Some Encrypted Messages

### ISSUE THREAD

**Issue by anthonykasza** [zeek/zeek#566]
The first encrypted message of an SSH session is not processed if it is included in a packet which also includes an SSH DH message or NewKeys message. This means the `ssh_encrypted_packet()` event is not raised under certain conditions such as specific client + server combinations. See the attached pcaps
[pcaps.zip](https://github.com/zeek/zeek/files/3570644/pcaps.zip)

In the pcap named ssh_server_sends_first_enc_pkt_with_newkeys.pcap the server sends its DH reply, NewKeys, and an encrypted message (the first of the session) all in the same packet (packet 12). The encrypted message is not processed by Zeek's SSH analyzer as is expected. The first encrypted packet processed by Zeek's SSH protocol analyzer is packet 15.

In the pcap named ssh_client_sends_first_enc_pkt_with_newkeys.pcap, the client includes an  encrypted message (the first of the session) in the packet carrying its NewKeys message (packet 13). Yet, the first encrypted message processed by Zeek's protocol analyzer is packet 15.

This bug can be demonstrated via the following script:
```
global pkts: count = 0;
redef SSH::disable_analyzer_after_detection = F;

event ssh_encrypted_packet (c: connection, orig: bool, len: count) {
  if (pkts < 2) {
    print orig ? len : len * -1;
    pkts = pkts + 1;
  } else {
    return;
  }
}
```

Output of the script when run on the attached pcaps.
```
$ bro test.bro -Cr ssh_client_sends_first_enc_pkt_with_newkeys.pcap 
-64
80

$ bro test.bro -Cr ssh_server_sends_first_enc_pkt_with_newkeys.pcap
44
-44
```

In both cases, the first encrypted packet to raise the `ssh_encrypted_packet()` event is the first encrypted packet NOT included with any type of SSH message.

**Comment by jsiwek** [comment]
Yeah, looks like we're not raising `ssh_encrypted_packet` for data in the later portion of a (reassembled) tcp segment that transitions into an encrypted state in the middle of that segment.  I'll take a look if it's easy to update the binpac grammar to capture that data in the event as well.

(A technicality that's maybe interesting to keep in mind is that this event has "packet" in the name, but maybe really ought to be thought of as "segment" due to the way it's currently raised using the length of data pertaining to reassembled TCP segments being fed into the analyzer, which may end up actually spanning multiple packets, like in the case we're filling in a previous gap).

**Comment by anthonykasza** [comment]
Even more confusing is that SSH uses the term "packet" for its binary format.
https://tools.ietf.org/html/rfc4253#section-6
