### ISSUE TITLE
Require cmake 3

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#571]
#264 will need cmake3, and more generally it seems it's time to switch to version 3; that has been out for a long time now. Let's do a quick survey across our supported platform to see what they ship these days, and what minimum version of 3.x makes sense to require.

**Comment by timwoj** [comment]
I looked through this when it came up and I believe the only outlier is CentOS 7 which has 2.8 in the baseline install. 3.x is available on EPEL though for those systems. Debian 8 has 3.0.2.

**Comment by jsiwek** [comment]
This page should have all the relevant availability/life-cycle info:

https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/Life-Cycle-Considerations#fn4-8698

So based on an estimate of when Zeek 4.0 will come out (year from now), might aim to support whatever CMake version is on Ubuntu 16.04 LTS (probably will stay within 3.5.x) since Debian 8 should be on the way out by then.  CentOS/RHEL will still have CMake 2.8.x as the default, but don't think we should wait on them since their support cycle is so long and do provide an easy way to get CMake 3.x (e.g. EPEL).

**Comment by 0xxon** [comment]
The related #645 (prefer cmake3 in configure) has just been merged.

**Comment by Neverlord** [comment]
I've opened a couple of PRs to do the transition in Zeek, `zeek-aux` and Broker. I've also fixed the handling of Apple's Clang releases (https://github.com/zeek/cmake/pull/10). The PR in the cmake module may be worth some discussion: it's probably a good idea to move away from compiler-specific version checks and instead check the value of `__cplusplus` and/or [feature macros](https://en.cppreference.com/w/User:D41D8CD98F/feature_testing_macros).

**Comment by jsiwek** [comment]
CMake 3.0+ is now required via #662 (and others)
