### ISSUE TITLE
Remove MemoryAllocation()?

### ISSUE THREAD

**Issue by rsmmr** [zeek/zeek#572]
A number of classes have `MemoryAllocation()` methods that try to estimate the actual memory usage of an instance, taking things like padding by the allocator into account. However, it's unclear if this logic still works: it has neither been validated in a long time nor I believe consistently updated with code changes. It's also not portable to begin with due to assumptions about specifics of the allocator. I suggest we investigate to which degree people are still relying on the numbers this computes and consider removing it.

**Comment by sethhall** [comment]
I've also been suspect of this functionality for a long time and I think it makes sense to remove it.  I'd be surprised to discover if anyone is using it.

**Comment by timwoj** [comment]
I had to make some changes to some of this code for the namespacing work and remembered that we had talked once about removing it. Is this something we want to actually do?

**Comment by rsmmr** [comment]
Yeah, I'm in favor of removing.

**Comment by initconf** [comment]
OHhh wait ! Can you please hold off on removing this - I am very recently been aware of this ( Thanks @0xxon ) I have been struggling trying to figure out sizes of data structures and memory explosions inside policies - I can make use of this function quite a bit  (instead of only replying in Global_size in prof.log or doing counts of members in tables and sets etc). 

I am made aware that we don't know how correct this function is - but let me test that out. Please don't remove it for now if you can.

**Comment by initconf** [comment]
> I've also been suspect of this functionality for a long time and I think it makes sense to remove it. I'd be surprised to discover if anyone is using it.

I think thats because I was not aware of this. I find it promising and useful - I wish to try it out !

**Comment by timwoj** [comment]
> I am made aware that we don't know how correct this function is - but let me test that out. Please don't remove it for now if you can.

Sure, we've waited a while on this one. We can wait longer. 👍 

Let me know when you're done testing with it, and we can discuss whether it truly is working or not.

**Comment by rsmmr** [comment]
@initconf I'd be interested how MemoryAllocation() compares for you to profiling tables/set just by their number of entries. The particular values that MemoryAllocation() reports, aren't very precise, but they help for finding the big guys. However, number entries does so, too, and I'm not sure how much more MemoryAllocation tells. I believe it helps mostly for recursive/nested tables, but there aren't that many of those usually.

**Comment by rsmmr** [comment]
@initconf did you have chance to play with this yet?

**Comment by timwoj** [comment]
There are also `NetSession::ConnectionMemoryUsage` and `NetSession::ConnectionMemoryUsageConnVals`, which rely on `MemoryAllocation`. Those will be removed as well.

**Comment by initconf** [comment]
Update: 

So I did run val_size on complex tables etc. Seems to be giving numbers about right but I am not entirely sure how to verify them. 

Here is the worse case scenario I tried : 

`type dns_summary: record {
                num_query: count &default=0 ;
                query: opaque of cardinality &default=hll_cardinality_init(0.1, 0.999);
                hosts: opaque of cardinality &default=hll_cardinality_init(0.1, 0.999);
                qtype_name: table[string] of count &write_expire=1 day ;
                first_seen: time ;
                last_seen: time;
        };
  global heavy_hitters: table[addr] of dns_summary &create_expire = 1 day &expire_func=expire_heavy_hitters ;
event zeek_done()
{
        print fmt ("val_size: %s", val_size(heavy_hitters));
}`


issue I am trying to figure out is - how can I get sizes of tables and data structures to see whats bloated and whats not. 

Right now I end up using either RES memory from top or otherwise membership counts to estimate memory issues. 

Here is one example on one cluster I see:

  PID USERNAME       THR PRI NICE   SIZE    RES STATE   C   TIME    WCPU COMMAND
53859 bro             58 103    0 62989M 62873M CPU29  29 947.9H 209.20% zeek <------------ MANAGER - notice memory 
54519 bro             17  49    0  4531M  4156M CPU30  30 167.5H  41.75% zeek
54496 bro             17  46    0  4551M  4432M mx cv  10 162.6H  40.66% zeek
54422 bro             17  46    0  4531M  4424M mx cv  28 159.5H  39.42% zeek

rest all 40 workers are doing right. 

I want to know what in manager is actually bloating. 

So I plotted some graphs related to different data structures  based on Global_size from prof.log 

eg. :

<img width="663" alt="Screen Shot 2020-09-02 at 4 22 30 PM" src="https://user-images.githubusercontent.com/4044729/92499936-570a0000-f1b1-11ea-9716-1ce813e0aca5.png">

Thats NetControl::rules then there are other such structures too but still they don't completely add to 62GB. 

Action items:
1) figure out if val_size gives right (and consistent numbers) 
2) Embed val_size into scan_detection, and few other complex scripts and dump a size log every 5 mins to see membership growth vs val_size and if there is explosion. 

Hurdle - since production DMZ are right now managing about 5M filters, I am avoiding restart until I have to and then I am deploying the (2) Embed val_size patch into prod ext-dmz boxes.

**Comment by rsmmr** [comment]
@initconf Any further updates?

**Comment by initconf** [comment]
(sorry for the delays) I haven’t done any more on this actually. 

I’d say remove it and my impression is that it is not fully accurate for certain complex data structures.
It would be a nice feature to have which allows measurements of sizes of tables etc to be able to rely on data calibrate expire functions etc.  I was hoping this lets me do that. 
I’d say OK to remove.

**Comment by timwoj** [comment]
This will require some changes to the output for stats and the removal of a couple of bif methods as well (`val_size` and `global_sizes`).

**Comment by rsmmr** [comment]
Yeah, that sounds good to me, will also give us more time to see if more people are using it and if so, if there's any substitute/proxy we could provide for their use cases.

**Comment by rsmmr** [comment]
Looks like agreement to go ahead with this and deprecate, then remove.
