### ISSUE TITLE
IntervalVal::ValDescribe does some weird transformations

### ISSUE THREAD

**Issue by grigorescu** [zeek/zeek#589]
Consider the following:

```
local tiny = 0.123456789 usec;
print "Tiny is", tiny;
local small = tiny*1000;
print "Small is", small;
```

The result I expect is:
```
Tiny is, 0.123456789 usecs
Small is, 123.456789 usecs
```

However, what actually prints is:
```
Tiny is, 
Small is, 123.0 usecs
```

So it looks like there are two problems here:

1. Values < 1 usec don't get described at all, even though they are being stored.
2. Values get coerced to an int and then back to a double, causing a loss of precison.

There's another small result of problem 2, which we may or may not want to fix. Because of this coercion, all values are printed as .0 doubles. `1.0 day 1.0 hr 1.0 min 1.0 sec 1.0 msec` could more succinctly be described as `1 day 1 hr 1 min 1 sec 1 msec` with no loss over the current precision (obviously, if we address the other issues here, the last unit should have values after the decimal point, if needed).

**Comment by jsiwek** [comment]
Yes, looked like `IntervalVal::ValDescribe` wasn't properly handling sub-microsecond values, but the additional ".0" is being added "on purpose" by:

https://github.com/zeek/zeek/blob/916491e2b4b828cad6624dd2e334d33206033804/src/Desc.cc#L167-L169

The PR in #593 will handle just the sub-microsecond bug.

Generally, I don't have a problem with changing intervals to drop the ".0" when possible (since they're already disambiguated from integers by presence of the unit label, like "secs").  Just didn't feel like doing it since that's not strictly a "bug" and probably had a bunch of test baselines to update, but feel free to create a separate "enhancement" issue for it.

**Comment by grigorescu** [comment]
Thanks @jsiwek . I think that sounds good, and I'll plan on filing an enhancement for it.

One question I did have is that the following generates a syntax error right now:
```
local i = 3.0 days 2.0 hours
```
The interval would need to be initialized as `3.0 days + 2.0 hours`. It feels like how the value gets printed and parsed should match, whenever possible.

As long as I'm touching that code, I could add a plus between values, but it feels like the better solution would be to have the parser support that?

**Comment by jsiwek** [comment]
> ```
> local i = 3.0 days 2.0 hours
> ```
>
> feels like the better solution would be to have the parser support that?

Might be a possibility.  Unless others immediately express strong feeling against it, feel free to make another enhancement issue for that.

**Comment by vpax** [comment]
While I agree it looks better, I expect it'll be tricky to implement due to grammar complexities.  Gramatically, `3.0 days` is an expression, as is `2.0 hours`.  So to avoid having concatenated expressions in the grammar (which will cause all sorts of problems), I think this will require the lexer doing look-ahead ... which gets ugly if there are possibilities like embedded comments or newlines.  These would have to be ruled out, and the scanner would need to know all of the possible `interval` modifiers.
