### ISSUE TITLE
Received via Files::ANALYZER_DATA_EVENT stream_event data length differs from seen_bytes

### ISSUE THREAD

**Issue by Olerdrive** [zeek/zeek#590]
Hello! I am trying to make my file extraction process more complicated, so I add `Files::ANALYZER_DATA_EVENT` to every new file seen in `file_sniff` event:

```
event file_sniff(f: fa_file, meta: fa_metadata)
{
    Files::add_analyzer(f, Files::ANALYZER_DATA_EVENT, [$stream_event=worker_data_event]);
}
```

In that `worker_data_event` I publish received `fa_file` and `data` to `manager_topic` and then to my python script

But the length of the received bytes and the `info.seen_bytes` confuses me: it differs.

```
    ep = broker.Endpoint()
    sub = ep.make_subscriber("/my/topic/")
    ss = ep.make_status_subscriber(True)
    ep.peer(BC_ADDR, BC_PORT)
    st = ss.get()
    while not (type(st) == broker.Status and st.code() == broker.SC.PeerAdded):
        logger.error("could not connect to bro: {}".format(st.code()))
        st = ss.get()
        continue

    logger.info("Successfully started")
    while True:
        (t, d) = sub.get()
        ev = broker.bro.Event(d)
        args = ev.args()

        body = args[1]
        if type(body) == str:
            body = body.encode()

        logger.info(len(body))

        meta = json.loads(args[0])

        logger.info(meta['info']['seen_bytes'] == len(bytes))

```

Am I doing something wrong? I am expecting `data` argument passed to `stream_event` to be the full content of the sniffed file.

Also I have tried to compare hashes of received data and the hash written by the analyzer, but the analyzer's value is missing at the time my `stream_event` is called: is there a way to determine an order in which analyzers are being executed?

**Comment by Olerdrive** [comment]
Here's an example pcap in which one simple HTTP GET request happens with `md5summper.zip` file in response. 

It seems to be no difference between `chunk` and `stream` events in the `Data Event Analyzer`


[md5summer.zip.pcap.zip](https://github.com/zeek/zeek/files/3646684/md5summer.zip.pcap.zip)

**Comment by 0xxon** [comment]
Hi,

you misunderstand the difference between the chunk and the stream events here (which is probably a failing of our documentation - I don't see that clearly called out anywhere).

The best documentation for this is in src/file_analysis/analyzer/data_event/DataEvent.h.

The difference between chunk and stream basically is that data delivered via chunk may be out of order (so you can get earlier data chunks after later ones). Data delivered via stream is in order. There is no event that will give you the entire data of a file. This is on purpose - files can get big and we do not want to hold the entirety of it in memory. If you need it, you can manually reassemble them by concatenating the data from the stream event.

Closing this due to the fact that this is no bug - feel free to re-open if you feel otherwise (or generally comment).
