### ISSUE TITLE
--with-caf broke

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#612]
Pointing zeek to a caf installation with --with-caf results in the following errors (and similar):

```
In file included from /home/johanna/bro/master/src/Frame.h:9,
                 from /home/johanna/bro/master/src/Debug.h:24,
                 from /home/johanna/bro/master/src/Expr.h:11,
                 from /home/johanna/bro/master/src/Var.h:8,
                 from /home/johanna/bro/master/src/plugin/ComponentManager.h:9,
                 from /home/johanna/bro/master/src/analyzer/Tag.h:9,
                 from /home/johanna/bro/master/src/analyzer/Analyzer.h:8,
                 from /home/johanna/bro/master/src/analyzer/protocol/tcp/TCP.h:5,
                 from /home/johanna/bro/master/src/analyzer/protocol/bittorrent/BitTorrentTracker.h:5,
                 from /home/johanna/bro/master/src/analyzer/protocol/bittorrent/BitTorrentTracker.cc:3:
/home/johanna/bro/master/aux/broker/include/broker/data.hh:11:10: fatal error: caf/default_sum_type_access.hpp: No such file or directory
   11 | #include <caf/default_sum_type_access.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Neverlord** [comment]
I'm using `--with-caf` in my setup without issues. Can you give more background / the full configuration?

This is how I configure Zeek:
```
./configure --build-dir=/Users/neverlord/corelight/zeek/build/debug --generator=Ninja --sanitizers=address --enable-debug --with-broker=/Users/neverlord/corelight/broker/build/debug --with-caf=/Users/neverlord/corelight/caf/build/debug
```

**Comment by 0xxon** [comment]
Oh, interesting.

This is on a pretty normal fedora 30.

my steps, in a normal zeek checkout are:

```
pushd src/3rdparty/caf
./configure --prefix=$HOME/caf
cd build
make -j32 install
popd
﻿./configure --prefix=/home/johanna/bro/install-master --with-caf=$HOME/caf
make -j32
```

The checkout has all submodule up to date to the current Zeek master; all build directories were deleted before; $HOME/caf also was deleted before.

**Comment by Neverlord** [comment]
@0xxon thanks for providing the steps to reproduce. It works in my setup because I'm setting both CAF_ROOT_DIR *and* BROKER_ROOT_DIR. I'm working on a fix.

**Comment by jsiwek** [comment]
Mostly informational:

I was looking into whether we needed any changes in 3.0.0 and found it still worked there, but then I wondered about why it broke in `master` since then and found an alternate fix would be reverting this:

https://github.com/zeek/zeek/pull/588/commits/68bb0e21a3c057e3e9df0b4861edd893809fcbba

I prefer the current state of things, but just wanted to point it out in case there's sudden insight into other potential improvements (e.g. in `FindCAF.cmake`).

The reason it worked before seems to be that the `find_path(CAF_INCLUDE_DIR_${UPPERCOMP} ...)` calls in Broker end up setting those specific dirs in `CMakeCache.txt` and so Zeek is able to still reference them as the parent project.  However, I don't see `CAF_INCLUDE_DIRS` in the cache, so switching to that was a problem until merging in the PR to have Zeek call `find_package(CAF ...)` itself.  So open question might be whether `FindCAF.cmake` should set a cache entry for `CAF_INCLUDE_DIRS` (don't know, don't care enough to pursue :)).
