### ISSUE TITLE
it is not clear to be it was ever correct for BRO to be using GZIP -9

### ISSUE THREAD

**Issue by initconf** [zeek/zeek#614]
broctl log archiving SHOULD NOT BE USING gzip -9 

default : zeekctl-config.sh:compresscmd="gzip -9"

should be please please changed to 

zeekctl-config.sh:compresscmd="gzip"

Reference: https://changelog.complete.org/archives/931-how-to-think-about-compression-part-2 

OR talk to PSB

**Comment by initconf** [comment]
gzip -9 compresses file smaller but takes upto 60% more time to do that. Its highly unoptimal esp in times when logs are huge and storage is cheap. 

some PBS numbers to convince you to Please remove -9 

GZIP-DEFAULT vs DATA-BRO:
1092860102 - 1067044215 = 25815887 bytes larger
1092860102/1067044215 = 1.024 times larger

GZIP9 vs DATA-BRO
1067044259 - 1067044259 = 0bytes

Also note run time of 3min vs 5min: GZIP-DEFAULT takes 60% the time

and this is for 1G file - our files are generally 80-90Gb.

**Comment by jsiwek** [comment]
Not sure the history behind it, but also a bit surprised that our default is to use highest compression level instead of just gzip's own default, so changing this sounds fine to me.  See this as a low-priority (but easy) task for 3.1.0 since it's a simple option for users to change themselves in the meantime.

**Comment by stevesmoot** [comment]
From previous experimentation I totally agree...

S
