### ISSUE TITLE
Allow print() to be redirected to a log

### ISSUE THREAD

**Issue by deejgregor** [zeek/zeek#619]
It would be helpful to be able to have an option to send output from print() to a Zeek log instead of sending to stdout. This will be useful to be able to see debugging output centrally from a cluster along with other Zeek logs.

**Comment by devbali** [comment]
We already have an option to send output from an individual print statement to a file, so would this be a global redef option to send outputs from all print statements to a given file?

**Comment by jsiwek** [comment]
@devbali nice idea, however, I understand this to this to be more about having an option that essentially turns `print` into a form of `Log::write()` which could then go through the remote logging system so that the output is available in a single, centralized log instead of each process creating their own file for it.

**Comment by devbali** [comment]
So would it be worth it to create a Log Val, that you could use in a print statement instead of a File Val like we can do right now? Arguments to the print function can be written to the log.

**Comment by devbali** [comment]
@jsiwek So would something like https://github.com/zeek/zeek/tree/topic/dev/print-to-log be good? This essentially adds two new constants that you redef.

Demo:
Code:
```
type Info: record {
	foo:	count &log;
	bar:	string &log;
	};

redef enum Log::ID += { FOOBAR };

redef Log::print_to_log = T;
redef Log::print_log = FOOBAR;

event zeek_init()
	{
	Log::create_stream(FOOBAR, [$columns=Info, $path="foo"]);
	print 2,"hello world";
	}
```

Log file foo.log:
```
#fields	foo	bar
#types	count	string
2	hello world
```

**Comment by 0xxon** [comment]
To ask the obvious question - what happens when you print something that does not fit your definition of the Info record?

I don't think this is quite the right approach in any case. For prints, I think it is fine to assume that the output is just text - so a single text string. If one wants to add more information into the log-file, I could imagine adding a timestamp, and very potentially the location at which the print was called.

I don't think it makes sense to require the user to set the info record - I would opt just being able to specify an output file name (and have everything else hardcoded).

But - just my opinion.

**Comment by jsiwek** [comment]
I'm thinking same as Johanna: automatically stringify all `print` arguments into a single field and also add a timestamp field.

**Comment by jsiwek** [comment]
This feature is now in `master` via #687
