### ISSUE TITLE
Remove deprecated functionality

### ISSUE THREAD

**Issue by 0xxon** [zeek/zeek#631]
Remove functionality that was deprecated in Zeek 3.0 for 3.1

**Comment by rsmmr** [comment]
Something to mull over: As I've been working on this, I realized it's hard to draw a boundary around what of the renaming workarounds might be worth keeping. In my branch I'm currently taking a hard stance and am removing *everything*. However, that's pretty harsh. For example, it means we would no longer read any `.bro` files, meaning that most existing  packages will break. We could keep supporting `.bro`, but then what about things like ZeekControl options, environment variables, symlinks to binaries, etc.? Where's the boundary? In principle we could also keep all of that but (1) it increases code complexity, and (2) people might not get the nudge they need to upgrade. Also, if not removing these things now, then when? Never?

**Comment by rsmmr** [comment]
Some huddling produced this strategy for handling renaming related pieces: We'll turn all current warnings into hard errors with 3.1: Zeek won't start. For the `.bro` filename extension--because we are currently not reporting that at all--we'll start warning, and then remove (or hard break) with 4.1 (which is the next opportunity to remove stuff we now deprecate).

**Comment by rsmmr** [comment]
New version in `topic/robin/631-deprecation-v2` in repositories zeek, zeekctl, zeek-doc, zeek-aux.

I'll do some more testing/review before opening a PR.

**Comment by jsiwek** [comment]
Done via #758
