### ISSUE TITLE
How to install kafka plugin for zeek instead of for bro?

### ISSUE THREAD

**Issue by qimingBD** [zeek/zeek#680]
I have installed zeek, not bro, and I want to install a kafka plugin for zeek, however only 'apache/metron-bro-plugin-kafka' was found.
`[root@wqmdev2 zeek]# zkg search /kafka/
zeek/apache/metron-bro-plugin-kafka - A Bro log writer plugin that sends logging output to Kafka.

[root@wqmdev2 zeek]# zkg install apache/metron-zeek-plugin-kafka --version master
error: invalid package "apache/metron-zeek-plugin-kafka": package name not found in sources and also not a usable git URL (invalid or inaccessible, use -vvv for details)
`

**Comment by jsiwek** [comment]
Whatever name is shown by `zkg search` or `zkg list` is the name you have to use with `zkg install`.  In this case, the name is "metron-bro-plugin-kafka".  A package can work for either a Bro or Zeek installation independent of the package name, which is also up to the package author whether they'd like to change to use "zeek" in the name rather than "bro".
