### ISSUE TITLE
zeek 3.0.0 Failed to listen on INADDR_ANYL: 47760

### ISSUE THREAD

**Issue by siemenslt123** [zeek/zeek#697]
zeek version: 3.0.0
system version: centos 7

After I execute the following command:
                zeekctl scripts 

I get these error information:
              error in /opt/zeek/spool/tmp/check-config-zeek/standalone-layout.zeek, failed to listen on INADDR_ANY: 47760(Broker::listen(Broker::default_listen_address,Broker::default_port, Broker::default_listen_retry))

Could anybody help me ? thanks so much.

**Comment by jsiwek** [comment]
That's a bug and should be fixed in the `master` branch with this patch:

https://github.com/zeek/zeekctl/commit/17f3b239f5551d8a9050a8d26a254e516db5c393

Otherwise, the workaround for Zeek 3.0.x is to run `ZEEKCTL_DISABLE_LISTEN=1 zeekctl scripts` instead of `zeekctl scripts` while Zeek is running.  Using just `zeekctl scripts` also still does work if nothing is running yet via `zeekctl deploy` or `zeekctl start`, so you could potentially `zeekctl stop` just to look at the scripts.

**Comment by siemenslt123** [comment]
Got it, thanks, jsiwek!
