### ISSUE TITLE
IO loop not processing queued events promptly

### ISSUE THREAD

**Issue by jsiwek** [zeek/zeek#773]
Observed the following on Linux, in case that matters.  Running this gives expected behavior of relatively short time-to-execute:

```
$ time zeek -b ../testing/btest/core/recursive-event.zeek
...
real	0m1.126s
user	0m0.192s
sys	0m0.029s
```

But simply removing the `-b` flag takes a lot longer:

```
$ time zeek ../testing/btest/core/recursive-event.zeek 
...
real	1m10.552s
user	0m0.443s
sys	0m0.057s
```

Didn't look into details of why, but possibly the IO loop needs to not block as long as there's a pending event in the queue and ready to be processed.

**Comment by timwoj** [comment]
The problem is that if there's an event that gets queued while kevent is waiting, it will continue to wait until the timeout happens. I had considered making event manager an IOSource so it could control it's own queue via kevent, but decided not to. In the normal case of incoming network traffic, `Drain()` gets called as part of the normal loop. Perhaps it actually makes sense to do that now.
