### ISSUE TITLE
ZEEK 3.0.1 vulnerability? Analyzer can be halted with a specific ENIP/CIP data stream.

### ISSUE THREAD

**Issue by kaelanfouwels** [zeek/zeek#785]
Hello,

We have encountered CIP traffic which causes our analyser to cease to analyse packets. This does not crash zeek, nor the analyser, but prevents any future (malicious) events from being logged by it.

No errors or events are raised, the analyser simply stops logging.

This is fully deterministic, with the analyser ceasing to process after CIP packet 0x171E (TCP seq 9972) in the sequence. This does not occur when the packet and it's surrounding context are
 removed from the pcap, indicating a potential issue with handling the overall connection?

I have re-created the issue in a new minimal "analyzer", which does not perform any actions besides dumping the CIP header fields to the console - it is seen that even with this messages cease to be output after the packet above is seen, indicating a potential issue within the zeek engine itself, rather than an implementation error within our analyzer. (This is attached)

This occurs in both datagram, and flowunit mode.

Other analysers running continue to log events concurrently.

Injecting the pcap over existing CIP traffic halts the analyser for all connections, indicating that is is halting the analyser for all traffic, not simply causing the connection to be ignored.

A PCAP of the traffic, and the test analyser (with dockerfile) used are attached.

This was encountered using zeek v3.0.1, built from source on ubuntu 18.04 (see dockerfile). This occurs when building with Ninja, and with the standard makefile generator.

[zeek-test-analyzer.zip](https://github.com/zeek/zeek/files/4170400/zeek-test-analyzer.zip)
[CIP_HALT_PCAP.zip](https://github.com/zeek/zeek/files/4170395/CIP_HALT_PCAP.zip)
[Dockerfile.txt](https://github.com/zeek/zeek/files/4170397/Dockerfile.txt)

**Comment by jsiwek** [comment]
The capture missed some packets and you can see `ENIPLG_Analyzer::Undelivered()` get called to indicate the gap in the TCP stream and sets the `had_gap = true;` state such that the following code path in `ENIPLG_Analyzer::DeliverStream()` gets taken and prevents any further data in the stream from being parsed/analyzed.

```c++
	if ( had_gap )
		// If only one side had a content gap, we could still try to
		// deliver data to the other side if the script layer can handle this.
		return;
```

There's generally many existing analyzers in Zeek that do not have any logic to react and re-synchronize the parser to the data stream in the event of a content gap.  If your parser/analyzer *can* be written a way that is resilient to content gaps, you're free to change this logic in your plugin, but otherwise it's more of a known-deficiency associated with packet loss/drops and there's also plans for future mechanisms that more generally allow parsers to re-synchronize to the stream after a gap is observed.

See the following info and follow up with security@zeek.org if you find any further security issues/concerns:

https://www.zeek.org/contact/index.html#reporting-a-security-vulnerability
