### ISSUE TITLE
Zeek has a problem with extracted file feature

### ISSUE THREAD

**Issue by phamphuqui1998** [zeek/zeek#807]
Dear DevTeam,
I have built test lab with Bro Stand-alone and got a problem with extracted file feature. Bro can not extracted file succeed when I downloaded file through HTTP and do not generate any log files. Beside that, sometimes file was extracted with seen_bytes less than total bytes but missing_bytes and overflow_bytes equal zero. 
Would you please help me fix this issue?
Thanks

**Comment by jsiwek** [comment]
If packets are getting dropped you could end up with no log files.  Or if just the packets at the end of the connection are dropped and Zeek times it out, that might be a case where you'd see `seen_bytes < total_bytes` and zero `missing_bytes` and zero `overflow_bytes`.

I'd first check if your capture setup is losing packets and, if not, it's hard to help diagnose the problem further unless you can send along a pcap that reproduces the unexpected file extraction behavior.

**Comment by phamphuqui1998** [comment]
Thank for answer, but we're monitor network real-time, and I realize that all file captured on our network less than 10kB (all of our test cases)

![image](https://user-images.githubusercontent.com/22283229/74998699-ff61ac80-548b-11ea-97c0-4ffacf2289bf.png)
 
![image](https://user-images.githubusercontent.com/22283229/74998726-130d1300-548c-11ea-8a72-4e5fe2445096.png)

Would you please help me?
Thanks

**Comment by jsiwek** [comment]
Unless you can provide a pcap file to reproduce, it's hard to tell you definitively what's happening, but usually when people don't see a file being extracted/analyzed like they expect, it's because not all packets were received and the analyzer (HTTP in this case) can't deal with a gap in the TCP stream.  You can also check/show your conn.log to see if the `missed_bytes` is non-zero or for other indication that the connection carrying the file you were expecting didn't get seen by Zeek in its entirety.

**Comment by phamphuqui1998** [comment]
I tried to 2 ways: written pcap by tcpdump and running Zeek real-time. The first way, file was extracted successfully but the second way, file only succeed if file size less than 10kB.
- Pcap: https://drive.google.com/open?id=16k8Igd3_39_8lqtuwFI-IadOxxr9537G

- The first way example:
- Video: https://youtu.be/Rid1e-6Z5c4
- Logs: https://drive.google.com/open?id=1i3QOqN7CzRAlZbfoo02subInosY5IxvH

- The second way example:
- Video: https://youtu.be/SsqF-O1oK10
- Logs: https://drive.google.com/open?id=1gYbU59JcYT9R14b133qcw6noDDtOOGtG

Sorry for bothering you, but I hope you can fix this issue
Thanks!

**Comment by jsiwek** [comment]
Thanks for the extra info, it helps.  In the realtime logs you can see the `missed_bytes` being 10000 and also `weird.log` shows `truncated_tcp_payload`.  You should look into increasing the "snaplen" setting since the default is 9216 and the pcap you gave starts exceeding that:

https://docs.zeek.org/en/current/scripts/base/init-bare.zeek.html#id-Pcap::snaplen

For example, you could run like `zeek -C -i any ../extract.bro Pcap::snaplen=20000` (or use whatever number makes sense in relation to the interface's MTU as reported by `ifconfig`).
