### ISSUE TITLE
References in `TableVal::ExpandAndInit()`

### ISSUE THREAD

**Issue by MaxKellermann** [zeek/zeek#811]
The method `TableVal::ExpandAndInit()` confuses me. Does it inherit the references to the parameters `index` and `new_val`?
If yes, why does it never release them (except for one single branch)?
If no, why does it release the `index` here?
https://github.com/zeek/zeek/blob/38b25cf38db3a79b0f536be9f774e1a3698106ac/src/Val.cc#L1709-L1711
And why does it allocate `new_index` but never releases it?
If I knew how this (undocumented) method was designed, I could try to fix it... either way, it's bugged.

**Comment by jsiwek** [comment]
Hard to answer questions of the "why?" type without falling into infinite regress, but here's a couple shallow reasons that may help as you come across oddities like this in the code base:

* Looks like this function is only used in the one-time initialization path, so got lucky in terms of reference count underflows and also no one noticed (or cared about) leakage since it's not in the main run-time loop
* Seems untouched at least for ~10 years since the import to git, and maybe even survived closer to 20+ years from a time when documenting intent either wasn't prioritized or not even imagined to be helpful to people of the far future that happen to come across and review it

That in mind, and after looking at the few calls to it, I'd say we can just make a decision about how we'd like it to work regardless of original intent. My first thought is to change both the implementation and call sites to agree that the function is taking ownership of a reference to each argument.
