### ISSUE TITLE
Workers overload CPU when used Exec::run or ActiveHTTP::request in script

### ISSUE THREAD

**Issue by winnie22** [zeek/zeek#838]
Hi,
I was probably hit by the same bug mentioned in this thread http://mailman.icsi.berkeley.edu/pipermail/zeek/2020-February/015062.html. After upgrading bro 2.6 to zeek 3.0, zeek stared to overload CPU in upredictable manners. I run zeek in cluster mode. Overloading started usually on one process and then spread across all other. When process hit 100% CPU usage there is no way to lower the usage until restart. In my case I was able to identify that the cause is async (when) call on my custom script calling HTTP API. I used Exec::run, then rewrote to ActiveHTTP::request (same curl call as I saw) without any change. For example MHR skript with lookup_hostname_txt in async call works without an issue. I tried compiling zeek without mentioned commit in the mailing thread but the bug is still present and it is present even for zeek 3.1. I attach perf top output and backtrace for zeek 3.0 and 3.1. If I can provide any more details on this bug, please let me know.

Platform Centos 7, kernel 5.4/5.5 (elrepo)

[zeek31_bt.txt](https://github.com/zeek/zeek/files/4280116/zeek31_bt.txt)
[zeek30_bt.txt](https://github.com/zeek/zeek/files/4280117/zeek30_bt.txt)
![zeek31_perf](https://user-images.githubusercontent.com/6103248/75757388-8d625080-5d32-11ea-8619-96feb9060545.png)
![zeek30_perf](https://user-images.githubusercontent.com/6103248/75757390-8dfae700-5d32-11ea-96ec-bc2305c05527.png)

**Comment by jsiwek** [comment]
> In my case I was able to identify that the cause is async (when) call on my custom script calling HTTP API. I used Exec::run, then rewrote to ActiveHTTP::request (same curl call as I saw) without any change. For example MHR skript with lookup_hostname_txt in async call works without an issue.

That's interesting; do you have any more information about how you came to that conclusion, such as example scripts that could be used to reproduce the behavior?  How frequently were requests/execs happening?  In my own attempts to reproduce, I found that generally over enough time with many requests I can overload CPU in either Bro 2.6 and Zeek 3.0 with the later getting overloaded a bit faster, but both settling back down after some time when requests cease.

There were internal changes to the way asynchronous `when` statements work between Bro 2.6 and Zeek 3.0, but not quite sure that explains the difference.  For example, you pointed out that use of the MHR script isn't a problem even though it uses an asynchronous `when`.   A difference in `Exec::run()` or `ActiveHTTP` is that those use a `when` combined with Input Framework reader thread, so that may indicate potential issue lies in the Input Framework, though I don't know any suspicious difference introduced there between Bro 2.6 and Zeek 3.0.

Do you generally see any suspicious error messages in your `reporter.log` that may indicate points of interest ?

> I tried compiling zeek without mentioned commit in the mailing thread but the bug is still present and it is present even for zeek 3.1

There were two commits mentioned.  For completeness, did you patch out both of them or just one?

If you are up for running other patches/instrumentations, here is one you can apply to Zeek 3.0 that will log more information about busy IOSources into `reporter.log`:

[zeek-3.0-iosource-stats.patch.txt](https://github.com/zeek/zeek/files/4285009/zeek-3.0-iosource-stats.patch.txt)

**Comment by winnie22** [comment]
Hi, 
PoC script attached. You just need to generete API key for Virustotal and append this lines to local.zeek:

@load frameworks/files/vt_check
redef VTCHECK::vt_apikey = "[API KEY]"

Usually, I am able to reproduce the issue in less then 20 http calls for first process to , whole processed traffic is about 1Gbps at this sensor.  Report.log is empty (file doesn't exists).

I tested these commits in separate, I can try both.

Last thing I forgot to mention is that I use AF packet modul but don't think it's related. I will try your patch ASAP and let you know. Thanks for your help.

[vt_check.zeek.txt](https://github.com/zeek/zeek/files/4287676/vt_check.zeek.txt)

**Comment by jsiwek** [comment]
A potential fix (at least for the issue in the mailing list) is incoming via the patch at https://github.com/zeek/broker/pull/97

Still not sure if you're seeing the same thing or a different issue, so please try out that patch and report your findings.

**Comment by winnie22** [comment]
Don't want to be too excited, but after 2 hours running zeek 3.0.2 + patch zeek/broker#97 + your stats patch and couple hundred http calls no CPU overload happend. I will keep you posted.

**Comment by winnie22** [comment]
After a day I didn't hit the issue, I think this issue is fixed. Awesome work @jsiwek! Thanks

**Comment by jsiwek** [comment]
Cool, thanks for reporting back, seems safe to assume it was the same problem.  Looking again at your description makes sense why you didn't see the issue upon removing the Exec/ActiveHTTP/Input usage: the bug in Broker is essentially hidden when Zeek's threading system is inactive.  Since you're running in cluster mode w/ remote logging, there's no logging threads to activate the threading system, but the use of Input threads does activate it.  For people running standalone mode w/ local logging, they didn't need to use Input threads at for the issue to crop up because they already had logging threads.

**Comment by winnie22** [comment]
Thanks for clarification!

**Comment by winnie22** [comment]
Confirm fix in 3.0.3
