### ISSUE TITLE
I can not download the all the submodules with --recursive option

### ISSUE THREAD

**Issue by Wapiti08** [zeek/zeek#849]

**Comment by timwoj** [comment]
Is git giving any errors? Can you try `git submodules update --init --recursive`?

**Comment by Wapiti08** [comment]
Some module or check --- not found or failed. 
But finally it said the configuration completed.

I noticed your issue for WSL downloading problem. I have some problems on WSL.

**Comment by Wapiti08** [comment]
> Is git giving any errors? Can you try `git submodules update --init --recursive`?

I did what you mentioned. It did not help. I download all the submodules manually already and met a init problem when I used the zeekctl.

**Comment by jsiwek** [comment]
We can't make much suggestion unless you give exact commands and error output, but there shouldn't generally be any problem with recursively cloning (even on WSL, which I just tried) unless it's an issue with your network or git config/version (or possibly you're sitting at some odd commit and just need to `git pull && git submodule update --recursive --init`).

I don't recommend using WSL in the first place since it's not an officially support platform and mostly untested.  If you still want to use it, you're already aware that Zeek 3.1.0+ currently won't work at all (from #842), but Zeek 3.0.x may still work with most obvious limitation of not being able to monitor a live interface (there's also a minor difference in extended floating point results).

**Comment by Wapiti08** [comment]
Thanks for your advice. The network did exist a problem for me. I think it is not a problem from the project. I will figure it out. Cheers!
