### ISSUE TITLE
Preservation of Case in HTTP headers

### ISSUE THREAD

**Issue by benjeems** [zeek/zeek#854]
Bumping this as an issue here: 
Currently zeek Upper Cases HTTP header names. This removes information which can be important in use cases where Case matters.   Lot's of good discussion including some use cases here:
https://bro-tracker.atlassian.net/browse/BIT-1431
and here 
https://bro-tracker.atlassian.net/browse/BIT-1923

It seems like we need to keep the existing uppercase headers as they may be used downstream , however can we also make the case preserved version available ?

**Comment by jsiwek** [comment]
Yeah, like what was suggested in earlier, I'd steer towards adding new parameters to all events to pass along the case-preserved header (think that may be `http_header`, `http_all_headers`, `mime_one_header`, and `mime_all_headers` events).

Changing event signature is currently a breaking change (unless we implement something like #418 / #262), but I wouldn't worry much in this case since it should be "easy" to adapt scripts to it (and we do have some clunkier ways people can use `@if` directives if they need to support multiple Zeek versions).

**Comment by anthonykasza** [comment]
@jsiwek What are your thoughts on creating a redefinable scriptland flag which controlled whether names are lowercased or not? No events would need added/modified. The default value for the flag could be the existing behavior.

**Comment by jsiwek** [comment]
@anthonykasza nice idea, though not too sure the "No events would need added/modified" bit is true -- the issue with a flag to switch behavior is that existing/external event handlers (maybe written by separate author in a package) are still assuming the current semantics and could break upon flipping that flag.  i.e. it's a weird mix of "the code I wrote works with the flag flipped, but I also didn't realize this other package I was relying on expected the old behavior and is now broke without any obvious indication".

So still think best thing here is to add a new parameter to the relevant events.  Now that #892 is merged, doing that isn't a breaking change, so there's no longer any concerns/gotchas for that way forward.
