### ISSUE TITLE
Improve vector comparisons

### ISSUE THREAD

**Issue by sethhall** [zeek/zeek#870]
Right now to compare vectors, the following must be done...

```
event zeek_init()
        {
        local v1 = vector("abc", "def");
        local v2 = vector("abc", "def");

        if ( all_set(v1 == v2) )
                print "yep!";
        }
```

I did it that way because the "result" from `v1 == v2` is a new vector `[T,T]`.  all_set then checks to see if all vector members are T.  It would be nice if the return value from `v1==v2` was a simple bool.

**Comment by jsiwek** [comment]
Agree, but I guess just to follow process for "breaking changes" it could be worth seeking feedback at least from the mailing list so we have an additional record of "nobody objected" as justification.

**Comment by vpax** [comment]
I'd suggest that if we go this route, we implement it not by changing the semantics of `v1 == v2` (i.e., still have it return `vector of bool`), but instead the semantics a `vector of bool` value when used in a scalar boolean context.  This is because the vector-operations-return-vectors paradigm is quite powerful, and I think we should keep it coherent/consistent.

**Comment by jsiwek** [comment]
@vpax great idea, though found a possibility ambiguity w/ current ternary conditionals:

```zeek
local bv1 = vector(T, F, T);
print bv1 ? vector(F, F, F) : vector(T, T, T);
```

That has a special meaning and produces `[F, T, F]` -- indices of the test condition are used to combine indices of *either* branch in the result but generally allowing `vector of bool` in scalar `bool` contexts shifts expectation for it to select the whole value from one branch *or* the other.

Seems dangerous/unexpected to leave the behavior stand for that narrow case (same-sized `vector of bool` operands), but causes a subtle, easy-to-miss breakage if altered.

**Comment by vpax** [comment]
Good catch.  (Didn't realize those semantics even worked!)  But then I'd argue for not making any change.  In R, for example, it's very cool that (1) you can use same-lengthed boolean vectors as selectors in arrays, and (2) comparison operators applied to vectors produce same-lengthed boolean vectors.  Let's you write things like `x[x > 5]` to get a vector that is all of the elements of `x` that are larger than 5.  If we want that sort of functionality, then `vb1 == vb2` needs to produce a vector and not a scalar for boolean variables, otherwise we'll have weird inconsistencies.

**Comment by jsiwek** [comment]
Yeah, I'm now uncomfortable w/ either change.  I forgot how many specialized treatments of `vector of bool` already existed, might become inconsistent, or block other desirable features.  Then also unfortunate to discover incompatible ternary semantics when going in to look.

Maybe the lamer thing to offer is a new BIF: `vec_eq(v1, v2)` (or one can currently write their own function).

**Comment by benjeems** [comment]
I didn’t know about all_set, my mind lept straight to just hashing the vectors and comparing that. Maybe more efficient than n element comparisons?.
event zeek_init()
        {
        local v1 = vector("abc", "def");
        local v2 = vector("abc", "def");

        if ( md5_hash(v1) == md5_hash(v2))
                print "yep!";
        }

Ben

**Comment by vpax** [comment]
I wouldn't expect hashing to be any faster, as it still has to fetch and compute over every element in both vectors.  In the case where the vectors differ, it still has to look at every element, whereas an element-by-element comparison can stop early.

**Comment by 0xxon** [comment]
> Yeah, I'm now uncomfortable w/ either change. I forgot how many specialized treatments of `vector of bool` already existed, might become inconsistent, or block other desirable features. Then also unfortunate to discover incompatible ternary semantics when going in to look.
> 
> Maybe the lamer thing to offer is a new BIF: `vec_eq(v1, v2)` (or one can currently write their own function).

just to second that - I also think we should not change this behavior. Adding a bif seems like an ok way to go - even though not quite as nice looking.

**Comment by sethhall** [comment]
After coming back to this and reading the comments, I'm inclined to just close this ticket?  Creating a special purpose bif for this doesn't seem much better than the existing (slightly goofy) trick that I originally put in the ticket.  What does everyone else think?

**Comment by vpax** [comment]
That's also my read of the thread.
