### ISSUE TITLE
zeek debug plugin parameter does not complain if plugin does not exist

### ISSUE THREAD

**Issue by simonhf** [zeek/zeek#913]
Recently I git cloned a zeek plugin, built it, and then wanted to add additional instrumentation (to understand it better) via the `PLUGIN_DBG_LOG()` macro mentioned here [1].

While adding the debug macros worked fine, I had difficulties switching on the debugging via the `zeek --debug` option. Why? Because the plugin name to be specified is case sensitive and if you get it wrong then there is no warning or error... and zeek runs but no debug output is generated and the user is left wondering what went wrong. E.g. `zeek --debug plugin-zeek-myplugin` silently fails whereas `zeek --debug plugin-Zeek-Myplugin` works.

It would be great and more intention-revealing if wrongly specified plugin names -- like in the above example -- actively fail. 

[1] https://docs.zeek.org/en/current/devel/plugins.html#debugging-plugins

**Comment by Samhita-sopho** [comment]
I could take up this issue

**Comment by rsmmr** [comment]
@Samhita-sopho still up for giving it a try?

**Comment by matyasalfoldi** [comment]
Hi, I would like to ask if this task is still up for grabs.
The way I see it, inside 
void DebugLogger::Log(const plugin::Plugin& plugin, const char* fmt, ...)
The lines:
if ( enabled_streams.find(tok) == enabled_streams.end() )
		return;
Are responsible for it, since enabled_streams will contain whatever was given with the -B flag,
so simply adding an fprintf like in the lines below should resolve this issue.

Also at first glance in DebugLogger.h lines 64,65 it seems as if the format attribute is given incorrectly with 3,4 instead of 2,3. (May be wrong, since I haven't looked to deep into it, but thought I would share it.)

**Comment by rsmmr** [comment]
`DebugLogger::Log` is where the output is eventually suppressed. The check would need to happen earlier: when all plugins are loaded, we'll need to see if all the labels given to the `-B` flag are accounted for. There's a place for this check already here: https://github.com/zeek/zeek/blob/master/src/DebugLogger.cc#L127. However, as the comment there says, that won't work there because at the time this method executes, not all plugins may have been loaded yet. I think what I'd do is extend this method to record all the `plugin-*` tags into an internal set; and then later, when all plugins have been loaded, come back to that and check if all of them are accounted for by the plugins now available.

Yes, 3/4 should be 2/3, good catch! Want to prepare a PR for that one as well?

**Comment by matyasalfoldi** [comment]
Will check if I can build it on my Win machine, since my Linux one has some issues currently, and will go for it then. Might take a bit, since I have my hands full with some other projects.
Also it is fine if someone else does the 3/4, 2/3 modification, important is that the bug gets fixed.

**Comment by Samhita-sopho** [comment]
@rsmmr I lost my way finding the solution, since @matyasalfoldi pointed out the problem , if the 3/4 , 2/3 modification is still open I can try my best shot at it.

**Comment by rsmmr** [comment]
Looks good, please file a PR.
