### ISSUE TITLE
Integrate Zeek with OSS-Fuzz

### ISSUE THREAD

**Issue by matrizzo** [zeek/zeek#915]
Hello,

We're reaching out because Zeek is an important part of the open source ecosystem. We would like to invite you to integrate with [OSS-Fuzz](https://google.github.io/oss-fuzz/), Google's free [fuzzing](https://en.wikipedia.org/wiki/Fuzzing) service for open source projects. OSS-Fuzz will continuously fuzz your code to identify security vulnerabilities and other bugs in your project and notify you when it finds issues. OSS-Fuzz is already fuzzing [hundreds of open source projects](https://github.com/google/oss-fuzz/tree/master/projects) and helping their developers find and remediate [critical security issues](https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+).

If you are interested, check out our [getting started guide](https://google.github.io/oss-fuzz/getting-started/). We even offer [rewards](https://opensource.googleblog.com/2017/05/oss-fuzz-five-months-later-and.html) for open source projects that integrate with OSS-Fuzz.

Let us know if you have any questions, or check out [our FAQ](https://google.github.io/oss-fuzz/faq/).

Matteo,
Google Security Engineering Team

**Comment by JustinAzoff** [comment]
Hi!

This is definitely something we are interested in.   I have done a few fuzzing experiments using afl-fuzz and have found a handful of bugs that way.  I have some questions that would need to be worked out for the OSS-Fuzz integration.

The libfuzzer faq states that

> Usually, the narrower the target the better. E.g. if your target can parse several data formats, split it into several targets, one per format.

This applies here,  since we parse many different protocols.  Do we *have* to build one target per format, like zeek-fuzz-ssl, zeek-fuzz-pop3, or can it be one binary that takes a --analyzer argument?  If we can't do arguments we could build a zeek-fuzz target that looks at argv[0] and then make symlinks for each protocol.  Normally zeek would just do dynamic protocol detection, but that goes against the 'one per format' recommendation. 

The new Structure-Aware Fuzzing features look amazing, are you aware of anyone working on a custom mutator for pcap files?  My last experiments I used what you call the 'Magic separator' approach to build a custom simplified packet format:

https://github.com/zeek/zeek/commit/f9889cb67b9fb8476d096d9a3b5345a5401f5d2b#diff-cc629382de3fddca8c8fb9bd9f0e065e

but it requires 'test-only code'.  A pcap mutator would be more work but could benefit many projects.

**Comment by matrizzo** [comment]
> Do we have to build one target per format, like zeek-fuzz-ssl, zeek-fuzz-pop3, or can it be one binary that takes a --analyzer argument?
There should be a separate binary for each parser because it keeps the corpus for each target separated

> are you aware of anyone working on a custom mutator for pcap files?
No, not that I know of

**Comment by JustinAzoff** [comment]
Ok,  so I think this is the plan:

* Resurrect the libfuzzer integration and get it working again, since the upstream git repo changes caused the cmake stuff to bitrot.  For oss-fuzz take note of what https://google.github.io/oss-fuzz/getting-started/new-project-guide/#buildsh says about $LIB_FUZZING_ENGINE
* Either build one target for each analyzer, or have the resulting analyzer fuzzer binary look at argv[0]  so we can symlink it to zeek-fuzz-analyzer-{http,dns,ssl}.

@jsiwek can help me get the cmake bits working, I can get the rest of the oss-fuzz integration done, which includes the initial corpus and dict files, based on the previous experiments i did.

**Comment by JustinAzoff** [comment]
Spent some time trying to get a basic integration working.   I have some libfuzzer based code working, but trying to run it using the oss-fuzz scripts (https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally)  I ran into 2 problems related to the fuzzing environment itself:

1) scripts: we can ./configure --prefix=$OUT/local in the build script, but ZEEKPATH won't be set when the fuzzer is ran and I don't think the $OUT variable exists in the runtime environment.  We also can't source zeek-path-dev.sh as far as I know.  We may be able to just have the fuzzer initialization set ZEEKPATH based on argv[0].

2) static linking: the fuzzer binaries need to be statically linked.  We have options for broker and binpac that get most of the way there, but we still end up dynamically linking against libpcap and libssl.

**Comment by JustinAzoff** [comment]
Some other things we should  look into.  From the libfuzzer docs:

> In many cases it makes sense to build a special fuzzing-friendly build with certain fuzzing-unfriendly features disabled. We propose to use a common build macro for all such cases for consistency: FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION.

```void MyInitPRNG() {
#ifdef FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
  // In fuzzing mode the behavior of the code should be deterministic.
  srand(0);
#else
  srand(time(0));
#endif
}
```
Not sure where that would go in `init_random_seed` exactly though.

The other place that would be useful is around the `Reporter::RuntimeError` and `Reporter::ExprRuntimeError`, like

```
#ifdef FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION
    abort()
#endif
```

For fuzzing raw packets, we should also enable ignore_checksums when fuzzing.

**Comment by JustinAzoff** [comment]
I just noticed @jsiwek already did all that, awesome!

**Comment by jsiwek** [comment]
Just noting that the Zeek-side infrastructure for adding fuzzers is now in `master` via #931 and the process for adding an OSS-Fuzz project is started here: https://github.com/google/oss-fuzz/pull/3799

**Comment by matrizzo** [comment]
Awesome, thanks for letting me know.

**Comment by jsiwek** [comment]
We're now accepted into OSS-Fuzz.

Next step would be to add more fuzz targets (@JustinAzoff if you had any ready to make PRs for, go for it).
