### ISSUE TITLE
double_to_interval() return value prints as a double, not as an interval

### ISSUE THREAD

**Issue by vpax** [zeek/zeek#985]
This one is weird.  The following

> event zeek_init()
        {
        local a = 5.0;
        local b = 6.0 sec;
        print a, interval_to_double(double_to_interval(a));
        print b, double_to_interval(interval_to_double(b));
        }

prints
> 5.0, 5.0
6.0 secs, 6.0

even though `type_name` shows that the return value from `double_to_interval` has type `interval`.  (The same holds if just doing it directly, e.g., `double_to_interval(5.0)`.)

**Comment by jsiwek** [comment]
Thanks, yeah that's weird.  Looks like there's a specific subclass, `IntervalVal` with overridden `ValDescribe()` to help do that prettier printing, but the BIF doesn't use it:

```diff
diff --git a/src/zeek.bif b/src/zeek.bif
index 77d3a1183..5f176b7f8 100644
--- a/src/zeek.bif
+++ b/src/zeek.bif
@@ -2404,7 +2404,7 @@ function double_to_time%(d: double%): time
 ## .. zeek:see:: interval_to_double
 function double_to_interval%(d: double%): interval
	%{
-	return make_intrusive<Val>(d, TYPE_INTERVAL);
+	return make_intrusive<IntervalVal>(d, Seconds);
	%}

 ## Converts a :zeek:type:`port` to a :zeek:type:`count`.
```

If we're going to want the specific handling for intervals, may be best to just deprecate this constructor and add `TimeVal`/`DoubleVal` subclasses, too, since it's easy to accidentally mis-use it for intervals:

https://github.com/zeek/zeek/blob/94ef9f45421afd3a13cc7c1862f7b9dead18621d/src/Val.h#L128-L131

**Comment by vpax** [comment]
Good eye, Jon!  I had stared at the same code but the issue eluded me.

Re other subclasses, yeah, makes sense.
